const ERRORS = {
  welllink_invalid_due_date:'Choose a valid follow-up date.',
  welllink_access_required:'WellLink is available to authorized program staff. Ask Damon if you need access.',
  welllink_changed_refresh:'This step changed while you were editing. Copy your notes and reload before saving again.',
  welllink_evidence_required:'Add an evidence reference before marking this step complete.',
  welllink_task_forbidden:'Only the assigned owner or an administrator can update this step.',
  welllink_unavailable:'WellLink could not be loaded. Please try again.',
  invalid_case_quantity:'Enter a whole number of cases from 1 to 10,000.',
  invalid_reporting_month:'Choose a valid reporting month from June 2026 onward.',
  invalid_gross_purchases:'Enter a nonnegative amount with no more than two decimal places.',

  corrected_total_changed_review_again:'The corrected total changed. Refresh and review the carrier cost, markup and tax before saving.',
  shipment_recovery_authority_required:'This correction belongs to Ashley, Darren or Damon according to the action selected.',
  shipped_stock_cannot_be_reversed:'This shipment has left the warehouse. Use the return and accounting review process; stock cannot be restored here.',
  reservation_reconciliation_required:'The reservation and inventory quantities do not agree. Reconcile them before retrying.',
  return_to_planning_before_correction:'Return this shipment to planning before correcting its unpaid freight invoice.',
  paid_or_posted_invoice_requires_reconciliation:'This invoice has payment or accounting activity. Ashley must reconcile it before a correction can be made.',
  shipment_not_recoverable:'The shipment is no longer in a state that supports this correction. Refresh to review it.',
  warehouse_custody_confirmation_required:'Confirm that all allocated goods are still in the warehouse.',
  carrier_void_evidence_required:'Void the label in the carrier system first, then enter the carrier’s void confirmation.',
  carrier_outcome_needs_reconciliation:'The carrier outcome is uncertain. Verify it with the carrier before changing this shipment.',
  shipment_cancelled:'This allocation was cancelled. Review it with Damon before making further changes.',
  invoice_closed:'This invoice is closed. Reconcile the accounting record before applying any further payment or write-off.',
  cancelled_order_payment_requires_reconciliation:'This shipment or order was cancelled. Ashley must reconcile the payment and refund position.',
  payment_amount_requires_cents:'Enter a payment amount with no more than two decimal places.',
  invoice_balance_requires_reconciliation:'Invoice totals, payments and balance do not agree. Reconcile the source amounts first.',
  invoice_currency_requires_reconciliation:'This invoice uses an unsupported currency. Reconcile it in accounting.',
  session_identity_stale:'Your account details changed. Sign in again.',

  quote_pricing_review_required:'Review the current quote prices before issuing. Existing verified account prices can be retained.',
  valid_price_and_landed_cost_required:'A valid price and verified landed cost are required for a new price.',
  pricing_authority_required:'Only Jacobe or Damon may approve new customer prices.',
  delivered_price_review_required:'Shipping or tax changed or the review expired. Review the delivered total again.',
  price_and_reason_required:'Enter a valid price for every line and a review reason.',
  customer_and_lines_required:'Choose an active customer and add at least one product.',
  product_not_found:'This SKU is not in the catalog. Check the exact variant SKU.',
  quote_only:'This product needs a sourced quote and verified cost before a price can be assigned.',
  quote_locked:'This quote is already accepted or declined and cannot be repriced.',
  duplicate_quote_line:'Use one line per SKU and combine its quantity.',

  shipment_invoice_required:'Review the freight amount and create this shipment’s invoice first.',
  customer_freight_approval_required:'Jacobe must record the customer’s approval of the complete invoice total.',
  later_freight_payment_pending:'Record full payment against this freight invoice before release.',
  shipment_invoice_locked:'This shipment has a recorded invoice or release. Reconcile it before changing its allocation or charges.',
  existing_allocation_needs_reconciliation:'Stock was already reserved for the whole order. Reconcile that reservation before splitting it.',
  shipment_already_released:'This shipment was already released. Refresh to see its current step.',
  allocation_shortfall:'There is not enough available stock for this shipment.',
  owner_allocation_shortfall:'There is not enough eligible stock belonging to this inventory owner.',
  lot_allocation_shortfall:'The eligible lot quantities do not cover this shipment. Reconcile stock first.',
  carrier_label_evidence_required:'Enter the carrier, tracking number, and issued label reference after stock is reserved.',
  shipment_not_ready:'Record the carrier label before confirming custody.',
  jacobe_customer_approval_required:'Customer approval must be recorded by Jacobe.',
  use_freight_invoice_payment:'Record this payment against the separate freight invoice in Finance.',

  records_changed_refresh:'Another action changed these records. Refresh and review the current information.',
  financial_evidence_changed:'The amount or payment evidence changed. Create a new review before proceeding.',
  ashley_release_required:'Ashley must review the payment before this order can be released.',
  ashley_review_required:'This review belongs to Ashley’s accounting account.',
  independent_damon_approval_required:'Damon must approve after Ashley’s review.',
  other_order_holds_remain:'This order has another hold. Resolve it before clearing payment release.',
  credit_approval_required:'Damon must approve the credit exception first.',
  payment_or_approved_credit_required:'Confirmed payment or an approved credit-release decision is required.',
  invalid_decision_amount:'Use a positive amount within the current balance. Credit release must cover the entire unpaid balance.',
  review_evidence_required:'Add a review note and the bank, accounting, or supporting evidence reference.',
  damon_approval_required:'Damon’s approval is required before this action.',
  use_shipment_workspace:'Release this order one shipment at a time in the shipment workspace.',

  customers_unavailable:'Customer records are temporarily unavailable. Please try again.',
  payment_reference_conflict:'This reference was already recorded with different payment details. Check the existing entry before using another reference.',
  invoice_overpayment:'The amount exceeds the remaining invoice balance. Refresh and check the payment evidence.',
  payment_evidence_required:'Enter the bank or accounting reference for the confirmed payment.',
  held_reservations_required:'Stock has not been reserved for this shipment. Ask operations to resolve the stock hold before recording handoff.',
  payment_not_released:'Payment has not cleared for release. Ask finance to review this order.',
  handoff_already_recorded:'Carrier handoff has already been recorded. Refresh to see its current status.',
  rma_state_changed_retry:'This return changed during review. Refresh and review the latest decision.',
  work_changed_refresh:'This record changed while you were reviewing it. Copy any unsaved notes, discard the draft, then refresh and review the latest details before saving.',
  work_item_unavailable:'This item is no longer available in your work queue. Refresh to see current work.',
  next_action_required:'Add a next action so the team knows what to do.',
  invalid_due_date:'Choose a valid follow-up date and time.',
  work_unavailable:'The team workspace is temporarily unavailable. Please refresh.',
  inquiry_changed_refresh:'This inquiry was updated by someone else. Refresh before saving.',
  inquiry_note_required:'Add a short note explaining the status change.',
  damon_final_approval_required:'Damon must record the final approval.',

  damon_approval_authority_required:'Only Damon’s configured administrator account can make this decision.',
  order_changed_review_again:'This order changed. Reload its details and review it again.',
  order_changed_retry:'This order changed. Refresh before continuing.',
  review_delivered_price_before_payment:'Confirm this order’s shipping and tax before setting up payment.',
  shipping_origin_not_configured:'The warehouse shipping address needs to be configured before this review can be saved.',
  shipping_review_requested:'Your shipping and tax review is queued. Refresh the estimate after Unite confirms it.',
  refresh_shipping_and_tax:'This estimate expired or your order changed. Get shipping and tax again.',
  review_changed_refresh:'Another reviewer updated this request. Refresh the list.',
  freight_and_tax_required:'Enter both freight and tax, including an explicit zero when applicable.',
  preserved_exemption_requires_review:'This account has a preserved exemption. Resolve the tax discrepancy before saving.',
  records_changed_preview_again:'Customer records changed. Generate a new merge preview.',
  commercial_policy_conflict:'These accounts have different pricing, credit or tax policies. Reconcile them before merging.',
  contract_price_conflict:'Both accounts have a price for the same SKU. Reconcile those prices first.',
  membership_conflict_review_required:'A person belongs to both accounts. Review their membership before merging.',
  stripe_not_configured:'Payment processing is not connected yet.',
  provider_invoice_total_mismatch:'The provider invoice does not match the reviewed total. Finance must reconcile it before sending.',
  order_changed_payment_reconciliation_required:'The order changed during payment setup. Finance must reconcile the provider invoice.',
  mfa_encryption_not_configured:'Authenticator sign-in needs server configuration.',

  authentication_required:'Please sign in again.', not_configured:'This service is not connected yet.',
  private_storage_not_configured:'Document storage is not connected yet. Please contact Unite support.',
  shopify_not_configured:'Shopify read access is not connected on staging yet.',
  not_found:'This action is available on the configured staging environment only.',
  shopify_order_changed:'The Shopify order changed. Refresh the preview before continuing.',
  profile_not_pending_activation:'This account does not need activation, or it needs review first.',
  activation_email_missing:'Add a valid customer email before creating an activation link.',
  clean_scan_required:'The document needs a completed security scan before approval.',
  file_too_large:'Choose a file smaller than 4 MB.',
  content_type_not_allowed:'Choose a PDF, PNG or JPEG file.',
  file_signature_invalid:'This file could not be verified as a PDF or image.',
};
export async function workspaceRequest(url, options={}) {
  let response;
  try { response=await fetch(url,{credentials:'include',...options}); }
  catch { throw new Error('Could not connect. Check your connection and try again.'); }
  const body=await response.json().catch(()=>null);
  if(!response.ok || !body?.ok) throw new Error(ERRORS[body?.error] || (response.status===401?'Please sign in again.':response.status===403?'This account does not have access.':'Could not complete this action. Try again or contact support.'));
  return body;
}
export function postWorkspace(url,body) { return workspaceRequest(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); }
