import crypto from 'node:crypto';
import {orderApprovalGate} from './orderApproval.js';
const closed=new Set(['closed','resolved','cancelled','delivered','refunded','paid','completed','received','acknowledged','approved']);
const idFor=(kind,id)=>`ex_${crypto.createHash('sha256').update(`${kind}:${id}`).digest('hex').slice(0,24)}`;
export function buildOperationsDesk(tables,now=new Date()){
 const rows=[];const orgs=(tables.organizations||[]).filter(o=>o.status!=='merged');
 function add(kind,row,{title,next,path,severity='attention',due,owner,impact='Customer waiting'}={}){
  const org=orgs.find(o=>o.id===(row.customer_id||row.org_id));
  const ownerEmail=owner||row.assigned_owner_email||row.account_owner_email||org?.account_owner_email||org?.owner_email||null;
  const candidate=due||row.due_at||row.response_due_at;
  const created=Date.parse(row.created_at||row.placed_at);
  const deadline=Number.isFinite(Date.parse(candidate))?new Date(candidate).toISOString():new Date((Number.isFinite(created)?created:now.getTime())+86400000).toISOString();
  rows.push({id:idFor(kind,row.id),kind,source_id:row.id,title,customer_id:org?.id||row.customer_id||row.org_id||null,customer_name:org?.name||row.customer_name||'',owner_email:ownerEmail,due_at:deadline,severity,customer_impact:impact,next_action:next,path,status:'open',source_version:crypto.createHash('sha256').update(JSON.stringify(row)).digest('hex')});
 }
 for(const r of tables.orders||[]){if(closed.has(r.status))continue;if(!orderApprovalGate(r).ok)add('approval',r,{title:`Approve order ${r.id}`,next:'Review commercial details and record a decision.',path:`/admin/orders?order=${encodeURIComponent(r.id)}`,owner:'damon@unitemedical.net'});else if(['pending','failed','awaiting_payment'].includes(r.payment_status))add('payment',r,{title:`Payment needed · ${r.id}`,next:'Review payment evidence before release.',path:'/admin/finance'});}
 for(const r of tables.invoices||[])if(!closed.has(r.status)&&Date.parse(r.due_date)<now.getTime())add('overdue_invoice',r,{title:`Overdue invoice ${r.id}`,next:'Assign collection follow-up and record the customer response.',path:'/admin/finance',due:r.due_date,severity:'urgent'});
 const specs=[['checkout_reviews','packing','Checkout review','/admin/packing','Review packed dimensions, freight and tax evidence.'],['sourcing_requests','sourcing','Sourcing response','/admin/sourcing','Review offers or update the customer.'],['backorders','backorder','Backorder','/admin/fulfillment','Confirm availability and update the customer; do not invent an ETA.'],['distributor_pickups','pickup','Pickup','/admin/fulfillment','Confirm collection arrangements and notify the warehouse.'],['returns','return','Return','/admin/fulfillment','Review receipt, quarantine and inspection evidence.'],['vendor_bills','supplier_bill','Supplier bill','/admin/finance','Match PO, accepted receipt and invoice.'],['purchase_orders','supplier_ack','Supplier acknowledgment','/admin/purchase-orders','Follow up with the vendor and record acknowledgment.']];
 for(const [table,kind,title,path,next] of specs)for(const r of tables[table]||[])if(!closed.has(r.status)&&!(table==='purchase_orders'&&r.status==='draft'))add(kind,r,{title:`${title} · ${r.id}`,path,next});
 for(const r of tables.shipments||[])if(['exception','delivery_failed','lost','delayed'].includes(r.status))add('carrier',r,{title:`Delivery exception · ${r.order_id||r.id}`,path:'/admin/fulfillment',next:'Confirm carrier evidence and give the customer an update.',severity:'urgent'});
 for(const r of tables.organizations||[])if(r.status!=='merged'&&(r.credit_status==='suspended'||r.commerce_hold_reason))add('account_hold',{...r,org_id:r.id},{title:`Account hold · ${r.name}`,path:'/admin/customers',next:'Review pricing, credit or verification evidence.'});
 for(const r of tables.tax_certificate_versions||[])if(r.review_status!=='approved'||(r.expires_at&&Date.parse(r.expires_at)<now.getTime()))add('tax',r,{title:'Tax document review',path:'/admin/documents',next:'Review scan and document evidence. Missing documents alone do not revoke a preserved exemption.',impact:'Document follow-up'});
 for(const table of ['customerio_outbox','gmail_outbox','notification_outbox'])for(const r of tables[table]||[])if(['dead_letter','provider_unknown','failed','sent_stale_revision'].includes(r.status))add('notification_failure',r,{title:`Communication needs review · ${r.ref_id||r.id}`,path:'/admin/integrations',next:'Reconcile provider evidence before retrying; do not resend an uncertain delivery.',severity:'urgent'});
 for(const r of tables.webhook_events||[])if(['dead','failed','dead_letter'].includes(r.status))add('integration',r,{title:`Integration failure · ${r.type||r.id}`,path:'/admin/integrations',next:'Review the error and retry with the same idempotency key.',severity:'urgent',impact:'Workflow may be delayed'});
 // Use observed customer cadence; no fixed reorder interval invented for all accounts.
 for(const org of orgs){const dates=[...new Set((tables.orders||[]).filter(o=>o.customer_id===org.id&&!['cancelled','refunded'].includes(o.status)).map(o=>Date.parse(o.placed_at)).filter(Number.isFinite))].sort((a,b)=>a-b);if(dates.length<3)continue;const gaps=dates.slice(1).map((d,i)=>d-dates[i]).sort((a,b)=>a-b);const cadence=gaps[Math.floor(gaps.length/2)];if(cadence<86400000)continue;const due=dates.at(-1)+cadence*1.5;if(now.getTime()>due)add('missed_reorder',{...org,org_id:org.id,updated_at:new Date(dates.at(-1)).toISOString()},{title:`Check in with ${org.name}`,next:'Review the last orders and ask whether needs have changed.',path:'/admin/customers',due:new Date(due).toISOString(),impact:'Reorder later than observed pattern'});}
 const states=new Map((tables.operational_exceptions||[]).map(r=>[r.id,r]));
 return rows.map(r=>{const state=states.get(r.id);const merged=state?.source_version===r.source_version?{...r,owner_email:state.owner_email??r.owner_email,due_at:state.due_at||r.due_at,next_action:state.next_action||r.next_action,notes:state.notes||'',version:state.version||0}:r;return {...merged,version:state?.version||0,escalated:!merged.owner_email||Date.parse(merged.due_at)<now.getTime(),escalation_owner:'damon@unitemedical.net'};}).sort((a,b)=>Number(b.escalated)-Number(a.escalated)||Date.parse(a.due_at)-Date.parse(b.due_at));
}
export const DESK_TABLES=['customerio_outbox','gmail_outbox','notification_outbox','checkout_reviews','orders','organizations','invoices','sourcing_requests','backorders','distributor_pickups','returns','vendor_bills','purchase_orders','shipments','tax_certificate_versions','webhook_events','operational_exceptions'];
