import crypto from 'node:crypto';
import {CRM_STAGES,LEAD_FIELDS} from '../../src/lib/crmSchema.js';
import {exaRequest,websetItems} from './prospectExa.js';
const text=(v,n=500)=>String(v??'').trim().slice(0,n);
export function safeWebUrl(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:'';}catch{return '';}}
export function domain(value){try{return new URL(value.includes('://')?value:'https://'+value).hostname.toLowerCase().replace(/^www\./,'');}catch{return '';}}
const generic=new Set(['gmail.com','yahoo.com','hotmail.com','outlook.com','aol.com','icloud.com','live.com','msn.com','comcast.net','att.net','sbcglobal.net','me.com','no-reply.com']);
const social=new Set(['linkedin.com','facebook.com','instagram.com','x.com','twitter.com']);
export function companyKey(value){return text(value).toLowerCase().replace(/\b(incorporated|inc|llc|ltd|corporation|corp)\b/g,'').replace(/[^a-z0-9]/g,'');}
export function customerExclusions(customers){return {domains:new Set(customers.map(c=>(c.email||'').toLowerCase().split('@')[1]).filter(d=>d&&!generic.has(d))),names:new Set(customers.flatMap(c=>[c.company,...(c.addresses||[]).map(a=>a.company)]).filter(Boolean).map(companyKey).filter(n=>n.length>5))};}
export function isExistingCustomer(lead,exclusions){const d=domain(lead.website),e=lead.email?.split('@')[1];return (d&&!social.has(d)&&exclusions.domains.has(d))||(e&&!generic.has(e)&&exclusions.domains.has(e))||exclusions.names.has(companyKey(lead.company));}
export function leadFromExa(item,list){
 const p=item.properties||{},c=p.company||p.person?.company||{},person=p.person||{},enrichments=(item.enrichments||[]).map(e=>({...e,description:list.enrichments?.find(x=>x.id===e.enrichmentId)?.description||'',title:list.enrichments?.find(x=>x.id===e.enrichmentId)?.title||list.enrichments?.find(x=>x.id===e.enrichmentId)?.description||'Enrichment'}));
 const result=pattern=>enrichments.find(e=>pattern.test(e.title+' '+(e.description||''))&&e.status==='completed')?.result?.join('\n')||'';
 const website=safeWebUrl(p.type==='person'?(c.url||c.website||''):p.url),identity=p.type==='person'?safeWebUrl(p.url):(!social.has(domain(website))?domain(website):'')||companyKey(c.name)||item.id;
 const outreach=result(/outreach angle/i),brandMismatch=/\b(NHS|staffing|revalidation|locum)\b/i.test(outreach);
 const now=new Date().toISOString(),id='lead_'+crypto.createHash('sha256').update((p.type||'company')+':'+identity).digest('hex').slice(0,24),hq=c.headquarters||{};
 const email=text(result(/business email|email/i),254).toLowerCase(),contact=result(/buying contact|buyer contact|publicly named owner/i).split('|').map(s=>s.trim());
 return {id,revision:0,kind:p.type||'company',company:text(c.name||p.custom?.name||'Unnamed organization'),contact_name:text(person.name||(contact[0]==='Not found'?'':contact[0]),1000),job_title:text(person.position||contact[1]),email:/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(email)?email:'',phone:text(result(/business phone|phone/i),100),website,linkedin:p.type==='person'?safeWebUrl(p.url):safeWebUrl(c.linkedinUrl),location:text(c.location||person.location),address:text(hq.address),city:text(hq.city),state:text(hq.state),postal_code:text(hq.postalCode),country:text(hq.country||hq.countryCode),industry:text(c.industry),employees:c.employees??null,segment:text(result(/segment|org type|classify into/i)),description:text(p.description||c.about,5000),product_interest:text(result(/product fit|product-fit|publicly evidenced offerings/i),5000),outreach_angle:brandMismatch?'Research mixed up Unite with another organization. Draft a new introduction from the cited prospect evidence.':text(outreach,4000),stage:'new',owner:'',expected_value:null,next_follow_up:'',close_date:'',next_action:'Review research and confirm the buying contact',tags:[],notes:'',do_not_contact:false,archived:false,list_ids:[list.id],source:'Exa Websets',source_url:safeWebUrl(p.url),source_item_id:item.id,created_at:now,updated_at:now,user_fields:[],events:[{id:crypto.randomUUID(),at:now,actor:'Exa research',text:'Added to pre-leads. No outreach sent.'}],research:{review_notes:brandMismatch?['The generated outreach angle appears to refer to a different Unite Medical. Do not use it.']:[],item_id:item.id,webset_id:list.id,properties:p,evaluations:item.evaluations||[],enrichments,verified_at:item.updatedAt,fit:!brandMismatch&&(item.evaluations||[]).length&&(item.evaluations||[]).every(e=>e.satisfied==='yes')?'matched':'needs_review'}};
}
export function validateLeadPatch(input){
 const allowed=new Set([...LEAD_FIELDS.map(f=>f[0]),'stage','do_not_contact','archived']);const patch={};
 for(const [key,value] of Object.entries(input||{})){
  if(!allowed.has(key))throw new Error('This lead field cannot be changed: '+key);
  if(['do_not_contact','archived'].includes(key)){if(typeof value!=='boolean')throw new Error('Use true or false for '+key);patch[key]=value;}
  else if(key==='stage'){if(!CRM_STAGES.some(s=>s.id===value))throw new Error('Choose a valid pipeline stage.');patch[key]=value;}
  else if(['expected_value','employees'].includes(key)){if(value===null||value==='')patch[key]=null;else{const n=Number(value);if(!Number.isFinite(n)||n<0||n>1e10)throw new Error('Enter a valid positive number.');patch[key]=n;}}
  else if(key==='tags'){if(!Array.isArray(value)||value.length>30)throw new Error('Use up to 30 tags.');patch[key]=[...new Set(value.map(v=>text(v,80)).filter(Boolean))];}
  else{patch[key]=text(value,['notes','product_interest'].includes(key)?10000:1000);if(key==='company'&&!patch[key])throw new Error('Company is required.');if(key==='email'&&patch[key]&&!/^[^\s<>@,;]+@[^\s<>@,;]+\.[^\s<>@,;]+$/.test(patch[key]))throw new Error('Enter a valid business email.');if(['website','linkedin'].includes(key)&&patch[key]&&!safeWebUrl(patch[key]))throw new Error('Enter a full http or https URL.');if(['next_follow_up','close_date'].includes(key)&&patch[key]&&(!/^\d{4}-\d{2}-\d{2}$/.test(patch[key])||Number.isNaN(Date.parse(patch[key]))||new Date(patch[key]).toISOString().slice(0,10)!==patch[key]))throw new Error('Use a date in YYYY-MM-DD format.');}
 }
 return patch;
}
export async function getLead(sql,id){const row=(await sql`SELECT data FROM um_rows WHERE tbl='crm_leads' AND id=${id} AND deleted=false`)[0]?.data;if(!row)throw new Error('Lead not found.');return row;}
export async function saveLead(sql,id,revision,input,actor){const current=await getLead(sql,id);if(Number(revision)!==Number(current.revision||0))throw new Error('This lead changed. Reload before saving.');const patch=validateLeadPatch(input),now=new Date().toISOString();const next={...current,...patch,revision:Number(current.revision||0)+1,updated_at:now,user_fields:[...new Set([...(current.user_fields||[]),...Object.keys(patch)])],events:[...(current.events||[]),{id:crypto.randomUUID(),at:now,actor:actor.name||actor.email||actor.user_id,text:'Updated '+Object.keys(patch).map(k=>k.replaceAll('_',' ')).join(', '),changes:Object.fromEntries(Object.keys(patch).map(k=>[k,{before:current[k],after:patch[k]}]))}].slice(-200)};const r=await sql`UPDATE um_rows SET data=${JSON.stringify(next)}::jsonb,updated_at=now() WHERE tbl='crm_leads' AND id=${id} AND deleted=false AND COALESCE((data->>'revision')::integer,0)=${Number(revision)} RETURNING id`;if(!r.length)throw new Error('This lead changed. Reload before saving.');return next;}
export async function listLeads(sql,{q='',stage='',lane='',list_id='',page=0,limit=100,archived=false}={}){
 if(lane&&!['prelead','pipeline'].includes(lane))throw new Error('Use lane prelead, pipeline, or an empty string for all.');
 if(stage&&!CRM_STAGES.some(s=>s.id===stage))throw new Error('Unknown stage. Use a CRM stage ID, or an empty string for all active records.');
 if(list_id&&!/^webset_[a-zA-Z0-9]+$/.test(list_id))throw new Error('Use an exact saved-search ID, or an empty string for all lists.');
 const search='%'+text(q,100).toLowerCase()+'%',stages=CRM_STAGES.filter(s=>s.lane===lane).map(s=>s.id),size=Math.min(100,Math.max(1,Number(limit)||100)),offset=Math.max(0,Number(page)||0)*size,showArchived=archived===true||archived==='true';
 const rows=await sql`SELECT data,COUNT(*) OVER()::int AS total FROM um_rows WHERE tbl='crm_leads' AND deleted=false AND COALESCE((data->>'archived')::boolean,false)=${showArchived} AND (${stage}='' OR data->>'stage'=${stage}) AND (${lane}='' OR data->>'stage'=ANY(${stages}::text[])) AND (${list_id}='' OR (data->'list_ids') ? ${list_id}) AND lower(CONCAT_WS(' ',data->>'company',data->>'contact_name',data->>'email',data->>'industry',data->>'segment',data->>'owner',data->>'notes')) LIKE ${search} ORDER BY updated_at DESC,id LIMIT ${size} OFFSET ${offset}`;
 let total=rows[0]?.total;
 if(total===undefined)total=(await sql`SELECT COUNT(*)::int AS total FROM um_rows WHERE tbl='crm_leads' AND deleted=false AND COALESCE((data->>'archived')::boolean,false)=${showArchived} AND (${stage}='' OR data->>'stage'=${stage}) AND (${lane}='' OR data->>'stage'=ANY(${stages}::text[])) AND (${list_id}='' OR (data->'list_ids') ? ${list_id}) AND lower(CONCAT_WS(' ',data->>'company',data->>'contact_name',data->>'email',data->>'industry',data->>'segment',data->>'owner',data->>'notes')) LIKE ${search}`)[0]?.total||0;
 return {rows:rows.map(r=>r.data),total,page:Number(page)||0,page_size:size,paging_note:!rows.length&&total?'Pages start at 0. Matching records exist; request page 0.':undefined,has_more:offset+rows.length<total};
}
export async function crmSummary(sql){const rows=await sql`SELECT data->>'stage' AS stage,COUNT(*)::int AS count,COUNT(*) FILTER(WHERE COALESCE(data->>'email','')<>'')::int AS with_email,COUNT(*) FILTER(WHERE COALESCE(data->>'phone','')<>'')::int AS with_phone,COUNT(*) FILTER(WHERE COALESCE(data->>'contact_name','')<>'')::int AS with_contact FROM um_rows WHERE tbl='crm_leads' AND deleted=false AND COALESCE((data->>'archived')::boolean,false)=false GROUP BY data->>'stage'`;return {total:rows.reduce((n,r)=>n+r.count,0),with_email:rows.reduce((n,r)=>n+r.with_email,0),with_phone:rows.reduce((n,r)=>n+r.with_phone,0),with_contact:rows.reduce((n,r)=>n+r.with_contact,0),stages:rows,archived_excluded:true,source:'Live Unite CRM',note:'Published contact details; not email deliverability verification.'};}
export async function saveProspectList(sql,webset){const data={...webset,last_synced_at:new Date().toISOString()};await sql`INSERT INTO um_rows(tbl,id,data) VALUES('prospect_lists',${webset.id},${JSON.stringify(data)}::jsonb) ON CONFLICT(tbl,id) DO UPDATE SET data=um_rows.data||EXCLUDED.data,updated_at=now() RETURNING id`;return data;}
export async function syncProspectList(sql,id){
 const existing=(await sql`SELECT data FROM um_rows WHERE tbl='prospect_lists' AND id=${id} AND deleted=false`)[0]?.data;if(!existing)throw new Error('Choose a Unite prospect list.');const webset=await exaRequest('/websets/'+id),customers=await sql`SELECT data FROM um_rows WHERE tbl='commerce_customers' AND deleted=false`,exclusions=customerExclusions(customers.map(r=>r.data));let cursor,seen=0,excluded=0,added=0;
 for(let page=0;page<10;page++){const data=await websetItems(id,cursor);for(let start=0;start<(data.data||[]).length;start+=10){await Promise.all(data.data.slice(start,start+10).map(async item=>{seen++;const lead=leadFromExa(item,webset);if(isExistingCustomer(lead,exclusions)){excluded++;return;}
 const previous=(await sql`SELECT data FROM um_rows WHERE tbl='crm_leads' AND id=${lead.id} AND deleted=false`)[0]?.data;
 if(!previous){const r=await sql`INSERT INTO um_rows(tbl,id,data) VALUES('crm_leads',${lead.id},${JSON.stringify(lead)}::jsonb) ON CONFLICT(tbl,id) DO NOTHING RETURNING id`;added+=r.length;}
 else{const next={...previous,research:lead.research,list_ids:[...new Set([...(previous.list_ids||[]),id])],updated_at:new Date().toISOString(),revision:Number(previous.revision||0)+1};for(const field of LEAD_FIELDS.map(f=>f[0]))if(!previous.user_fields?.includes(field)&&lead[field]!==''&&lead[field]!==null&&field!=='owner'&&field!=='next_action'&&field!=='notes'&&field!=='tags')next[field]=lead[field];if(!previous.user_fields?.includes('product_interest'))next.outreach_angle=lead.outreach_angle;if(JSON.stringify({...next,updated_at:previous.updated_at,revision:previous.revision})===JSON.stringify(previous))return;await sql`UPDATE um_rows SET data=${JSON.stringify(next)}::jsonb,updated_at=now() WHERE tbl='crm_leads' AND id=${lead.id} AND COALESCE((data->>'revision')::integer,0)=${Number(previous.revision||0)}`;}}));}
 if(!data.hasMore)break;cursor=data.nextCursor;
 }
 const count=(await sql`SELECT COUNT(*)::int AS n FROM um_rows WHERE tbl='crm_leads' AND deleted=false AND (data->'list_ids') ? ${id}`)[0]?.n||0;
 return saveProspectList(sql,{...webset,sync:{provider_results:seen,existing_customers_excluded:excluded,added,crm_count:count}});
}
export async function createProspectSearch(sql,input,actor){
 const {searchSpec,DEFAULT_ENRICHMENTS}=await import('./prospectExa.js');
 const recent=await sql`SELECT COUNT(*)::int AS n FROM um_rows WHERE tbl='prospect_requests' AND data->>'actor'=${actor.user_id} AND updated_at>now()-interval '1 hour'`;
 if(recent[0]?.n>=5)throw new Error('Five searches were started this hour. Review their results before starting more.');
 const spec=searchSpec({...input,exclude_import_id:undefined});spec.enrichments=DEFAULT_ENRICHMENTS;
 const previous=(await sql`SELECT data FROM um_rows WHERE tbl='prospect_lists' AND deleted=false ORDER BY updated_at DESC LIMIT 1`)[0]?.data;
 const exclusions=previous?.searches?.flatMap(s=>s.exclude||[]).filter(x=>x.source==='import')||[];
 if(exclusions.length)spec.search.exclude=[...new Map(exclusions.map(x=>[x.id,x])).values()];
 const id=input.request_id||crypto.randomUUID();spec.externalId='unite-'+id;
 await sql`INSERT INTO um_rows(tbl,id,data) VALUES('prospect_requests',${id},${JSON.stringify({actor:actor.user_id,query:spec.search.query})}::jsonb) ON CONFLICT(tbl,id) DO NOTHING`;
 const webset=await exaRequest('/websets',spec);await saveProspectList(sql,webset);return webset;
}
