import crypto from 'node:crypto';
import {STAFF_ROLES} from '../../src/lib/staffWorkspace.js';
// Explicit scope: unknown tables and identity/security configuration are preserved.
export const RESET_TABLES=new Set(`products product_variants categories pricing inventory carts cart_items orders order_items shipments shipment_items invoices payments quotes quote_items leads contacts activities tasks qbo_invoices flexport_shipments shipstation_labels stripe_payments stripe_invoices hubspot_contacts hubspot_companies hubspot_deals gmail_outbox customerio_events po_receipts surplus_submissions surplus_lines product_compliance compliance_events purchase_orders vendor_bills vendor_bill_variances vendor_bill_approvals daily_digests trade_records shortage_requests calendar_events surplus_offers rep_payouts documents webhook_events fulfillment_pipeline backorders rmas tier_pricing catalog_visibility shopify_orders shopify_products shopify_history_rows stock_movements lots lot_tracking reservations count_sessions count_lines transfers transfer_lines bundles customer_contract_prices volume_breaks account_payment_methods account_prices account_notification_recipients reorder_lists reorder_list_items rep_order_grants inventory_lots distributor_products scan_events consignment_movements consignment_settlement_links distributor_notifications distributor_pickups distributor_pickup_events distributor_documents distributor_po_uploads distributor_sku_map cross_references quote_misses sourcing_requests vendor_offers po_communications recall_notice_drafts customerio_outbox quote_signer_challenges customer_external_identities customer_migration_records customer_migration_runs marketing_consents staging_imports legacy_shopify_migrations financial_decisions order_batches payment_requests quote_revisions quote_acceptances quote_acceptance_evidence quote_acceptance_events returns ar_payments settlement_payments settlement_candidates accounting_reconciliation checkout_estimates checkout_reviews accounting_tasks public_inquiries inquiry_notifications notification_outbox staff_followups tax_certificates tax_certificate_versions receipt_locks label_operations manual_payment_identities`.split(' '));
export const isStaff=p=>[p?.role,...(p?.roles||[])].some(r=>STAFF_ROLES.includes(r));
export function planWorkspaceReset(rows){
 const active=rows.filter(r=>!r.deleted),staff=active.filter(r=>r.tbl==='profiles'&&isStaff(r.data));
 const staffIds=new Set(staff.map(r=>r.id)),staffOrgs=new Set(staff.map(r=>r.data.org_id).filter(Boolean));
 const customerIds=new Set(active.filter(r=>r.tbl==='profiles'&&!isStaff(r.data)&&['customer','distributor'].includes(r.data.role)).map(r=>r.id));
 const customerOrgs=new Set(active.filter(r=>r.tbl==='profiles'&&customerIds.has(r.id)).map(r=>r.data.org_id));
 for(const r of active)if(r.tbl==='organizations'&&!staffOrgs.has(r.id))customerOrgs.add(r.id);
 const targets=active.filter(r=>RESET_TABLES.has(r.tbl)||r.tbl==='profiles'&&customerIds.has(r.id)||r.tbl==='organizations'&&customerOrgs.has(r.id)&&!staffOrgs.has(r.id)||r.tbl==='organization_users'&&!staffIds.has(r.data.user_id)&&(customerIds.has(r.data.user_id)||customerOrgs.has(r.data.org_id))||['addresses','activation_tokens'].includes(r.tbl)&&(customerIds.has(r.data.user_id||r.data.profile_id)||customerOrgs.has(r.data.org_id||r.data.customer_id)));
 const holds=active.filter(r=>r.tbl==='legal_holds'&&r.data.status==='active');
 const blocked=targets.filter(r=>r.data.legal_hold===true||holds.some(h=>[r.tbl,'*'].includes(h.data.table)&&(!h.data.record_id||h.data.record_id===r.id)));
 const counts={};for(const r of targets)counts[r.tbl]=(counts[r.tbl]||0)+1;
 const version=crypto.createHash('sha256').update(JSON.stringify(active.map(r=>[r.tbl,r.id,r.updated_at]).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))))).digest('hex');
 return {version,counts,total:targets.length,staff_preserved:staff.length,blocked:blocked.length,targets:targets.map(r=>({tbl:r.tbl,id:r.id}))};
}
