import test from 'node:test';
import assert from 'node:assert/strict';
import {AGENT_MODEL,AGENT_REASONING,agentTools,getAgentCard,prepareAgentChanges,applyAgentCard,exportRows,recordsCsv,callCommerceAgentTool} from '../api/_lib/commerceAgentTools.js';
const actor={user_id:'damon',name:'Damon',email:'damon@unitemedical.net',role:'admin'};
function memorySql(initial=[]){const db=new Map(initial.map(r=>[r.table+':'+r.data.id,structuredClone(r.data)]));let writes=0;const sql=async(strings,...v)=>{const q=strings.join('?').replace(/\s+/g,' ').trim();
 if(q.startsWith('SELECT data FROM um_rows WHERE tbl=? AND id=?')){const data=db.get(v[0]+':'+v[1]);return data?[{data:structuredClone(data)}]:[];}
 if(q.startsWith("SELECT data FROM um_rows WHERE tbl='commerce_agent_cards'")){const data=db.get('commerce_agent_cards:'+v[0]);return data&&data.user_id===v[1]&&data.session_id===v[2]?[{data:structuredClone(data)}]:[];}
 if(q.startsWith("INSERT INTO um_rows(tbl,id,data) VALUES('commerce_agent_cards'")){const key='commerce_agent_cards:'+v[0];if(!db.has(key))db.set(key,JSON.parse(v[1]));return [];}
 if(q.startsWith('UPDATE um_rows SET data=jsonb_set')){const card=db.get('commerce_agent_cards:'+v[0]);if(card?.status!=='pending'||card.user_id!==v[1])return [];card.status='applying';return [{id:card.id}];}
 if(q.startsWith('UPDATE um_rows SET data=?::jsonb,updated_at=now() WHERE tbl=?')){const previous=db.get(v[1]+':'+v[2]);if(!previous||previous.revision!==v[3])return [];db.set(v[1]+':'+v[2],JSON.parse(v[0]));writes++;return [{id:v[2]}];}
 if(q.startsWith("UPDATE um_rows SET data=?::jsonb,updated_at=now() WHERE tbl='commerce_agent_cards'")){db.set('commerce_agent_cards:'+v[1],JSON.parse(v[0]));return [];}
 if(q.startsWith('SELECT data FROM um_rows WHERE tbl=? AND id=ANY'))return [...db.entries()].filter(([k,r])=>k.startsWith(v[0]+':')&&v[1].includes(r.id)).map(([,data])=>({data}));
 throw new Error('Unexpected test query: '+q);
 };return {sql,db,get writes(){return writes;}};}
const customer={id:'100',name:'Customer',notes:'Before',revision:3,addresses:[],price_lists:[],status:'active'};
test('assistant model and tool capabilities are explicit',()=>{assert.equal(AGENT_MODEL,'gpt-6-sol');assert.equal(AGENT_REASONING.effort,'medium');for(const name of ['select_records','propose_changes','export_records','current_selection'])assert.ok(agentTools.some(t=>t.name===name));});
test('preparing an edit produces a before/after preview without writing a record',async()=>{const m=memorySql([{table:'commerce_customers',data:customer}]);const changes=await prepareAgentChanges(m.sql,[{kind:'customers',id:'100',revision:3,patch_json:'{"notes":"After"}'}],actor);assert.equal(m.writes,0);assert.deepEqual(changes[0].diff,[{field:'notes',before:'Before',after:'After'}]);});
test('stale revisions and forbidden fields cannot be proposed',async()=>{const m=memorySql([{table:'commerce_customers',data:customer}]);await assert.rejects(prepareAgentChanges(m.sql,[{kind:'customers',id:'100',revision:2,patch:{notes:'After'}}],actor),/changed/);await assert.rejects(prepareAgentChanges(m.sql,[{kind:'customers',id:'100',revision:3,patch:{role:'admin'}}],actor),/cannot be changed/);assert.equal(m.writes,0);});
test('assistant uses normal credit authority and cross-customer price guards',async()=>{const m=memorySql([{table:'commerce_customers',data:customer},{table:'commerce_price_lists',data:{id:'another',status:'active',customer_id:'200',rows:[]}}]);await assert.rejects(prepareAgentChanges(m.sql,[{kind:'customers',id:'100',revision:3,patch:{credit_limit:1000}}],{...actor,email:'other@example.com'}),/Damon/);await assert.rejects(prepareAgentChanges(m.sql,[{kind:'customers',id:'100',revision:3,patch:{price_lists:['another']}}],actor),/Another customer/);});
test('applying a reviewed card saves with an audit event and is not repeated',async()=>{const m=memorySql([{table:'commerce_customers',data:customer}]);const changes=await prepareAgentChanges(m.sql,[{kind:'customers',id:'100',revision:3,patch:{notes:'After'}}],actor);const card={id:'plan',type:'changes',status:'pending',user_id:'damon',session_id:'session',changes};m.db.set('commerce_agent_cards:plan',card);const result=await applyAgentCard(m.sql,card,actor);assert.equal(result.status,'applied');assert.equal(m.writes,1);assert.equal(m.db.get('commerce_customers:100').notes,'After');assert.match(m.db.get('commerce_customers:100').events[0].actor,/Unite assistant/);await applyAgentCard(m.sql,result,actor);assert.equal(m.writes,1);});
test('a changed record prevents any writes in a reviewed batch',async()=>{const m=memorySql([{table:'commerce_customers',data:customer},{table:'commerce_customers',data:{...customer,id:'200'}}]);const changes=await prepareAgentChanges(m.sql,['100','200'].map(id=>({kind:'customers',id,revision:3,patch:{notes:'After'}})),actor);m.db.get('commerce_customers:200').revision=4;await assert.rejects(applyAgentCard(m.sql,{id:'plan',type:'changes',status:'pending',changes},actor),/changed/);assert.equal(m.writes,0);});
test('cards belong to one person and one chat',async()=>{const m=memorySql([{table:'commerce_agent_cards',data:{id:'card',user_id:'damon',session_id:'s1'}}]);assert.equal((await getAgentCard(m.sql,'card','damon','s1')).id,'card');await assert.rejects(getAgentCard(m.sql,'card','jacobe','s1'),/unavailable/);await assert.rejects(getAgentCard(m.sql,'card','damon','s2'),/unavailable/);});
test('selection and export include all explicit records without mutating them',async()=>{const records=Array.from({length:205},(_,i)=>({table:'commerce_customers',data:{...customer,id:String(i+1)}}));const m=memorySql(records);const result=await callCommerceAgentTool(m.sql,{name:'select_records',call_id:'call1',arguments:{kind:'customers',ids:records.map(r=>r.data.id),all_matching:false,title:'All test customers'}},{actor,sessionId:'s1'});assert.equal(result.selected,205);const card=m.db.get('commerce_agent_cards:'+result.card_id);assert.equal(card.records.length,205);assert.equal(m.writes,0);});
test('address and price exports preserve every nested row; CSV neutralizes formulas',()=>{const rows=exportRows('customers',[{...customer,addresses:[{id:'1',city:'A'},{id:'2',city:'B'}]}],'addresses');assert.equal(rows.length,2);const prices=exportRows('pricing',[{id:'p',name:'Prices',rows:[{sku:'sku1',unit_price:49},{sku:'sku2',unit_price:490}]}],'prices');assert.equal(prices.length,2);assert.throws(()=>exportRows('orders',[],'addresses'));const csv=recordsCsv([{name:'=SUM(A1)',notes:'  +test',value:'A,"B"'}]);assert.match(csv,/'=SUM/);assert.match(csv,/' {2}\+test/);assert.match(csv,/A,""B""/);});
test('all-matching bulk selection reads beyond the first page',async()=>{const all=Array.from({length:237},(_,i)=>({...customer,id:String(i+1)}));const cards=new Map();let pages=0;const sql=async(strings,...v)=>{const q=strings.join('?');if(q.includes('COUNT(*) OVER()')){pages++;return all.slice(v.at(-1),v.at(-1)+v.at(-2)).map(data=>({data,total:all.length}));}if(q.includes("INSERT INTO um_rows(tbl,id,data) VALUES('commerce_agent_cards'")){cards.set(v[0],JSON.parse(v[1]));return [];}throw new Error(q);};const result=await callCommerceAgentTool(sql,{name:'select_records',call_id:'all',arguments:{kind:'customers',all_matching:true,ids:[],query:'',filter:'',customer_id:'',title:'All'}},{actor,sessionId:'s'});assert.equal(result.selected,237);assert.equal(pages,3);assert.equal(cards.get(result.card_id).ids.length,237);});

test('customer lookup and selection supply exact Shopify source links',async()=>{const m=memorySql([{table:'commerce_customers',data:customer}]);const read=await callCommerceAgentTool(m.sql,{name:'read_record',arguments:{kind:'customers',id:'100'}},{actor,sessionId:'s'});assert.equal(read.shopify_url,'https://admin.shopify.com/store/unite-medical/customers/100');const result=await callCommerceAgentTool(m.sql,{name:'select_records',call_id:'source-links',arguments:{kind:'customers',ids:['100'],title:'Customer'}},{actor,sessionId:'s'});assert.equal(result.sample[0].shopify_url,read.shopify_url);assert.equal(m.db.get('commerce_agent_cards:'+result.card_id).records[0].shopify_url,read.shopify_url);});
