import test from 'node:test';
import assert from 'node:assert/strict';
import {buildStaffWorkspace,planStaffFollowup} from '../api/_lib/staffWorkspace.js';
import {financeWorkspace} from '../api/_lib/financeWorkspace.js';
import {planInquiryReview} from '../api/_lib/inquiryReview.js';
import {refundFingerprint} from '../api/_lib/refundApproval.js';
import {staffHome,staffShortcuts} from '../src/lib/staffWorkspace.js';
const now=new Date('2026-09-22T12:00:00Z');
const actors={admin:{role:'admin',email:'damon@unitemedical.net',user_id:'damon',name:'Damon'},sales:{role:'sales',email:'jacobe@unitemedical.net',user_id:'jacobe',name:'Jacobe'},warehouse:{role:'warehouse_operator',email:'warehouse@example.test',user_id:'darren',name:'Darren'},finance:{role:'finance',email:'finance@example.test',user_id:'ashley',name:'Ashley'}};
const tables={
 organizations:[{id:'org',name:'Example Medical',account_owner_email:actors.sales.email,billing_email:'ap@example.test',credit_limit:999,password:'secret'}],
 orders:[{id:'order',customer_id:'org',status:'ready_to_ship',payment_status:'paid',total:100,internal_cost:60,tracking_number:'tracking',created_at:'2026-09-21T12:00:00Z'}],
 order_items:[{id:'line',order_id:'order',sku:'EXAMPLE',qty:2,unit_price:50,vendor_cost:30}],
 invoices:[{id:'invoice',customer_id:'org',order_id:'order',status:'partial',amount:100,paid_amount:40,balance:60,due_date:'2026-09-20',payment_evidence:[{secret:'private'}]}],
 public_inquiries:[{id:'inquiry',company:'Sample Co',name:'Person',email:'person@example.test',kind:'regenicool',owner_email:actors.sales.email,status:'pending_review',message:'Dealer details',request_hash:'private-hash',source_ip_hash:'private-ip'}],
 purchase_orders:[{id:'po',vendor_name:'Supplier',status:'partial',line_items:[{sku:'EXAMPLE',qty:10,received_qty:4,cost:22}],cost:220}],
 quotes:[{id:'quote',customer_id:'org',status:'sent',cost:123,vendor_name:'PRIVATE_VENDOR'},{id:'other-quote',customer_id:'other',status:'sent',account_owner_email:'other@example.test'}],
 tasks:[{id:'task',owner_email:actors.sales.email,subject:'Call customer',kind:'followup',status:'open',payload:{next_action:'Confirm needs',secret:'private'}}],
};
const board=(role,t=tables)=>buildStaffWorkspace(t,actors[role],{now,ashleyEmail:actors.finance.email});
test('customers, distributors, and missing identity cannot get an internal board',()=>{for(const session of [null,{role:'customer'},{role:'distributor'}])assert.equal(buildStaffWorkspace(tables,session).error,'forbidden');});
test('warehouse sees quantities and status without prices, balances, invoices or inquiries',()=>{const b=board('warehouse');assert.ok(b.items.some(r=>r.category==='Incoming'));assert.ok(b.items.some(r=>r.category==='Outgoing'));const text=JSON.stringify(b);for(const secret of ['internal_cost','unit_price','vendor_cost','PRIVATE_VENDOR','private-hash','payment_evidence','Invoice total'])assert.ok(!text.includes(secret),secret);assert.ok(b.items.every(r=>r.team==='warehouse'));assert.match(b.items.find(r=>r.category==='Incoming').summary,/6 units/);assert.ok(b.items.find(r=>r.category==='Outgoing').details.some(d=>d.value==='EXAMPLE · 2 units'));});
test('sales receives assigned accounts and approved inquiry ownership only',()=>{const b=board('sales');assert.ok(b.items.some(r=>r.source_id==='quote'));assert.ok(!b.items.some(r=>r.source_id==='other-quote'));assert.ok(b.items.some(r=>r.source_id==='inquiry'));assert.ok(!JSON.stringify(b).includes('PRIVATE_VENDOR'));const other=buildStaffWorkspace(tables,{role:'sales',user_id:'other',email:'other@example.test'},{now});assert.ok(!other.items.some(r=>r.source_id==='inquiry'));assert.equal(other.capabilities.inquiries,false);});
test('finance gets actual balances and no unrelated inquiry or sales queue',()=>{const b=board('finance');assert.ok(b.items.some(r=>r.category==='Invoice'));assert.ok(!b.items.some(r=>r.category==='Inquiry'||r.category==='Quote'));assert.equal(b.items.find(r=>r.category==='Invoice').details.find(d=>d.label==='Balance').value,'$60.00');});
test('admin sees all teams and can filter without changing their working role',()=>{const b=board('admin');assert.deepEqual(b.views,['all','sales','warehouse','finance','sourcing']);assert.ok(b.items.some(r=>r.category==='Quote'));assert.ok(b.items.some(r=>r.category==='Invoice'));assert.ok(b.items.some(r=>r.category==='Incoming'));});
test('order decision stays with Damon and warehouse only sees a release hold',()=>{const t={...tables,orders:[{...tables.orders[0],total:15000}]};assert.ok(board('admin',t).items.some(r=>r.category==='Approval'&&r.owner_email===actors.admin.email));assert.ok(!board('warehouse',t).items.some(r=>r.category==='Approval'));assert.match(board('warehouse',t).items[0].details.find(d=>d.label==='Release').value,/hold/);});
test('only ready, unsplit orders expose carrier handoff to warehouse',()=>{assert.deepEqual(board('warehouse').items.find(r=>r.category==='Outgoing').actions,['handoff']);for(const patch of [{status:'processing'},{shipment_plan:[{id:'one'},{id:'two'}]}])assert.deepEqual(board('warehouse',{...tables,orders:[{...tables.orders[0],...patch}]}).items.find(r=>r.category==='Outgoing').actions,[]);});
test('follow-up updates do not mutate financial or fulfillment records',()=>{const item=board('warehouse').items[0],before=JSON.stringify(tables);const plan=planStaffFollowup(item,{source_version:item.source_version,version:item.version,state:'waiting',next_action:'Ask for the delivery window',note:'Called the carrier',claim:true,due_at:'2026-09-23T14:00:00Z',status:'shipped',approval:'approved'},actors.warehouse,now);assert.equal(plan.ok,true);assert.equal(plan.row.owner_email,actors.warehouse.email);assert.equal(plan.row.status,undefined);assert.equal(plan.row.approval,undefined);assert.equal(plan.row.version,1);assert.equal(JSON.stringify(tables),before);});
test('stale follow-up versions and changed sources cannot be overwritten',()=>{const item=board('sales').items[0];for(const patch of [{version:10},{source_version:'stale'}])assert.equal(planStaffFollowup(item,{source_version:item.source_version,version:0,state:'open',next_action:'Review',...patch},actors.sales,now).error,'work_changed_refresh');});
test('saving follow-up requires a next action and never allows resolving a business record',()=>{const item=board('sales').items[0],base={source_version:item.source_version,version:0,state:'open',next_action:'Review'};assert.equal(planStaffFollowup(item,{...base,state:'completed'},actors.sales).error,'invalid_work_state');assert.equal(planStaffFollowup(item,{...base,next_action:' '},actors.sales).error,'next_action_required');assert.equal(planStaffFollowup(item,{...base,due_at:'tomorrowish'},actors.sales).error,'invalid_due_date');assert.equal(planStaffFollowup(null,base,actors.sales).error,'work_item_unavailable');});
test('waiting items return as overdue when their follow-up deadline passes',()=>{const item=board('sales').items.find(r=>r.source_id==='quote');const state=planStaffFollowup(item,{source_version:item.source_version,version:0,state:'waiting',next_action:'Call tomorrow',due_at:'2026-09-21T14:00:00Z'},actors.sales,now).row;const updated=board('sales',{...tables,staff_followups:[state]});const saved=updated.items.find(r=>r.id===item.id);assert.equal(saved.work_status,'waiting');assert.equal(saved.overdue,true);assert.equal(saved.next_action,'Call tomorrow');});
test('closed source workflows disappear even if saved follow-up remains open',()=>{const item=board('sales').items.find(r=>r.source_id==='quote');const state=planStaffFollowup(item,{source_version:item.source_version,version:0,state:'open',next_action:'Review'},actors.sales).row;assert.ok(!board('sales',{...tables,quotes:[{...tables.quotes[0],status:'closed'}],staff_followups:[state]}).items.some(r=>r.id===item.id));});
test('refund work moves from accuracy review to Damon based on current amount fingerprint',()=>{const rma={id:'rma',status:'refund_pending',refund_total:85,restocking_fee:15,order_id:'order'};assert.ok(board('finance',{rmas:[rma]}).items.some(r=>r.category==='Refund'));const reviewed={...rma,refund_accuracy_review:{fingerprint:refundFingerprint(rma)}};assert.equal(board('finance',{rmas:[reviewed]}).items.length,0);assert.equal(board('admin',{rmas:[reviewed]}).items[0].owner_email,actors.admin.email);assert.ok(board('finance',{rmas:[{...reviewed,refund_total:75}]}).items.length);});
test('finance projection excludes full customer records and payment credentials',()=>{const rows=financeWorkspace(tables.invoices,tables.organizations);assert.equal(rows[0].balance,60);assert.equal(rows[0].customer_name,'Example Medical');assert.equal(rows[0].payment_evidence,undefined);assert.equal(rows[0].password,undefined);assert.equal(rows[0].credit_limit,undefined);});
test('inquiry changes require a note, detect simultaneous edits, and leave delivery/fees untouched',()=>{const row=tables.public_inquiries[0];assert.equal(planInquiryReview(row,{version:0,status:'closed',note:''},actors.sales).error,'inquiry_note_required');assert.equal(planInquiryReview(row,{version:1,status:'closed',note:'Done'},actors.sales).error,'inquiry_changed_refresh');assert.equal(planInquiryReview(row,{version:0,status:'fee_paid',note:'Done'},actors.sales).error,'invalid_inquiry_status');const out=planInquiryReview(row,{version:0,status:'closed',note:'Request answered',fee_paid:true},actors.sales,now);assert.equal(out.row.review_version,1);assert.equal(out.row.fee_paid,undefined);assert.equal(row.status,'pending_review');});
test('every staff role lands on Today and ordinary staff navigation avoids admin-only tools',()=>{for(const role of ['admin','sales','finance','warehouse_manager','warehouse_operator','sourcing'])assert.equal(staffHome(role),'/work');assert.equal(staffHome('customer'),'/dashboard');assert.deepEqual(staffShortcuts('warehouse_operator').map(r=>r.path),['/work','/staff/welllink','/staff/shipments','/admin/inventory/receive']);assert.ok(staffShortcuts('sales').every(r=>!r.path.startsWith('/admin')));});

test('paid orders remain in outgoing work until shipped; shipped orders leave the queue',()=>{for(const status of ['paid','processing','ready_to_ship'])assert.ok(board('warehouse',{orders:[{...tables.orders[0],status}]}).items.some(r=>r.category==='Outgoing'));for(const status of ['shipped','delivered','cancelled'])assert.equal(board('warehouse',{orders:[{...tables.orders[0],status}]}).items.length,0);});
test('source waiting state is visible before a staff follow-up is saved',()=>{const b=board('sales',{public_inquiries:[{...tables.public_inquiries[0],status:'waiting'}]});assert.equal(b.items[0].work_status,'waiting');assert.equal(b.counts.waiting,1);});
test('sales can see their own sourcing requests without receiving another owners sourcing',()=>{const b=board('sales',{sourcing_requests:[{id:'mine',assigned_owner_email:actors.sales.email,status:'open'},{id:'theirs',assigned_owner_email:'other@example.test',status:'open'}]});assert.deepEqual(b.items.map(r=>r.source_id),['mine']);});
