import test from 'node:test';
import assert from 'node:assert/strict';
import {warehouseRows,filterWarehouseRows,resolveLocation,manualArea,countFormForRow} from '../src/lib/warehouseBrowse.js';
const fixture=()=>({server_time:'2026-09-27T12:00:00Z',products:[{sku:'P',name:'Product',policy:{},pack_verified:true,units_per_case:12}],inventory:[{id:'i',sku:'P',warehouse_id:'w',on_hand:100},{id:'other',sku:'P',warehouse_id:'w',owner_type:'distributor',owner_org_id:'d',on_hand:9}],lots:[{id:'l',product_sku:'P',warehouse_id:'w',bin_id:'b',lot_number:'LOT-1',expiration_date:'2028-01-01',qty_remaining:100}],bins:[{id:'b',code:'A-01',warehouse_id:'w'}],containers:[{id:'PALLET-1',kind:'pallet',sku:'P',warehouse_id:'w',bin_id:'b',lot_id:'l',units_remaining:100,units_per_case:12,state:'sealed'}],counts:[],outgoing_picks:[]});
test('inventory browser preserves owner pools and finds pallets, lots and locations',()=>{const rows=warehouseRows(fixture());assert.equal(rows.length,2);assert.equal(rows[1].lot,null);for(const query of ['pallet-1','LOT-1','product A-01'])assert.equal(filterWarehouseRows(rows,{query}).length,1);assert.equal(filterWarehouseRows(rows,{warehouse:'no'}).length,0);});
test('opening worksheets map their posted lots back to count progress',()=>{const d=fixture();d.counts=[{inventory_id:'i',posted_lot_ids:['l'],status:'posted',counted_at:'2026-09-27'}];assert.equal(warehouseRows(d)[0].status,'counted');});
test('location scans require warehouse disambiguation and preserve exact labels',()=>{const bins=[{id:'a',code:'A-01',warehouse_id:'w'},{id:'b',code:'A-01',warehouse_id:'other'}];assert.ok(resolveLocation('A-01',bins).error);assert.equal(resolveLocation('a-01',bins,'w').bin.id,'a');assert.ok(resolveLocation('unregistered',bins,'w').error);});
test('starting a count prefills identity and traceability but never recorded quantities',()=>{const row=warehouseRows(fixture())[0],form=countFormForRow(row,{eaches:'',cases:'0',confirmed:false});assert.equal(form.eaches,'');assert.equal(form.cases,'0');assert.equal(form.lot_number,'LOT-1');assert.equal(form.bin_id,'b');assert.equal(form.units_per_case,'12');});
test('manual maps require bounded dimensions and identify their approximate source',()=>{assert.equal(manualArea('Area','w',12,18).source,'manual_layout');for(const width of [0,-1,101,'bad',Infinity])assert.equal(manualArea('Area','w',width,18),null);});
