import {Children,isValidElement,useEffect,useRef,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {auth} from '../../lib/auth.js';
import {staffShortcuts,staffHome,teamForRole,STAFF_TEAMS} from '../../lib/staffWorkspace.js';
import {useWebhookBridge} from '../../lib/webhookBridge.js';
import {WorkspaceIcon} from '../workspace/WorkspaceIcon.jsx';
import '../../styles/staff-workspace.css';

const TOOLS=[
 ['Orders & customers',[['Quotes','/admin/quotes','quotes'],['Sourcing','/admin/sourcing','sourcing'],['Customers','/admin/customers','customers'],['CRM','/admin/crm','crm'],['HubSpot','/admin/crm/hubspot','hubspot'],['Sales reps','/admin/reps','reps'],['Purchase orders','/admin/purchase-orders','purchase-orders']]],
 ['Warehouse & buying',[['Receive a delivery','/admin/inventory/receive','receiving'],['Inventory','/admin/inventory','inventory'],['Pick & ship','/admin/fulfillment','fulfillment'],['Checkout reviews','/admin/packing','packing'],['Stock counts','/admin/inventory/count','count'],['Lots & recall','/admin/inventory/lots','lots'],['Transfers','/admin/inventory/transfers','transfers'],['Consignment','/admin/consignment','consignment'],['Barcodes','/admin/inventory/barcodes','barcodes'],['Replenishment','/admin/replenishment','replenish'],['Vendors','/admin/vendors','vendors']]],
 ['Manage Unite',[['Refund approvals','/admin/refund-reviews','refund-reviews'],['Needs attention','/admin/desk','desk'],['Document review','/admin/documents','documents'],['Products','/admin/products','products'],['Morning brief','/admin/digest','digest'],['Analytics','/admin/analytics','analytics'],['Team & permissions','/admin/team','team'],['Integrations','/admin/integrations','integrations'],['Website content','/admin/cms','cms'],['Compliance','/admin/compliance','compliance'],['UDI / GUDID','/admin/udi','udi'],['Discovery','/admin/discovery','discovery'],['Webhooks','/admin/webhooks','webhooks'],['Shopify history','/admin/shopify-history','shopify-history'],['Launch preparation','/admin/launch','launch'],['Testing & feedback','/admin/testing','testing'],['Settings','/admin/settings','settings']]],
];
const iconFor=id=>({work:'grid',orders:'box',customers:'people',inquiries:'inbox',quotes:'list',finance:'money',fulfillment:'box',receiving:'box',rep:'people','refund-reviews':'money','new-quote':'list'}[id]||'list');
export function AdminShell({active,children,unsavedChanges=false}){
 const session=auth.use(),location=useLocation(),navigate=useNavigate();
 const [open,setOpen]=useState(false),[error,setError]=useState(''),[switching,setSwitching]=useState(false),[toolSearch,setToolSearch]=useState('');
 const drawer=useRef(null),menuButton=useRef(null);
 useWebhookBridge(session?.role==='admin');
 const nav=staffShortcuts(session?.role,{inquiries:String(session?.email||'').toLowerCase()==='jacobe@unitemedical.net'});
 const matchingTools=TOOLS.map(([name,links])=>[name,links.filter(([label])=>label.toLowerCase().includes(toolSearch.toLowerCase().trim()))]).filter(([,links])=>links.length);
 const pageLabel=active==='work'||active==='overview'?'Today':nav.find(n=>n.id===active)?.label||TOOLS.flatMap(([,links])=>links).find(([,path,id])=>id===active||path===location.pathname)?.[0]||'Operations';
 const isActive=(id,path)=>active===id||location.pathname===path||(id==='work'&&location.pathname==='/admin');
 useEffect(()=>{if(!open)return;const previous=document.activeElement;drawer.current?.querySelector('button')?.focus();const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';function key(e){if(e.key==='Escape')setOpen(false);if(e.key==='Tab'){const els=[...drawer.current.querySelectorAll('a,button,input,select,summary')].filter(el=>el.getClientRects().length);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0]?.focus();}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener('keydown',key);previous?.focus();};},[open]);
 async function switchRole(role){if(unsavedChanges){setError('Save or discard your changes before changing roles.');return;}setSwitching(true);setError('');try{const next=await auth.switchRole(role);setOpen(false);navigate(staffHome(next.role));}catch(e){setError(e.message);}finally{setSwitching(false);}}
 useEffect(()=>{if(!unsavedChanges)return;const guard=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[unsavedChanges]);
 function guardNavigation(event){const link=event.target.closest('a[href]');if(unsavedChanges&&link&&!link.getAttribute('href').startsWith('#')){event.preventDefault();event.stopPropagation();setError('Save or discard your changes before leaving this page.');}}
 const visibleError=error.startsWith('Save or discard')&&!unsavedChanges?'':error;
 const go=()=>setOpen(false);
 const hasMain=Children.toArray(children).some(child=>isValidElement(child)&&child.type==='main');
 const sidebar=<>
  <Link to="/work" className="uw-brand" onClick={go}><img src="/brand/unite-medical-logo.png" alt="Unite Medical" onError={e=>{e.currentTarget.style.display='none';}}/><span className="uw-brand-caption">TEAM WORKSPACE</span></Link>
  <div className="uw-sidebar-scroll"><div className="uw-sidebar-label">YOUR WORKDAY</div>
  <nav aria-label="Staff navigation">{nav.map(n=><Link className={`uw-nav-link ${isActive(n.id,n.path)?'is-active':''}`} key={n.id} to={n.path} onClick={go} aria-current={isActive(n.id,n.path)?'page':undefined}><WorkspaceIcon name={iconFor(n.id)} size={18}/>{n.label}</Link>)}</nav>
  {session?.role==='admin'&&<div className="uw-more-tools"><span className="uw-sidebar-label">EXPLORE</span><label className="uw-tool-search"><WorkspaceIcon name="search" size={16}/><input aria-label="Find a workspace tool" type="search" placeholder="Find a tool…" value={toolSearch} onChange={e=>setToolSearch(e.target.value)}/></label>{!matchingTools.length&&<p className="uw-tool-empty">No tools match your search.</p>}{matchingTools.map(([name,links])=><details key={name} open={Boolean(toolSearch)||links.some(([,path,id])=>isActive(id,path))||undefined}><summary>{name}<WorkspaceIcon name="chevron" size={14}/></summary>{links.map(([label,path,id])=><Link key={id} to={path} onClick={go} className={`uw-tool-link ${isActive(id,path)?'is-active':''}`} aria-current={isActive(id,path)?'page':undefined}>{label}</Link>)}</details>)}</div>}
  </div><div className="uw-sidebar-bottom"><div className="uw-person"><span className="uw-avatar">{(session?.name||session?.email||'U').slice(0,1).toUpperCase()}</span><div><strong>{session?.name||'Unite team'}</strong><span>{session?.role==='admin'?'Administrator':STAFF_TEAMS[teamForRole(session?.role)]?.label}</span></div></div>
  {session?.roles?.length>1&&<label className="uw-role-label">Working role<select value={session.role} disabled={switching} onChange={e=>switchRole(e.target.value)}>{session.roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></label>}
  <div className="uw-account-links"><Link to="/">View website ↗</Link><button onClick={async()=>{if(unsavedChanges){setError('Save or discard your changes before signing out.');return;}await auth.logout();navigate('/login');}}>Sign out</button></div></div>
 </>;
 return <div className="uw-shell" onClickCapture={guardNavigation} onChangeCapture={()=>{if(error.startsWith('Save or discard'))setError('');}}><aside className="uw-sidebar" aria-label="Workspace navigation">{sidebar}</aside><div className="uw-main"><header className="uw-topbar"><div className="uw-breadcrumb"><button ref={menuButton} className="uw-menu-button" onClick={()=>setOpen(true)} aria-label="Open workspace menu" aria-expanded={open}><WorkspaceIcon name="menu"/></button><span>Unite Medical</span><span>/</span><strong>{pageLabel}</strong></div><div className="uw-environment"><span/>{import.meta.env.DEV?'Local preview':import.meta.env.VITE_UNITE_ENVIRONMENT==='staging'?'Staging workspace':'Team workspace'}</div></header><div className="uw-content">{visibleError&&<p role="alert" className="uw-error" style={{margin:20}}>{visibleError}</p>}{hasMain?children:<main id="main">{children}</main>}</div></div>
 {open&&<div className="uw-mobile-layer"><div className="uw-backdrop" onClick={()=>setOpen(false)}/><aside ref={drawer} className="uw-mobile-sidebar" role="dialog" aria-modal="true" aria-label="Workspace navigation"><button className="uw-close-menu" onClick={()=>setOpen(false)} aria-label="Close workspace menu"><WorkspaceIcon name="close"/></button>{sidebar}</aside></div>}</div>;
}
