import {trackFunnel} from '../lib/funnelTelemetry.js';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Nav } from '../components/layout/Nav.jsx';
import { workspaceRequest } from '../lib/workspaceRequest.js';
import { useSEO } from '../lib/seo.js';
import '../styles/workspace.css';
export function AccountDocuments(){
 const [file,setFile]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState(null);const [documents,setDocuments]=useState(null);
 useSEO({title:'Tax documents',noindex:true});
 useEffect(()=>{let active=true;workspaceRequest('/api/account/tax-certificates').then(r=>{if(active)setDocuments(r.documents);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function upload(event){event.preventDefault();if(!file||busy)return;setBusy(true);setError('');setResult(null);try{if(file.size>4*1024*1024)throw new Error('Choose a file smaller than 4 MB.');const type=file.type||({'pdf':'application/pdf','png':'image/png','jpg':'image/jpeg','jpeg':'image/jpeg'}[file.name.split('.').pop().toLowerCase()]);if(!type)throw new Error('Choose a PDF, PNG or JPEG file.');const r=await workspaceRequest('/api/account/tax-certificates',{method:'POST',headers:{'Content-Type':type},body:file});trackFunnel('certificate_uploaded');setResult(r);setFile(null);event.target.reset();setDocuments(null);try{const fresh=await workspaceRequest('/api/account/tax-certificates');setDocuments(fresh.documents);}catch{setError('Upload saved. The document list could not refresh. Reload to check its status.');}}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Nav/><main id="main" className="um-workspace" style={{maxWidth:800}}><Link to="/dashboard">← Your account</Link><header className="ws-header" style={{marginTop:24}}><div><h1>Tax documents</h1><p>Upload your exemption certificate for review.</p></div></header><section className="ws-card"><h2>Add a certificate</h2><form className="ws-stack" onSubmit={upload}><label>PDF, PNG or JPEG · up to 4 MB<input type="file" accept=".pdf,.png,.jpg,.jpeg" required disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);setResult(null);}}/></label><button className="ws-button primary" disabled={!file||busy}>{busy?'Uploading…':'Upload certificate'}</button></form>{error&&<p className="ws-error" role="alert">{error}</p>}{result&&<p className="ws-note" role="status">Your certificate was received and is awaiting review.</p>}<p style={{marginTop:20}}>A missing certificate does not prevent checkout or change an existing tax exemption. Account approval and pricing requirements still apply.</p></section><section className="ws-card"><h2>Document status</h2>{documents===null?<p>Document status is not loaded.</p>:!documents.length?<p>No certificates have been uploaded.</p>:<ul className="ws-list">{documents.map(d=><li key={d.id} className="ws-row"><div><strong>Exemption certificate</strong><span className="ws-muted">{new Date(d.uploaded_at).toLocaleDateString()}</span></div><span className="ws-pill">{d.review_status==='approved'?'Approved':d.review_status==='rejected'?'Needs a replacement':'Awaiting review'}</span></li>)}</ul>}</section></main></>;
}
