import {useRef} from 'react';
import {Link} from 'react-router-dom';
import {Nav} from '../components/layout/Nav.jsx';
import {HomepageFooter} from '../components/layout/HomepageFooter.jsx';
import {EditorialFilm} from '../components/shared/EditorialFilm.jsx';
import {useEditorialReveal} from '../lib/useEditorialReveal.js';
import {useSEO} from '../lib/seo.js';
import './commerce-public.css';
import './case-study-tjs.css';

const OPERATIONS=[
  ['01','Built around the practice.','A complete branded storefront, a 49-product launch catalog, merchandising and pricing. Recovery products selected for the procedures the group performs.','Storefront / Catalog / Pricing'],
  ['02','Their name. Our manufacturing.','Private-label post-surgical bracing, with the practice’s identity carried through the products, packaging and patient touchpoints.','Private label / Product development'],
  ['03','Connected to recovery.','Care-pathway integration with Force Therapeutics connects the store to the patient’s recovery journey. Reorder flows and store analytics support the practice after launch.','Care pathways / Reorders / Analytics'],
  ['04','Delivered by Unite.','Inventory, warehouse operations and direct-to-patient fulfillment run from our Georgia warehouse. Orders are picked, packed and shipped without the practice handling a box.','Inventory / Pick & pack / Fulfillment'],
];
export function CaseStudyTJS(){
  const page=useRef(null);useEditorialReveal(page);
  useSEO({title:'Total Joint Specialists — a recovery store, fully supported',description:'A branded recovery store for Total Joint Specialists. Unite brings together private-label products, care-pathway integration and direct-to-patient fulfillment.',canonical:'/case-studies/tjs'});
  return <div ref={page} className="uc-page tjs-page"><Nav overlay heroSelector=".ed-film"/><main id="main">
    <EditorialFilm id="tjs-film" eyebrow="UNITE MEDICAL / TOTAL JOINT SPECIALISTS" title={<>Their brand.<br/><em>Every step of recovery.</em></>} description="A patient recovery store with an entire supply operation behind it. Built and run by Unite Medical for Total Joint Specialists." src="/images/program-films/tjs-scroll.mp4" poster="/images/mobile-v1/tjs.webp" alt="Conceptual studio arrangement of an orthopedic recovery kit and shipping materials" action={{href:'#tjs-story',label:'Explore the case study'}} endTitle={<>From the practice.<br/>To the patient’s door.</>} endCopy="The storefront is only the beginning. Products, operations and fulfillment work together behind the scenes."/>
    <section id="tjs-story" className="tjs-results uc-wrap ed-reveal" aria-label="First 90 days results"><div className="tjs-results-label"><p className="uc-eyebrow">TOTAL JOINT SPECIALISTS</p><span>The first 90 days.</span></div><div className="tjs-stat-grid">{[['+43%','Revenue growth','Launch month → month three'],['$19.3K','Revenue','First 90 days'],['49','Products','Live at launch'],['3 / 3','Months of growth','Month over month']].map(([value,label,note])=><div key={value}><strong>{value}</strong><span>{label}</span><small>{note}</small></div>)}</div><p className="tjs-stat-note">Reported launch-period results. Revenue increased from $5,278 in the launch month to $7,547 in month three.</p></section>
    <section className="tjs-intro uc-wrap ed-reveal"><p className="uc-eyebrow">01 / THE OPPORTUNITY</p><div><h2>Keep the connection.<br/><span>Beyond the appointment.</span></h2><p>TJS needed a recovery store that felt like an extension of the practice—without building an internal supply-chain or fulfillment team.</p><p>Unite brought the pieces together: the storefront, the product line, the care pathway and the operation that gets every order to the patient.</p></div></section>
    <section className="tjs-store ed-reveal"><div className="uc-wrap tjs-store-grid"><div><p className="uc-eyebrow">A STORE THAT FEELS LIKE THEM</p><h2>One familiar brand.<br/>A complete experience.</h2><p>A dedicated recovery destination, built around the practice and the products its patients need.</p><a className="uc-text-link" href="https://tjs.unitemedical.net/" target="_blank" rel="noreferrer">Visit the TJS Recovery Store <span aria-hidden="true">↗</span></a></div><figure><div className="tjs-browser-bar"><span aria-hidden="true">● ● ●</span><span>tjs.unitemedical.net</span><span>↗</span></div><a href="https://tjs.unitemedical.net/" target="_blank" rel="noreferrer" aria-label="Open the Total Joint Specialists Recovery Store"><img src="/images/program-films/tjs-storefront.png" alt="The live Total Joint Specialists patient recovery storefront" loading="lazy" width="1124" height="720"/></a><figcaption>The TJS Recovery Store · actual storefront</figcaption></figure></div></section>
    <section className="tjs-operations uc-wrap"><div className="tjs-operations-heading ed-reveal"><p className="uc-eyebrow">02 / BEHIND THE EXPERIENCE</p><h2>One partner.<br/>The whole operation.</h2><p>From the first product decision to the package at the door.</p><Link className="uc-text-link" to="/services/private-label">Explore private label ↗</Link></div><div>{OPERATIONS.map(([number,title,copy,tags])=><article className="ed-reveal" key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p><small>{tags}</small></div></article>)}</div></section>
    <section className="tjs-closing ed-reveal"><div className="uc-wrap"><p className="uc-eyebrow">03 / YOUR NEXT CHAPTER</p><h2>Your practice.<br/><span>Your recovery store.</span></h2><div><p>For orthopedic and surgical groups ready to bring recovery products into their own patient experience. We’ll help you work through the products, brand and operation.</p><Link className="tjs-contact" to="/contact?reason=New%20account">Let’s build your program <span aria-hidden="true">↗</span></Link></div></div></section>
  </main><HomepageFooter/></div>;
}
