/**
 * Resources · HCPCS Level II reference — PRD-29 §6.3 (built real).
 *
 * Runs on the actual CMS HCPCS Level II quarterly dataset
 * (src/data/hcpcs.json, generated by scripts/import_hcpcs.py from the
 * public CMS Alpha-Numeric file — HCPCS Level II is public domain).
 * Real code counts, functional search + family filters, true Unite SKU
 * cross-links (src/data/hcpcsSkuMap.js), a real PDF export built with
 * the in-house PDF writer, and a dynamic CMS-update date read from the
 * dataset itself. No fabricated numbers anywhere on this page.
 *
 * The 1 MB dataset is lazy-loaded on mount so it ships as its own chunk
 * and never burdens the main bundle.
 */

import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { D } from '../tokens.js';
import { Nav } from '../components/layout/Nav.jsx';
import { Footer } from '../components/layout/Footer.jsx';
import { PageHead } from '../components/layout/PageHead.jsx';
import { Grad } from '../components/shared/Grad.jsx';
import { Icon } from '../components/shared/Icon.jsx';
import { useViewport } from '../lib/viewport.js';
import { useSEO } from '../lib/seo.js';
import { skusForCode, skuCountsByCode, productForSku } from '../data/hcpcsSkuMap.js';
import { createPdf, downloadPdf, wrapText } from '../lib/pdf.js';

const PAGE_SIZE = 50;

function exportPdf(rows, { family, query, updated }) {
  const doc = createPdf();
  const margin = 54;
  const colCode = margin;
  const colDesc = margin + 70;
  const descWidth = doc.pageWidth - margin - colDesc;
  let y = margin;

  const header = () => {
    doc.text(margin, y, 'HCPCS Level II reference', { size: 15, bold: true });
    y += 22;
    const scope = [
      family === 'All' ? 'All families' : `Family ${family}`,
      query ? `search “${query}”` : null,
      `${rows.length.toLocaleString()} codes`,
    ].filter(Boolean).join(' · ');
    doc.text(margin, y, scope, { size: 9, color: [0.35, 0.35, 0.35] });
    y += 14;
    doc.text(margin, y, `Source: CMS HCPCS Level II Alpha-Numeric File — ${updated} update. Compiled by Unite Medical (unitemedical.net/resources).`, { size: 8, color: [0.45, 0.45, 0.45], maxWidth: doc.pageWidth - margin * 2 });
    y += 24;
    doc.line(margin, y, doc.pageWidth - margin, y, { color: [0.8, 0.8, 0.8] });
    y += 10;
  };

  header();
  for (const [code, desc] of rows) {
    const lines = wrapText(desc, descWidth, 9);
    const rowH = Math.max(1, lines.length) * 12 + 6;
    if (y + rowH > doc.pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(colCode, y, code, { size: 9, bold: true, color: [0.369, 0.161, 0.388] }); // brand plum #1d5c4d
    doc.text(colDesc, y, desc, { size: 9, maxWidth: descWidth, lineHeight: 12 });
    y += rowH;
  }
  downloadPdf(doc.toBlob(), `hcpcs-${family === 'All' ? 'all' : family}-${updated.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}

export function Resources() {
  const { isMobile } = useViewport();
  const padX = isMobile ? 20 : 40;
  const [data, setData] = useState(null);
  const [loadError, setLoadError] = useState(false);
  const [q, setQ] = useState('');
  const [family, setFamily] = useState('All');
  const [limit, setLimit] = useState(PAGE_SIZE);
  const [expanded, setExpanded] = useState(null); // code whose SKU links are open

  useEffect(() => {
    let alive = true;
    import('../data/hcpcs.json')
      .then((m) => { if (alive) setData(m.default || m); })
      .catch(() => { if (alive) setLoadError(true); });
    return () => { alive = false; };
  }, []);

  const updated = data?.updated || '';
  const total = data?.codes?.length || 0;

  useSEO({
    title: 'HCPCS Level II code reference for medical supplies',
    description: `Free searchable HCPCS Level II reference — every CMS procedure and supply code with full descriptions, cross-linked to Unite Medical SKUs.${updated ? ` Current through the ${updated} CMS update.` : ''}`,
    canonical: '/resources',
  });

  const skuCounts = useMemo(() => skuCountsByCode(), []);

  const families = useMemo(() => {
    if (!data) return [];
    const counts = {};
    for (const [code] of data.codes) counts[code[0]] = (counts[code[0]] || 0) + 1;
    return Object.keys(counts).sort().map((f) => [f, data.families?.[f] || `${f}-codes`, counts[f]]);
  }, [data]);

  const filtered = useMemo(() => {
    if (!data) return [];
    const query = q.trim().toLowerCase();
    return data.codes.filter(([code, desc]) =>
      (family === 'All' || code[0] === family) &&
      (!query || code.toLowerCase().includes(query) || desc.toLowerCase().includes(query)));
  }, [data, q, family]);

  // Reset pagination + expanded row whenever the filter scope changes.
  const setQuery = (value) => { setQ(value); setLimit(PAGE_SIZE); setExpanded(null); };
  const pickFamily = (f) => { setFamily(f); setLimit(PAGE_SIZE); setExpanded(null); };

  const visible = filtered.slice(0, limit);

  return (
    <div style={{ background: D.paper, fontFamily: D.sans, color: D.ink, minHeight: '100vh' }}>
      <Nav />
      <PageHead eyebrow="RESOURCES · HCPCS REFERENCE"
        title={<>Every code, <Grad>every SKU</Grad>.</>}
        sub={data
          ? `All ${total.toLocaleString()} HCPCS Level II codes from the official CMS dataset, cross-linked to our catalog. Current through the ${updated} CMS update.`
          : 'The full HCPCS Level II code set from the official CMS dataset, cross-linked to our catalog.'} />
      <div style={{ maxWidth: 1360, margin: '0 auto', padding: `24px ${padX}px ${isMobile ? 56 : 80}px` }}>
        <div style={{ display: 'flex', gap: 10, marginBottom: 20, flexWrap: 'wrap' }}>
          <div style={{ flex: '1 1 240px', padding: '4px 18px', background: D.card, borderRadius: 4, border: `1px solid ${D.line}`, display: 'flex', alignItems: 'center', gap: 10 }}>
            <Icon.search />
            <input
              value={q}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={data ? `Search ${total.toLocaleString()} codes or descriptions` : 'Loading code set…'}
              aria-label="Search HCPCS codes"
              disabled={!data}
              style={{ border: 'none', outline: 'none', background: 'transparent', flex: 1, fontSize: isMobile ? 13 : 14, fontFamily: D.sans, color: D.ink, padding: '10px 0' }}
            />
          </div>
          <button
            onClick={() => exportPdf(filtered, { family, query: q.trim(), updated })}
            disabled={!data || filtered.length === 0}
            style={{ background: D.plum, color: D.paper, border: 'none', padding: isMobile ? '12px 22px' : '0 24px', borderRadius: 4, cursor: data && filtered.length ? 'pointer' : 'default', fontSize: 14, fontWeight: 500, opacity: data && filtered.length ? 1 : 0.4 }}>
            Download PDF{data && filtered.length ? ` (${filtered.length.toLocaleString()} codes)` : ''}
          </button>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '260px 1fr', gap: isMobile ? 18 : 32 }}>
          <div>
            <div style={{ fontFamily: D.mono, fontSize: 10, letterSpacing: 1, color: D.ink3, marginBottom: 12 }}>FAMILY</div>
            <div className={isMobile ? 'um-scroll-x' : ''} style={isMobile ? { display: 'flex', gap: 6 } : undefined}>
              {[['All', 'All families', total], ...families].map(([f, label, count]) => (
                <div key={f} role="button" tabIndex={0} onClick={() => pickFamily(f)} onKeyDown={(e) => e.key === 'Enter' && pickFamily(f)}
                  style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 14px', borderRadius: isMobile ? 999 : 8, background: family === f ? D.plum : (isMobile ? D.card : 'transparent'), color: family === f ? D.paper : D.ink2, fontSize: 13, cursor: 'pointer', marginBottom: isMobile ? 0 : 2, gap: 8, border: isMobile ? `1px solid ${family === f ? D.plum : D.line}` : 'none', whiteSpace: 'nowrap', flexShrink: 0 }}>
                  <span>{label}</span><span style={{ fontFamily: D.mono, fontSize: 11, opacity: .7 }}>{count.toLocaleString()}</span>
                </div>
              ))}
            </div>
            {data && (
              <div style={{ marginTop: 16, fontSize: 11, color: D.ink3, lineHeight: 1.6, display: isMobile ? 'none' : 'block' }}>
                Source: {data.source}, {updated} update. HCPCS Level II codes are maintained by CMS and are public domain.
              </div>
            )}
          </div>
          <div style={{ background: D.card, borderRadius: 14, border: `1px solid ${D.line}`, overflow: 'hidden' }}>
            {!data && !loadError && (
              <div style={{ padding: 40, textAlign: 'center', color: D.ink3, fontSize: 13 }}>Loading the CMS code set…</div>
            )}
            {loadError && (
              <div style={{ padding: 40, textAlign: 'center', color: D.ink3, fontSize: 13 }}>Couldn't load the code set — refresh to try again.</div>
            )}
            {data && (
              <>
                <div className={isMobile ? 'um-scroll-x' : ''}>
                  <table style={{ width: '100%', minWidth: isMobile ? 600 : 'auto', borderCollapse: 'collapse', fontSize: 13 }}>
                    <thead>
                      <tr style={{ background: D.paperAlt, fontFamily: D.mono, fontSize: 10, letterSpacing: 1, color: D.ink3 }}>
                        {['CODE', 'DESCRIPTION', 'UNITE SKUS'].map((h) => <th key={h} style={{ padding: '12px 18px', textAlign: 'left' }}>{h}</th>)}
                      </tr>
                    </thead>
                    <tbody>
                      {visible.map(([code, desc]) => {
                        const count = skuCounts[code] || 0;
                        const open = expanded === code;
                        return [
                          <tr key={code} style={{ borderTop: `1px solid ${D.line}` }}>
                            <td style={{ padding: '14px 18px', fontFamily: D.mono, color: D.plum, fontWeight: 600, whiteSpace: 'nowrap', verticalAlign: 'top' }}>{code}</td>
                            <td style={{ padding: '14px 18px', lineHeight: 1.5 }}>{desc}</td>
                            <td style={{ padding: '14px 18px', fontFamily: D.mono, fontSize: 11, whiteSpace: 'nowrap', verticalAlign: 'top' }}>
                              {count > 0 ? (
                                <span role="button" tabIndex={0} onClick={() => setExpanded(open ? null : code)} onKeyDown={(e) => e.key === 'Enter' && setExpanded(open ? null : code)}
                                  style={{ color: D.plum, letterSpacing: 0.8, cursor: 'pointer' }}>
                                  {open ? 'HIDE' : 'VIEW'} {count} SKU{count === 1 ? '' : 'S'} {open ? '↑' : '→'}
                                </span>
                              ) : (
                                <span style={{ color: D.ink3 }}>—</span>
                              )}
                            </td>
                          </tr>,
                          open && (
                            <tr key={`${code}-skus`}>
                              <td colSpan={3} style={{ padding: '0 18px 16px', background: D.paperAlt }}>
                                {skusForCode(code).map((sku) => {
                                  const p = productForSku(sku);
                                  return (
                                    <Link key={sku} to={`/products/${encodeURIComponent(sku)}`} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, margin: '10px 10px 0 0', padding: '8px 14px', borderRadius: 4, border: `1px solid ${D.line}`, background: D.paper, color: D.ink, fontSize: 12, textDecoration: 'none' }}>
                                      <span style={{ fontFamily: D.mono, color: D.plum, fontWeight: 600 }}>{sku}</span>
                                      <span>{p?.name}</span>
                                      {p?.pdac_approved && <span style={{ fontFamily: D.mono, fontSize: 9, letterSpacing: 1, color: '#3b8760' }}>PDAC</span>}
                                    </Link>
                                  );
                                })}
                              </td>
                            </tr>
                          ),
                        ];
                      })}
                      {filtered.length === 0 && (
                        <tr><td colSpan={3} style={{ padding: 32, textAlign: 'center', color: D.ink3 }}>No codes match — try a different search or family.</td></tr>
                      )}
                    </tbody>
                  </table>
                </div>
                {filtered.length > limit && (
                  <div style={{ padding: 16, textAlign: 'center', borderTop: `1px solid ${D.line}` }}>
                    <button onClick={() => setLimit(limit + PAGE_SIZE * 4)} style={{ background: 'transparent', color: D.plum, border: `1px solid ${D.plum}`, padding: '10px 24px', borderRadius: 4, cursor: 'pointer', fontSize: 13, fontWeight: 600 }}>
                      Show more ({(filtered.length - limit).toLocaleString()} remaining)
                    </button>
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
