import { useRef, useState } from 'react';
import { Nav } from '../components/layout/Nav.jsx';
import { Footer } from '../components/layout/Footer.jsx';
import { useSEO } from '../lib/seo.js';
import './regenicool.css';
const emptyLine = () => ({ raw_description:'', product_identifier:'', category:'', qty:'', condition:'new_in_box', expiry_date:'', lot_number:'', provenance:'', evidence_url:'', target_usd_per_unit:'' });
export function Surplus() {
  useSEO({title:'Surplus marketplace pilot',description:'Private intake for verified US businesses with unopened, unexpired medical supplies, including PPE. Unite connects buyers and sellers.',canonical:'/surplus'});
  const [lines,setLines] = useState([emptyLine()]);
  const [state,setState] = useState({busy:false,error:'',id:null});
  const key=useRef(null);
  function update(i,k,v){setLines(rows=>rows.map((r,j)=>j===i?{...r,[k]:v}:r));}
  async function submit(e){e.preventDefault();if(state.busy)return;key.current ||= crypto.randomUUID();const values=Object.fromEntries(new FormData(e.currentTarget));setState({busy:true,error:'',id:null});try{const response=await fetch('/api/public/inquiry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,kind:'surplus',idempotency_key:key.current,us_business:values.us_business==='on',eligibility_confirmed:values.eligibility_confirmed==='on',lines})});const body=await response.json().catch(() => ({}));if(!response.ok)throw new Error(body.error==='unexpired_goods_only'?'Only unexpired goods are eligible. Check each lot’s expiration date.':'Could not save your submission. Check the details and try again.');setState({busy:false,error:'',id:body.id});}catch(err){setState({busy:false,error:err.message,id:null});}}
  return <><Nav/><main id="main" className="rc-page"><section className="rc-container rc-section"><p className="rc-eyebrow">SURPLUS MARKETPLACE · INTAKE PILOT</p><h1>Make a connection.<br/>Move eligible surplus.</h1><p className="rc-lead">For verified US businesses selling unopened, unexpired medical supplies, including PPE. Products can be eligible even when they are not in Unite’s catalog.</p><p>Submissions are saved privately for Jacobe’s review. This initial release accepts inquiries only; deal acceptance, fee collection and contact introductions are not enabled.</p><div className="rc-facts" style={{background:'#14271f',padding:28,marginTop:32}}><div><h2>Seller keeps the goods</h2><p>Unite connects buyer and seller without acquiring inventory. Buyers pay sellers directly, outside Unite.</p></div><div><h2>10% connection fee</h2><p>The seller pays 10% of agreed merchandise value, excluding shipping and sales tax. No listing fee or minimum.</p></div><div><h2>Direct fulfillment</h2><p>Buyer and seller agree shipping and arrange all logistics directly. The seller provides tracking.</p></div></div></section>
    <section className="rc-container" style={{paddingBottom:80,maxWidth:1000}}>{state.id?<div role="status" className="rc-confirmation"><h2>Submission saved for review.</h2><p>Jacobe will review eligibility and any missing evidence. This is not a published listing or an accepted deal.</p><p>Reference: {state.id}</p></div>:<form className="rc-form" onSubmit={submit}><h2>Submit inventory for review.</h2><div className="rc-form-grid">{[['name','Your name','text'],['company','Business name','text'],['email','Work email','email'],['pickup_location','Inventory location (city, state)','text']].map(([name,label,type])=><label key={name}>{label}<input name={name} type={type} required maxLength={254}/></label>)}</div><label style={{display:'flex',alignItems:'center'}}><input name="us_business" type="checkbox" required style={{width:20}}/> I represent a US business. Business verification is required before participation.</label>
      {lines.map((line,i)=><fieldset key={i} style={{border:'1px solid #bac6be',padding:24}}><legend>Lot {i+1}</legend><div className="rc-form-grid">{[['raw_description','Product name / description','text',true],['product_identifier','Manufacturer and product ID / SKU / GTIN','text',true],['category','Category (for example, PPE gowns)','text',true],['qty','Quantity','number',true],['lot_number','Lot number, where applicable','text',false],['expiry_date','Expiration date, where applicable','date',false],['evidence_url','Link to photos and lot / expiration evidence','url',false],['target_usd_per_unit','Target price per unit (optional)','number',false]].map(([field,label,type,required])=><label key={field}>{label}<input type={type} required={required} value={line[field]} onChange={e=>update(i,field,e.target.value)} min={type==='number'?field==='qty'?1:0.01:undefined} step={field==='target_usd_per_unit'?'0.01':undefined} maxLength={1000}/></label>)}</div><label style={{marginTop:18}}>Provenance and storage history<textarea required rows="2" value={line.provenance} onChange={e=>update(i,'provenance',e.target.value)} maxLength={4000}/></label><p className="rc-caption">Photos, condition, identifiers, provenance, quantity and applicable lot/expiration evidence will be reviewed before eligibility is confirmed. If you do not have an evidence link, Jacobe will coordinate missing evidence.</p>{lines.length>1&&<button type="button" className="rc-button rc-secondary" onClick={()=>setLines(rows=>rows.filter((_,j)=>i!==j))}>Remove lot</button>}</fieldset>)}<button type="button" className="rc-button rc-secondary" onClick={()=>setLines([...lines,emptyLine()])} disabled={lines.length>=200}>Add another lot</button><label style={{display:'flex',alignItems:'center'}}><input type="checkbox" name="eligibility_confirmed" required style={{width:20}}/> All goods are unopened and unexpired. I understand Unite does not provide logistics or buy this inventory.</label><label>Additional information<textarea name="message" rows="3" maxLength={4000}/></label><input className="rc-honeypot" name="website_confirm" tabIndex="-1" autoComplete="off" aria-hidden="true"/>{state.error&&<p className="rc-error" role="alert">{state.error}</p>}<button className="rc-button" disabled={state.busy}>{state.busy?'Saving…':'Submit for private review'}</button></form>}</section>
    <section className="rc-container rc-section" style={{borderTop:'1px solid #dfe5e0'}}><h2>How a future connection works.</h2><p>Both parties must agree to the same deal. Required contracting identities and disclosures are provided before binding commitment. Exact fee dollars are disclosed before acceptance. Unite’s separate fee is collected through Stripe and payment confirmed before the introduction is completed or remaining contact details released. Merchandise payment stays between buyer and seller.</p><p>Unite does not quote freight, book carriers, issue labels, arrange pickup or packing, store or transport goods, or arrange returns. Jacobe may follow up and record status. Participation does not remove applicable responsibilities or obligations.</p><h3>Fee and refund rules</h3><p>A $5,000 merchandise deal carries a $500 fee. If the buyer never pays the seller or the seller cannot supply, the fee is refundable under the agreed rule. An eligible $1,000 partial merchandise refund produces a $100 fee reversal.</p><p>If the buyer has paid, both parties agreed and the introduction is complete, Unite retains its fee when both parties subsequently choose to cancel. Ashley reviews eligible refunds and Damon gives final approval. Payment disputes and charge errors are handled separately. Treatment of an uncompleted introduction remains to be confirmed before deal processing is enabled.</p></section>
  </main><Footer/></>;
}
