import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Nav} from '../components/layout/Nav.jsx';
import {HomepageFooter} from '../components/layout/HomepageFooter.jsx';
import {CommerceHero} from '../components/shared/CommerceHero.jsx';
import {WELL_CONTRACT,WELL_PUBLIC_PRODUCTS,WELL_REQUEST_STATES} from '../data/welllinkPublic.js';
import {PRODUCT_IMG} from '../lib/imageMap.js';
import {auth} from '../lib/auth.js';
import {useSEO} from '../lib/seo.js';
import './commerce-public.css';
import './commerce-editorial.css';
import './welllink-public.css';
const endpoint='/api/welllink/requests';
const requestKey=()=>crypto.randomUUID();
function referralFor(params) {
  let saved={};try{saved=JSON.parse(sessionStorage.getItem('unite.welllink.referral')||'{}');}catch{/* Storage is optional. */}
  const incoming=Object.fromEntries(['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].map(k=>[k,(params.get(k)||'').slice(0,200)]));
  const latest=Object.values(incoming).some(Boolean)?incoming:(saved.latest||saved);
  const current={first:saved.first||latest,latest};
  try{sessionStorage.setItem('unite.welllink.referral',JSON.stringify(current));}catch{/* Submission still works. */}
  return current;
}
function MemberStatus({session}) {
  const [result,setResult]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetch(endpoint,{credentials:'include',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(setResult).catch(()=>{if(!controller.signal.aborted)setError('We couldn’t load your requests. Try again, or contact Damon.');});return()=>controller.abort();},[session.user_id,retry]);
  return <section className="wm-status uc-wrap" id="member-status"><p className="uc-eyebrow">YOUR WELLLINK REQUESTS</p><h2>Your facility. Your next step.</h2><p>Signed in as {session.email}. Signing in does not activate contract pricing. Our team verifies your facility and accepted participation before preparing a contract quote.</p>{error?<><p role="alert" className="uq-error">{error}</p><button className="uc-text-button" onClick={()=>{setError('');setRetry(n=>n+1);}}>Try again</button></>:!result?<p role="status">Loading your requests…</p>:result.requests.length?<ul>{result.requests.map(r=><li key={r.id}><div><strong>{r.facility}</strong><small>{r.kind==='sample'?'Sample box':r.kind==='quote'?'Contract quote':'Facility access'} · {new Date(r.created_at).toLocaleDateString()}</small></div><span>{WELL_REQUEST_STATES[r.status]||'Under review'}</span></li>)}</ul>:<p>No requests are linked to this email yet. Use the form below with your account email; you do not need another account.</p>}</section>;
}
export function WellLink() {
  const [params]=useSearchParams(),session=auth.use();
  const [kind,setKind]=useState('access'),[skus,setSkus]=useState([]),[key,setKey]=useState(requestKey),[referral]=useState(()=>referralFor(params));
  const [form,setForm]=useState({name:session?.name||'',title:'',email:session?.email||'',organization:'',facility:'',address:'',city:'',state:'',zip:'',phone:'',institution_id:'',account_number:'',participation_status:'not_started',quantity:'1',carrier:'quote_shipping',carrier_account:'',carrier_authorization:false,contact_permission:false,marketing_opt_in:false});
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(null);
  useSEO({title:'WellLink member program',description:'Explore six Luer Lock syringe sizes through WellLink contract CC-NS-0052. Request facility access, a contract quote, or a sample box from Unite Medical.',canonical:'/welllink'});
  function update(field,value){setForm(f=>({...f,[field]:value}));setError('');setKey(requestKey());}
  function choose(next,sku){setKind(next);setSkus(sku?[sku]:[]);setDone(null);setError('');setKey(requestKey());requestAnimationFrame(()=>document.getElementById('welllink-request')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'}));}
  async function submit(e) {
    e.preventDefault();if(busy)return;
    if(kind!=='access'&&!skus.length){setError('Select at least one syringe size.');return;}
    setBusy(true);setError('');
    try{const response=await fetch(endpoint,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,kind,skus,referral:referral.latest,first_referral:referral.first,idempotency_key:key})});const body=await response.json();if(!response.ok){const message={too_many_requests:'You’ve sent several requests. Please try later or contact Damon.',whole_cases_required:'Enter a whole number of cases, minimum one.',invalid_details:'Check your facility details, email and five-digit ZIP.',carrier_authorization_required:'Authorize use of your carrier account, or ask us to quote shipping.',authentication_required:'Your sign-in has expired. Sign in again, then retry.',request_conflict:'This request changed. Edit a field, then send it again.'}[body.error];throw new Error(message||'We couldn’t save your request. Your details are still here; please try again.');}setDone(body.request);setForm(f=>({...f,carrier_account:''}));}catch(e){setError(e.message||'We couldn’t save your request. Please try again.');}finally{setBusy(false);}
  }
  return <div className="uc-page wm-page"><Nav overlay heroSelector=".umc-masthead"/><main id="main">
    <CommerceHero eyebrow={`WELLLINK MEMBER PROGRAM / ${WELL_CONTRACT}`} title="Standard Luer Lock syringes." accent="For WellLink members." description="Access Unite Medical® contract pricing on six syringe sizes without needles. Start with your facility, and we’ll help you through participation." image="/images/homepage-2026/everyday-supplies-1200.webp" imageAlt="Medical supplies prepared for a care team" action={{to:'#welllink-request',label:'Request WellLink access'}} index="04"/>
    <div className="uc-wrap wm-intro"><div><p className="uc-eyebrow">A FOCUSED CONTRACT. A PERSONAL CONNECTION.</p><h2>Six sizes.<br/>One place to start.</h2></div><div><p>From 1 mL to 50/60 mL, explore the awarded Luer Lock syringe line under contract {WELL_CONTRACT}. Our team will verify your facility’s membership and coordinate the required Contract Participation Form.</p><p>Contract quotes are currently prepared by our team after verification and accepted participation. Online contract pricing and ordering are not yet activated.</p><div className="wm-inline-actions"><Link className="uc-text-link" to={session?'#member-status':'/login?next=%2Fwelllink%3Fview%3Dstatus'}>{session?'View my request status':'Member sign in'} ↗</Link><button className="uc-text-button" onClick={()=>choose('sample')}>Request a sample box ↗</button></div></div></div>
    {session&&<MemberStatus key={`${session.user_id}:${done?.id||''}`} session={session}/>}
    <section className="uc-wrap wm-products" aria-labelledby="wm-products-title"><div className="wm-section-heading"><div><p className="uc-eyebrow">01 / THE AWARDED LINE</p><h2 id="wm-products-title">The right size for your team.</h2></div><p>Luer Lock syringes without needles.<br/>Contract orders are full cases, minimum one case.</p></div><div className="wm-product-grid">{WELL_PUBLIC_PRODUCTS.map(p=><article key={p.sku}><div className="wm-product-image"><span>{p.size} <small>mL</small></span><img src={PRODUCT_IMG[p.sampleSku]} alt={`${p.size} mL Luer Lock syringe without needle`} loading="lazy"/></div><div className="wm-product-info"><h3>{p.size} mL Luer Lock syringe</h3><p>{p.eachPerCase.toLocaleString()} syringes per case</p>{p.size==='1'&&<p className="wm-reference">Needles and accessories shown are not included.</p>}<small>{p.sku}</small>{p.size==='5'&&<p className="wm-reference">Purchasing reference: BD 309646.<br/>Subject to your facility’s clinical evaluation.</p>}<button className="uc-product-action" onClick={()=>choose('quote',p.sku)}>Request contract pricing <span>↗</span></button><button className="uc-text-button" onClick={()=>choose('sample',p.sampleSku)}>Request a sample box ↗</button></div></article>)}</div></section>
    <section className="wm-process"><div className="uc-wrap"><p className="uc-eyebrow">02 / FROM REQUEST TO PARTICIPATION</p><h2>A clear path to your contract.</h2><div>{[['01','Tell us about your facility.','Send your facility details and ship-to address. Already have a Unite account? Use the same email; no duplicate account is needed.'],['02','We verify and coordinate.','Our team checks the current WellLink roster, confirms your authority, and coordinates the required participation form.'],['03','Review your contract quote.','After supplier acceptance and the effective date are confirmed, our team helps you review pricing and place a full-case order.']].map(([n,h,p])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{p}</p></article>)}</div></div></section>
    <section className="uc-wrap wm-terms"><div><p className="uc-eyebrow">03 / BUILT INTO YOUR CONTRACT</p><h2>Know the details.<br/>Plan with confidence.</h2><p>Applies to eligible, participating facilities under {WELL_CONTRACT}. Our team confirms the details with your quote.</p></div><dl>{[['Six awarded sizes','Contract pricing on standard Luer Lock syringes without needles, from 1 mL through 50/60 mL.'],['One-case minimum','Full-case contract orders. Sample product is complimentary; members pay shipping.'],['Shipment within 48 hours','For orders received during normal business hours. This is a shipment timeframe, not a delivery promise. Freight is prepaid and added to the invoice.'],['Net 30 payment terms','A 1% discount when paid within 10 days, under the contract’s payment terms.'],['First-year price protection','Contract limits and advance notice requirements apply to later increases.']].map(([h,p])=><div key={h}><dt>{h}</dt><dd>{p}</dd></div>)}</dl></section>
    <section className="us-request wm-request" id="welllink-request"><div className="uc-wrap us-request-grid"><div><p className="uc-eyebrow">04 / LET’S GET STARTED</p><h2>{kind==='sample'?<>A sample.<br/>A closer look.</>:kind==='quote'?<>Your facility.<br/>Your contract quote.</>:<>Your access.<br/>Our attention.</>}</h2><p>{kind==='sample'?'Sample product is complimentary. You pay shipping. Provide an optional UPS or FedEx account with billing authorization, or ask us to confirm shipping charges before fulfillment.':'Tell us about your facility. We’ll verify membership, coordinate participation, and help with the next step.'}</p><a href="mailto:damon@unitemedical.net">Contact Damon Reed ↗</a><p className="wm-contact-role">Owner & CEO · Unite Medical</p><p className="wm-document-note">Need product specifications or the member overview? Ask Damon for the current approved materials.</p></div><div>
      <div className="wm-request-types" aria-label="Request type">{[['access','Facility access'],['quote','Contract quote'],['sample','Sample box']].map(([value,label])=><button key={value} disabled={busy} aria-pressed={kind===value} onClick={()=>choose(value)}>{label}</button>)}</div>
      {done?<div role="status" className="us-confirmation"><p className="uc-eyebrow">REQUEST RECEIVED</p><h3>Your next step is with us.</h3><p>We received your {kind==='sample'?'sample box request':'facility request'}. Damon’s team will review your details and follow up at {form.email}. Contract access requires facility verification and accepted, effective participation.</p><small>Reference {done.id}</small><Link className="uc-text-link" to="/login?next=%2Fwelllink%3Fview%3Dstatus">Member sign in ↗</Link><button className="uc-text-button" onClick={()=>choose('access')}>Start another request</button></div>:<form className="us-request-form" onSubmit={submit}><fieldset disabled={busy}><legend>{kind==='sample'?'Request a sample box':kind==='quote'?'Request contract pricing':'Request WellLink access'}</legend>
      {kind!=='access'&&<fieldset className="wm-size-options"><legend>{kind==='sample'?'Sample sizes':'Syringe sizes'}</legend>{WELL_PUBLIC_PRODUCTS.map(p=>{const sku=kind==='sample'?p.sampleSku:p.sku;return <label key={sku}><input type="checkbox" checked={skus.includes(sku)} onChange={e=>{setSkus(s=>e.target.checked?[...s,sku]:s.filter(x=>x!==sku));setKey(requestKey());setError('');}}/><span>{p.size} mL<small>{sku}</small></span></label>;})}</fieldset>}
      <div className="us-fields">{[['name','Your name','name',150],['title','Job title','organization-title',150],['email','Work email','email',254],['phone','Phone (optional)','tel',40],['organization','Organization / parent organization','organization',200],['facility','Facility name','off',200],['address','Ship-to street address','street-address',300],['city','City','address-level2',100],['state','State','address-level1',80],['zip','ZIP code','postal-code',10],['institution_id','WellLink institution ID (optional)','off',100],['account_number','Existing Unite account number (optional)','off',100]].map(([field,label,autoComplete,maxLength])=><label key={field} className={['address','organization','facility'].includes(field)?'us-wide':''}>{label}<input required={!['phone','institution_id','account_number'].includes(field)} type={field==='email'?'email':field==='phone'?'tel':'text'} autoComplete={autoComplete} maxLength={maxLength} pattern={field==='zip'?'[0-9]{5}(-[0-9]{4})?':undefined} value={form[field]} onChange={e=>update(field,e.target.value)}/></label>)}
      <label className="us-wide">Participation form status<select value={form.participation_status} onChange={e=>update('participation_status',e.target.value)}><option value="not_started">Not started — please help me</option><option value="submitted">Submitted for review</option><option value="accepted">Previously accepted — please verify</option><option value="unsure">I’m not sure</option></select></label>
      {kind==='quote'&&<label className="us-wide">Cases per selected size<input required type="number" min="1" max="10000" step="1" value={form.quantity} onChange={e=>update('quantity',e.target.value)}/></label>}
      {kind==='sample'&&<><label>Shipping arrangement<select value={form.carrier} onChange={e=>{update('carrier',e.target.value);update('carrier_account','');update('carrier_authorization',false);}}><option value="quote_shipping">Confirm shipping charges with me</option><option value="UPS">My UPS account</option><option value="FedEx">My FedEx account</option></select></label>{form.carrier!=='quote_shipping'&&<label>Carrier account number (optional)<input autoComplete="off" maxLength={50} value={form.carrier_account} onChange={e=>update('carrier_account',e.target.value)}/></label>}</>}
      </div><div className="wm-consents">{kind==='sample'&&form.carrier_account&&<label><input type="checkbox" required checked={form.carrier_authorization} onChange={e=>update('carrier_authorization',e.target.checked)}/><span>I’m authorized to use this carrier account and authorize shipping charges for this sample request.</span></label>}<label><input type="checkbox" required checked={form.contact_permission} onChange={e=>update('contact_permission',e.target.checked)}/><span>I’m authorized to request information for this facility and ask Unite Medical to contact me about this request.</span></label><label><input type="checkbox" checked={form.marketing_opt_in} onChange={e=>update('marketing_opt_in',e.target.checked)}/><span>Send me optional product and program updates. This is separate from my request.</span></label></div>
      {error&&<p role="alert" className="uq-error">{error}</p>}<button className="uc-button" type="submit" disabled={busy}>{busy?'Saving your request…':kind==='sample'?'Send sample request':kind==='quote'?'Request contract pricing':'Request WellLink access'} <span>↗</span></button><p className="uq-note">Submitting a request does not place an order or grant pricing access. <Link to="/privacy">Privacy policy ↗</Link></p></fieldset></form>}
    </div></div></section>
    <section className="uc-wrap wm-help"><p className="uc-eyebrow">A PERSON TO HELP YOU MOVE FORWARD</p><h2>Let’s get your facility connected.</h2><a href="mailto:damon@unitemedical.net" className="uc-text-link">Damon Reed · damon@unitemedical.net ↗</a></section>
  </main><HomepageFooter/></div>;
}
