import {useEffect,useState} from 'react';
import {assistantRequest} from '../../lib/assistantClient.js';
import {WorkspaceIcon} from '../workspace/WorkspaceIcon.jsx';
function group(row){if(row.pinned)return 'Pinned';const days=Math.floor((new Date().setHours(0,0,0,0)-new Date(row.updated_at).setHours(0,0,0,0))/86400000);return days===0?'Today':days===1?'Yesterday':days<7?'Previous 7 days':new Date(row.updated_at).toLocaleDateString('en-US',{month:'long',year:'numeric'});}
export function ChatHistorySidebar({current,onOpen,onNew,refresh,onCollapse,onRenamed}){
 const [q,setQ]=useState(''),[rows,setRows]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[more,setMore]=useState(false),[version,setVersion]=useState(0),[renaming,setRenaming]=useState(''),[name,setName]=useState('');
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{setBusy(true);assistantRequest(null,{action:'history',q}).then(r=>{if(active){setRows(r.history);setMore(r.has_more);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});},180);return()=>{active=false;clearTimeout(timer);};},[q,refresh,version]);
 async function moreRows(){setBusy(true);try{const r=await assistantRequest(null,{action:'history',q,offset:rows.length});setRows(v=>[...v,...r.history]);setMore(r.has_more);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function update(row,action){try{await assistantRequest({action,session_id:row.id,...(action==='rename'?{title:name}:{pinned:!row.pinned})});if(action==='rename'&&row.id===current)onRenamed?.(name);setRenaming('');setVersion(v=>v+1);}catch(e){setError(e.message);}}
 return <aside className="uc-history" aria-label="Conversation history"><header><strong>Your conversations</strong><button aria-label="Hide conversation history" onClick={onCollapse}><WorkspaceIcon name="chevron" size={16}/></button></header><button className="uc-new-chat" onClick={onNew}><span>＋</span> New chat</button><label className="uc-history-search"><WorkspaceIcon name="search" size={16}/><input type="search" aria-label="Search conversations" placeholder="Search conversations" value={q} onChange={e=>setQ(e.target.value)}/></label><div className="uc-history-scroll">{error&&<p className="cw-error" role="alert">{error}</p>}{rows.map((row,index)=><div key={row.id}>{(index===0||group(row)!==group(rows[index-1]))&&<h3>{group(row)}</h3>}<div className={'uc-history-item '+(row.id===current?'selected':'')}>{renaming===row.id?<form onSubmit={e=>{e.preventDefault();update(row,'rename');}}><input aria-label="Conversation name" value={name} autoFocus maxLength={90} onChange={e=>setName(e.target.value)} onKeyDown={e=>{if(e.key==='Escape')setRenaming('');}}/><button type="submit" aria-label="Save conversation name">✓</button></form>:<><button className="uc-history-open" onClick={()=>onOpen(row.id)} aria-current={row.id===current?'page':undefined}><span>{row.title}</span><small>{new Date(row.updated_at).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</small></button><details className="uc-history-menu"><summary aria-label={'Options for '+row.title}>···</summary><div><button onClick={e=>{e.currentTarget.closest('details').open=false;setRenaming(row.id);setName(row.title);}}>Rename</button><button onClick={e=>{e.currentTarget.closest('details').open=false;update(row,'pin');}}>{row.pinned?'Unpin':'Pin conversation'}</button></div></details></>}</div></div>)}{busy&&<p className="uc-history-note">Loading…</p>}{!busy&&!rows.length&&<p className="uc-history-note">{q?'No matching conversations.':'Your conversations will appear here.'}</p>}{more&&<button className="uc-load-more" disabled={busy} onClick={moreRows}>Load older chats</button>}</div><footer><span className="uc-private-dot"/>Private to your account</footer></aside>;
}
