import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {commerceRequest,money,date,label} from '../../lib/commerceClient.js';
export function Badge({children,tone=''}){return <span className={'cw-badge '+tone}>{children}</span>;}
export function Status({value}){return <Badge tone={['paid','fulfilled','complete','active','subscribed','verified'].includes(value)?'good':['unfulfilled','partially_paid','partial','partially_fulfilled','needs_review','held','missing'].includes(value)?'warn':''}>{label(value)}</Badge>;}
export function Card({title,action,children,className=''}){return <section className={'cw-card '+className}>{title&&<header><h2>{title}</h2>{action}</header>}<div className="cw-card-body">{children}</div></section>;}
export function Empty({children}){return <div className="cw-empty">{children}</div>;}
export function Modal({title,onClose,children,wide=false}){const ref=useRef();useEffect(()=>{const last=document.activeElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector('input,select,textarea,button')?.focus();function key(e){if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=[...ref.current.querySelectorAll('button,a,input,textarea,select')].filter(el=>!el.disabled&&el.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old;last?.focus();};},[onClose]);return <div className="cw-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={ref} className={'cw-modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="cw-icon-button" onClick={onClose} aria-label="Close dialog">×</button></header>{children}</section></div>;}
export function EditForm({title,kind,record,fields,onClose,onSaved,initial}){const [values,setValues]=useState(()=>initial||Object.fromEntries(fields.map(f=>[f.key,f.type==='tags'?(record[f.key]||[]).join(', '):record[f.key]??'']))),[error,setError]=useState(''),[saving,setSaving]=useState(false);async function save(e){e.preventDefault();setSaving(true);setError('');try{const patch=Object.fromEntries(fields.map(f=>[f.key,f.type==='tags'?values[f.key].split(',').map(v=>v.trim()).filter(Boolean):f.type==='number'?values[f.key]===''?null:Number(values[f.key]):values[f.key]]));const r=await commerceRequest({},record.id?{action:'save',kind,id:record.id,revision:record.revision,patch}:{action:'create',kind,patch});onSaved(r.data);onClose();}catch(e){setError(e.message);}finally{setSaving(false);}}return <Modal title={title} onClose={onClose}><form onSubmit={save}><div className="cw-form">{fields.map(f=><label key={f.key}>{f.label}{f.type==='textarea'?<textarea rows={5} value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})}/>:f.type==='boolean'?<select value={String(values[f.key])} onChange={e=>setValues({...values,[f.key]:e.target.value==='true'})}><option value="false">No</option><option value="true">Yes</option></select>:f.options?<select value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})}>{f.options.map(o=><option key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?label(o):o.label}</option>)}</select>:<input required={f.required} type={f.type==='number'?'number':f.type==='email'?'email':'text'} step={f.type==='number'?'0.01':undefined} min={f.type==='number'?0:undefined} value={values[f.key]} onChange={e=>setValues({...values,[f.key]:e.target.value})}/ >}{f.hint&&<small>{f.hint}</small>}</label>)}{error&&<p className="cw-error" role="alert">{error}</p>}</div><footer><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save'}</button></footer></form></Modal>;}
export function Address({address}){if(!address?.address1)return <p className="cw-muted">No address recorded</p>;return <address>{[address.recipient,address.company,address.address1,address.address2,[address.city,address.province,address.zip].filter(Boolean).join(' '),address.country,address.phone].filter(Boolean).map((l,i)=><div key={i}>{l}</div>)}</address>;}
export function Timeline({kind,record,onSaved,orders=[]}){const [comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[visible,setVisible]=useState(20);async function post(){setBusy(true);try{const r=await commerceRequest({},{action:'comment',kind,id:record.id,text:comment});onSaved(r.data);setComment('');}catch(e){setError(e.message);}finally{setBusy(false);}}const events=[...(record.events||[]),...orders.map(o=>({id:o.id,at:o.created_at,text:'Order '+o.number+' placed',href:'/admin/orders/'+o.id,detail:money(o.total)})),...(record.created_at?[{id:'created',at:record.created_at,text:kind==='orders'?(record.historical?'Order created in Shopify':'Draft order created'):kind==='customers'?'Customer created':'Record created',detail:record.historical?'Imported history':''}]:[])].sort((a,b)=>(Date.parse(b.at)||0)-(Date.parse(a.at)||0));return <Card title="Timeline"><div className="cw-comment"><textarea aria-label="Timeline comment" placeholder="Leave a comment for your team…" rows={3} value={comment} onChange={e=>setComment(e.target.value)}/><div><small>Only your team can see comments.</small><button className="primary" disabled={!comment.trim()||busy} onClick={post}>{busy?'Posting…':'Post'}</button></div></div>{error&&<p role="alert" className="cw-error">{error}</p>}<div className="cw-timeline">{events.slice(0,visible).map(e=><div key={e.id}><span className="cw-timeline-dot"/><div><small>{date(e.at)}{e.actor?' · '+e.actor:''}</small><p>{e.href?<Link to={e.href}>{e.text}</Link>:e.text}</p>{e.detail&&<small>{e.detail}</small>}</div></div>)}{events.length>visible&&<button onClick={()=>setVisible(n=>n+20)}>Show older activity</button>}{!events.length&&<Empty>No timeline events yet.</Empty>}</div></Card>;}
export function Pager({page,total,onChange,size=50}){return <div className="cw-pager"><span>{total?`${page*size+1}–${Math.min((page+1)*size,total)} of ${total.toLocaleString()}`:'0 results'}</span><div><button disabled={page===0} onClick={()=>onChange(page-1)} aria-label="Previous page">‹</button><button disabled={(page+1)*size>=total} onClick={()=>onChange(page+1)} aria-label="Next page">›</button></div></div>;}
export function LoadingError({loading,error,children}){return error?<div className="cw-error" role="alert">{error}</div>:loading?<div className="cw-loading" role="status">Loading…</div>:children;}
export function EditButton({onClick,label:aria='Edit'}){return <button className="cw-icon-button" onClick={onClick} aria-label={aria} title={aria}>✎</button>;}
