import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Card,Modal,Status} from './CommerceUI.jsx';
import {draftRequest} from '../../lib/adminOrderClient.js';
import {money} from '../../lib/commerceClient.js';
export function OrderWorkflow({order}){
 const [state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false),[version,setVersion]=useState(0),[matching,setMatching]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/admin/order-drafts?id='+encodeURIComponent(order.id),{credentials:'include'}).then(r=>r.json()).then(data=>{if(active){if(data.error)throw new Error(data.error);setState(data);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[order.id,version]);
 async function sync(){setBusy(true);setError('');try{await draftRequest('sync_accounting',{id:order.id});setVersion(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function payment(){setBusy(true);setError('');try{const r=await fetch('/api/admin/order-resume',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_id:order.operational_order_id})});const data=await r.json();if(!r.ok)throw new Error(data.error?.replaceAll('_',' ')||'Payment setup needs attention.');setConfirm(false);setVersion(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const live=state?.operational,accounting=state?.accounting,id=order.operational_order_id;
 return <><Card title="Order workflow" action={<button disabled={busy} onClick={()=>setVersion(v=>v+1)}>Refresh</button>}><div className="co-workflow"><div><strong>1. Order created</strong><p>{order.number} · {money(order.total)}</p><Link to={'/admin/order-operations?order='+id}>Open order operations →</Link></div><div><strong>2. QuickBooks Online</strong><Status value={accounting?.status||'queued'}/>{accounting?.last_error&&<p>{accounting.last_error}</p>}{accounting?.invoice?.url?<a href={accounting.invoice.url} target="_blank" rel="noopener noreferrer">Open QuickBooks invoice →</a>:<div className="cw-actions"><button disabled={busy} onClick={sync}>Retry accounting sync</button><button onClick={()=>setMatching(true)}>Match QuickBooks records</button><Link to="/admin/integrations">Connection settings</Link></div>}</div><div><strong>3. Payment & credit</strong><Status value={live?.payment_status||'unpaid'}/><p>{live?.payment_url?'Payment request is ready.':'Review payment or approved credit before releasing inventory.'}</p><div className="cw-actions"><Link to="/admin/finance">Open Finance →</Link>{live?.payment_url?<a href={live.payment_url} target="_blank" rel="noopener noreferrer">Payment link →</a>:live?.payment_method==='ach'&&<button disabled={busy} onClick={()=>setConfirm(true)}>Send bank-payment invoice</button>}</div></div><div><strong>4. Fulfillment</strong><Status value={live?.status||'payment_pending'}/><p>Payment, stock availability, packaging and carrier checks apply to this same order.</p><Link to={'/admin/fulfillment?order='+id}>Open fulfillment →</Link></div></div>{error&&<p className="cw-error" role="alert">{error}</p>}{confirm&&<Modal title="Send payment invoice" onClose={()=>!busy&&setConfirm(false)}><div className="cw-form"><p>Send a bank-payment invoice for <strong>{money(live?.total)}</strong> to <strong>{live?.contact_email}</strong>.</p><p>The customer will receive an email with a payment link.</p>{error&&<p className="cw-error">{error}</p>}</div><footer><button disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button className="primary" disabled={busy} onClick={payment}>{busy?'Preparing…':'Send invoice'}</button></footer></Modal>}</Card>{matching&&<AccountingMatch order={order} onClose={()=>setMatching(false)} onSaved={()=>{setMatching(false);setVersion(v=>v+1);}}/>}</>;
}
function AccountingMatch({order,onClose,onSaved}){
 const [choices,setChoices]=useState(null),[values,setValues]=useState({customer_id:'',items:{},shipping_item_id:'',tax_code_id:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;draftRequest('accounting_choices',{id:order.id}).then(r=>{if(active)setChoices(r.choices);}).catch(e=>{if(active)setError(/qbo_/.test(e.message)?'Connect QuickBooks Online in Integrations first.':e.message);});return()=>{active=false;};},[order.id]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await draftRequest('save_accounting_mappings',{id:order.id,...values});onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const select=(label,options,value,onChange,required=true)=><label>{label}<select required={required} value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose a QuickBooks record</option>{options?.map(o=><option key={o.id} value={o.id}>{o.name}{o.sku?' · '+o.sku:''}</option>)}</select></label>;
 return <Modal title="Match QuickBooks records" wide onClose={onClose}><form onSubmit={save}><div className="cw-form"><p>Match the customer and products to the records in your migrated QuickBooks company. These matches will be reused on future orders.</p>{error&&<p className="cw-error" role="alert">{error}</p>}{!choices&&!error&&<p>Loading QuickBooks records…</p>}{choices&&<>{select(order.customer_name||order.email,choices.Customer,values.customer_id,v=>setValues({...values,customer_id:v}))}{order.lines.map(l=><div key={l.id}>{select(l.name+' · '+l.sku,choices.Item,values.items[l.product_id]||'',v=>setValues({...values,items:{...values.items,[l.product_id]:v}}))}</div>)}{order.shipping>0&&select('Shipping income item',choices.Item,values.shipping_item_id,v=>setValues({...values,shipping_item_id:v}))}{order.tax>0&&select('Sales tax code',choices.TaxCode,values.tax_code_id,v=>setValues({...values,tax_code_id:v}))}</>}</div><footer><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={!choices||busy}>{busy?'Saving…':'Save matches'}</button></footer></form></Modal>;
}
