#!/usr/bin/env node
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { REAL_PRODUCTS, REAL_CATEGORIES, REAL_COLLECTIONS } from '../src/data/realCatalog.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = path.join(ROOT, 'src', 'data', 'publicCatalog.generated.js');

function cleanVariant(variant = {}) {
  return {
    variant_id: variant.variant_id || null,
    sku: variant.sku || null,
    title: variant.title || 'Default',
    available: Boolean(variant.available),
    weight_grams: variant.weight_grams ?? null,
    options: variant.options || {},
    image: variant.image || '',
  };
}

function cleanProduct(product) {
  return {
    sku: product.sku,
    handle: product.handle,
    name: product.name,
    category: product.category,
    pack_size: product.pack_size || '1 ea',
    hcpcs: product.hcpcs || '—',
    moq: product.moq || 1,
    img: product.img || product.summary || product.name,
    summary: product.summary || '',
    description: product.description || '',
    images: product.images || [],
    hero_image: product.hero_image || null,
    variants: (product.variants || []).map(cleanVariant),
    tags: product.tags || [],
    collections: product.collections || [],
    product_type: product.product_type || null,
    m6_category: product.m6_category || null,
    quote_only: Boolean(product.quote_only),
    fda_registered: product.fda_registered ?? true,
    pdac_approved: Boolean(product.pdac_approved),
    taa_compliant: Boolean(product.taa_compliant),
    berry_compliant: Boolean(product.berry_compliant),
    mspv_listed: Boolean(product.mspv_listed),
    latex_free: Boolean(product.latex_free),
    country_of_origin: product.country_of_origin || null,
  };
}

const payload = {
  products: REAL_PRODUCTS.map(cleanProduct),
  categories: REAL_CATEGORIES.map((category) => ({
    slug: category.slug,
    name: category.name,
    parent: null,
    count: category.count,
  })),
  collections: REAL_COLLECTIONS.map((collection) => ({
    slug: collection.slug,
    name: collection.name,
    handles: collection.handles || [],
    category: collection.category || null,
  })),
};

const forbidden = /(^|_)(price|cost|cogs|margin|discount|vendor_price|contract_price)($|_)/i;
function assertSanitized(value, trail = []) {
  if (Array.isArray(value)) return value.forEach((entry, index) => assertSanitized(entry, [...trail, index]));
  if (!value || typeof value !== 'object') return;
  for (const [key, entry] of Object.entries(value)) {
    if (forbidden.test(key)) throw new Error(`forbidden public catalog key: ${[...trail, key].join('.')}`);
    assertSanitized(entry, [...trail, key]);
  }
}
assertSanitized(payload);

const source = `/* Generated by scripts/generate_public_catalog.mjs. Do not hand edit. */\nexport const PUBLIC_CATALOG = ${JSON.stringify(payload, null, 2)};\n`;
await writeFile(OUTPUT, source, 'utf8');
console.log(`Generated ${payload.products.length} public products at ${OUTPUT}`);
