import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {CRM_STAGES,LEAD_FIELDS,STAGE_LABEL} from '../../lib/crmSchema.js';
import {prospectRequest,publicLink} from '../../lib/prospectClient.js';
const show=v=>v===undefined||v===null||v===''?'Not found':typeof v==='object'?JSON.stringify(v):String(v);
function Sources({references=[]}){return <ul className="pl-sources">{references.filter(r=>publicLink(r.url)).map((r,i)=><li key={i}><a href={publicLink(r.url)} target="_blank" rel="noreferrer">{r.title||new URL(r.url).hostname} ↗</a>{r.snippet&&<p>{r.snippet}</p>}</li>)}</ul>;}
export function LeadDetail({lead,onClose,onSaved,initialTab='overview',onPrevious,onNext}){
 const [tab,setTab]=useState(initialTab),[edit,setEdit]=useState(!lead.id),[draft,setDraft]=useState(lead),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const patch=(key,value)=>setDraft(d=>({...d,[key]:value}));
 async function save(extra){setBusy(true);setError('');try{const changes=extra||Object.fromEntries([...LEAD_FIELDS.map(([k])=>k),'stage','do_not_contact','archived'].filter(k=>JSON.stringify(draft[k])!==JSON.stringify(lead[k])).map(k=>[k,draft[k]??'']));const r=await prospectRequest({},lead.id?{action:'save',id:lead.id,revision:lead.revision,patch:changes}:{action:'create_lead',patch:{company:draft.company,...changes}});setDraft(r.lead);setEdit(false);onSaved(r.lead);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const changed=JSON.stringify(draft)!==JSON.stringify(lead);
 function close(){if(edit&&changed){setError('Save your changes or select Discard edits before closing.');return;}onClose();}
 const research=lead.research||{},logo=publicLink(research.properties?.company?.logoUrl);const [logoFailed,setLogoFailed]=useState(false);
 useEffect(()=>{const escape=e=>{if(e.key==='Escape')close();};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape);});
 return <aside className="pl-lead-drawer" aria-label="Lead details"><header className="pl-drawer-top"><strong>Lead details</strong><div><button aria-label="Previous lead" disabled={!onPrevious||edit} onClick={onPrevious}>↑</button><button aria-label="Next lead" disabled={!onNext||edit} onClick={onNext}>↓</button><button aria-label="Close lead details" onClick={close}>×</button></div></header><div className="pl-detail">
  <div className="pl-detail-identity"><span className="pl-company-icon">{logo&&!logoFailed?<img src={logo} alt="" referrerPolicy="no-referrer" onError={()=>setLogoFailed(true)}/>:((lead.company||'U').slice(0,1))}</span><div><strong>{lead.company||'Add an organization'}</strong><p>{lead.segment||lead.industry||'Prospect'}{lead.location?' · '+lead.location:''}</p>{publicLink(lead.website)&&<a href={publicLink(lead.website)} target="_blank" rel="noreferrer">{new URL(lead.website).hostname} ↗</a>}</div><span className="pl-badge">{STAGE_LABEL[lead.stage]||'New prospect'}</span></div>
  <nav className="pl-tabs" aria-label="Prospect details">{['overview','evidence','activity'].map(t=><button key={t} disabled={edit&&t!=='overview'} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='evidence'?'Research':t==='overview'?'CRM details':'Activity'}</button>)}</nav>
  {error&&<p role="alert" className="cw-error">{error}</p>}
  {tab==='overview'&&<>{lead.description&&<p className="pl-description">{lead.description}</p>}{edit?<form id="lead-form" onSubmit={e=>{e.preventDefault();save();}}><div className="pl-field-grid">{LEAD_FIELDS.map(([key,label])=><label key={key}>{label}{['notes','product_interest'].includes(key)?<textarea rows={4} value={draft[key]||''} onChange={e=>patch(key,e.target.value)}/>:<input required={key==='company'} type={['next_follow_up','close_date'].includes(key)?'date':['expected_value','employees'].includes(key)?'number':key==='email'?'email':['website','linkedin'].includes(key)?'url':'text'} min={['expected_value','employees'].includes(key)?0:undefined} value={key==='tags'?(draft.tags||[]).join(', '):draft[key]??''} onChange={e=>patch(key,key==='tags'?e.target.value.split(',').map(v=>v.trim()).filter(Boolean):e.target.value)}/>}</label>)}<label>Stage<select value={draft.stage||'new'} onChange={e=>patch('stage',e.target.value)}>{CRM_STAGES.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="pl-check"><input type="checkbox" checked={!!draft.do_not_contact} onChange={e=>patch('do_not_contact',e.target.checked)}/>Do not contact</label></div></form>:<><dl className="pl-data-grid">{LEAD_FIELDS.filter(([k])=>!['company','notes','product_interest'].includes(k)).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{key==='tags'?(lead.tags||[]).join(', ')||'None':show(lead[key])}</dd></div>)}</dl>{lead.do_not_contact&&<p className="cw-error">Do not contact this prospect.</p>}<section><h3>Product fit</h3><p>{lead.product_interest||'No product-fit research recorded.'}</p><h3>Outreach angle</h3><p>{lead.outreach_angle||'Review the evidence before drafting an introduction.'}</p><h3>Notes</h3><p className="pl-preserve">{lead.notes||'No notes yet.'}</p></section></>}</>}
  {tab==='evidence'&&<div className="pl-evidence">{(research.review_notes||[]).map((note,i)=><p className="cw-error" key={i}>{note}</p>)}<details open><summary>Relevance summary</summary><p>{lead.description||'No summary recorded.'}</p></details><p>Public-source research. A matching company is a prospect, not a confirmed buyer. Published contact details are not a deliverability guarantee.</p>{(research.evaluations||[]).map((e,i)=><details key={i} open><summary>{e.criterion}</summary><span className={'pl-badge '+(e.satisfied==='yes'?'good':'')}>{e.satisfied==='yes'?'✓ Matches':e.satisfied==='no'?'Does not match':'Needs review'}</span><p>{e.reasoning}</p><Sources references={e.references}/></details>)}{(research.enrichments||[]).map(e=><details key={e.enrichmentId} open><summary>{e.title}</summary><span className="pl-badge">{e.status}</span><p className="pl-preserve">{e.result?.join('\n')||'Not found yet'}</p><p>{e.reasoning}</p><Sources references={e.references}/></details>)}{!research.item_id&&<p>This record was added manually.</p>}<details open><summary>Basic information</summary><dl className="pl-data-grid">{Object.entries({Employees:research.properties?.company?.employees,Founded:research.properties?.company?.foundedYear,Headquarters:Object.values(research.properties?.company?.headquarters||{}).filter(Boolean).join(', '),'Annual revenue (research)':research.properties?.company?.financials?.revenueAnnual,'Total funding (research)':research.properties?.company?.financials?.fundingTotal,'Monthly visits (research)':research.properties?.company?.webTraffic?.visitsMonthly}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl><p>{research.properties?.company?.about}</p></details><details><summary>All source fields</summary><pre>{JSON.stringify(research.properties||{},null,2)}</pre></details></div>}
  {tab==='activity'&&<ol className="pl-activity">{[...(lead.events||[])].reverse().map((e,i)=><li key={e.id||i}><span className="pl-dot"/><div><strong>{e.text}</strong><p>{e.actor} · {new Date(e.at).toLocaleString()}</p>{e.changes&&<details><summary>View changes</summary>{Object.entries(e.changes).map(([k,v])=><p key={k}>{k.replaceAll('_',' ')}: {show(v.before)} → {show(v.after)}</p>)}</details>}</div></li>)}</ol>}
  <footer className="pl-detail-footer">{edit?<><button disabled={busy} onClick={()=>{setDraft(lead);setEdit(false);setError('');if(!lead.id)onClose();}}>Discard edits</button><button className="primary" form="lead-form" disabled={busy} type="submit">{busy?'Saving…':'Save prospect'}</button></>:<><button onClick={()=>{setTab('overview');setEdit(true);}}>Edit details</button>{CRM_STAGES.find(s=>s.id===lead.stage)?.lane==='prelead'&&!lead.archived&&<button className="primary" disabled={busy||lead.do_not_contact} onClick={()=>save({stage:'qualified'})}>Add to pipeline</button>}<Link to={'/admin/chat?prompt='+encodeURIComponent('Review prospect '+lead.company+' ('+lead.id+'). Show the evidence and suggest a factual introduction. Do not send an email.')}>Ask Unite ↗</Link><button disabled={busy} onClick={()=>save({archived:!lead.archived})}>{lead.archived?'Restore':'Archive'}</button></>}</footer>
 </div></aside>;
}
