import {useState} from 'react';
import {UMLogoMark} from '../shared/Logo.jsx';
import {prospectRequest} from '../../lib/prospectClient.js';
export function ProspectSearch({onCreated,connected}){
 const [query,setQuery]=useState(''),[entity,setEntity]=useState('company'),[count,setCount]=useState(25),[title,setTitle]=useState(''),[criteria,setCriteria]=useState(['Operates in the United States']),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const examples=[['DME & medical suppliers','US independent DME/HME companies and medical-supply distributors offering orthopedic braces or cold-therapy recovery products.'],['Orthopedic & pain practices','Independent US orthopedic and pain-management practices providing bracing or post-operative recovery care.'],['Surgery centers','US ambulatory surgery centers performing orthopedic procedures with recurring clinical and surgical supply needs.']];
 async function run(e){e.preventDefault();if(!review){setReview(true);return;}setBusy(true);setError('');try{const r=await prospectRequest({},{action:'search',query,entity,count,title:title||query.slice(0,85),criteria});onCreated(r.list);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="pl-search-home"><UMLogoMark size={48}/><span className="pl-eyebrow">UNITE PROSPECTING</span><h1>Find your next customer.</h1><p>Describe the companies or people you want to reach.<br/>Get a researched list, with the evidence beside it.</p><form onSubmit={run} className="pl-search-builder"><div className="pl-entity-switch">{[['company','Companies'],['person','People']].map(([id,label])=><button type="button" aria-pressed={entity===id} key={id} onClick={()=>{setEntity(id);setReview(false);}}>{label}</button>)}</div><textarea aria-label="Describe your ideal prospects" required minLength={15} maxLength={5000} rows={4} value={query} placeholder="Find orthopedic practices in the Southeast that provide post-operative bracing…" onChange={e=>{setQuery(e.target.value);setReview(false);}}/>{review&&<div className="pl-search-review"><label>List name<input value={title} onChange={e=>setTitle(e.target.value)} placeholder={query.slice(0,85)} maxLength={140}/></label><h3>Match criteria</h3>{criteria.map((c,i)=><div className="pl-criterion-input" key={i}><input aria-label={'Criterion '+(i+1)} value={c} maxLength={500} onChange={e=>setCriteria(v=>v.map((x,j)=>i===j?e.target.value:x))}/><button type="button" aria-label={'Remove criterion '+(i+1)} onClick={()=>setCriteria(v=>v.filter((_,j)=>j!==i))}>×</button></div>)}{criteria.length<5&&<button type="button" onClick={()=>setCriteria(v=>[...v,''])}>+ Add criterion</button>}<p>Includes buying contact, business email, phone, product fit and segment research. Uses your Exa credits. Existing customer organizations are excluded using the saved customer-domain list and checked again when results are imported.</p></div>}<footer><label>Results<select aria-label="Number of prospects" value={count} onChange={e=>setCount(Number(e.target.value))}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" disabled={busy||connected===false}>{busy?'Starting search…':review?'Run search →':'Review search →'}</button></footer>{error&&<p role="alert" className="cw-error">{error}</p>}{connected===false&&<p className="cw-error">Connect Exa before running a search.</p>}</form><div className="pl-example-grid">{examples.map(([name,text])=><button key={name} onClick={()=>{setQuery(text);setTitle(name);setReview(false);}}><span>↗</span><strong>{name}</strong><small>{text}</small></button>)}</div></div>;
}
