import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {useSEO} from '../../lib/seo.js';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const label={release:'Release paid order',write_off:'Write-off review',credit_release:'Credit release'};
export function AdminDecisions(){
  useSEO({title:'Approvals & release · Unite',noindex:true});
  const [data,setData]=useState(null),[mode,setMode]=useState('release'),[selected,setSelected]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[amount,setAmount]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const dirty=!!(reason||reference||amount);
  const load=useCallback(async()=>{try{setData(await workspaceRequest('/api/finance/decisions'));setError('');}catch(e){setError(e.message);}},[]);
  useEffect(()=>{const c=new AbortController();workspaceRequest('/api/finance/decisions',{signal:c.signal}).then(r=>{if(!c.signal.aborted)setData(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
  const rows=mode==='decisions'?(data?.decisions||[]).filter(d=>['pending_approval','approved'].includes(d.status)):mode==='write_off'?(data?.invoices||[]):(data?.orders||[]).filter(o=>mode==='release'?o.release_required:!['paid','terms_approved'].includes(o.payment_status));
  const row=rows.find(r=>r.id===selected)||rows[0];
  const target=mode==='decisions'?(row?.kind==='write_off'?data?.invoices:data?.orders)?.find(r=>r.id===row?.target_id):row;
  function discard(){setReason('');setReference('');setAmount('');}
  function navigate(fn){if(dirty){setNotice('Save or discard this review before switching records.');return;}fn();setNotice('');}
  async function submit(action){
    if(!row)return;setBusy(true);setError('');setNotice('');
    try{
      const input={action,reason,reference,amount:mode==='credit_release'?Number(row.total)-Number(row.paid_amount||0):Number(amount),kind:mode,target_id:row.id,fingerprint:row.fingerprint};
      if(mode==='decisions')Object.assign(input,{decision_id:row.id,expected_revision:row.revision,kind:row.kind,target_id:row.target_id,fingerprint:target?.fingerprint});
      const result=await postWorkspace('/api/finance/decisions',input);
      discard();setNotice(action==='release'?`Release saved. Jacobe and Darren have follow-up tasks.${result.allocation&&!result.allocation.ok?' Stock still needs attention: '+String(result.allocation.reason).replaceAll('_',' ')+'.':''}`:action==='request'?'Review saved for Damon’s decision.':action==='record_write_off'?'Accounting evidence recorded. Cash received was not changed.':'Decision saved.');await load();if(action==='request'){setMode('decisions');setSelected(result.decision?.id||'');}
    }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  const action=mode==='decisions'?row?.status==='pending_approval'&&data?.permissions.approve?'approve':row?.status==='approved'&&data?.permissions.review?(row.kind==='write_off'?'record_write_off':'release'):null:data?.permissions.review?(mode==='release'?'release':'request'):null;
  return <AdminShell active="decisions" unsavedChanges={dirty}><main id="main" className="uw-work-page"><header className="uw-page-heading"><div><span className="uw-eyebrow">Finance & operations</span><h1>Approvals & release</h1><p>Evidence first. One clear next step for every decision.</p></div><Link className="uw-button" to="/admin/finance">Invoices & payments</Link></header>
    {error&&<p role="alert" className="uw-error">{error}</p>}{notice&&<p role="status" className="uw-notice">{notice}</p>}
    <div className="uw-queue-filters"><div>{[['release','Paid orders'],['decisions','Approval queue'],['write_off','Request write-off'],['credit_release','Request credit release']].map(([key,title])=><button key={key} aria-pressed={mode===key} onClick={()=>navigate(()=>{setMode(key);setSelected('');})}>{title}</button>)}</div><button className="uw-button quiet" disabled={dirty||busy} onClick={load}>Refresh</button></div>
    <div className={`uw-work-grid ${row?'has-detail':''}`}><section className="uw-work-list"><div className="uw-queue-heading"><h2>{mode==='decisions'?'Waiting for a decision':label[mode]}</h2><span className="uw-badge">{data?rows.length:'—'}</span></div>{!data&&!error?<p className="uw-empty">Loading financial reviews…</p>:!rows.length?<p className="uw-empty">{error?'Reviews could not be loaded.':'Nothing waiting in this view.'}</p>:<ul className="uw-queue">{rows.map(r=><li key={r.id}><button className={`uw-work-row ${r.id===row.id?'is-selected':''}`} aria-pressed={r.id===row.id} onClick={()=>navigate(()=>setSelected(r.id))}><span className="uw-row-copy"><strong>{r.customer_name||r.target_id||r.id}</strong><span>{r.kind?label[r.kind]:r.id}</span></span><span className="uw-row-state"><strong>{money(mode==='credit_release'?Number(r.total)-Number(r.paid_amount||0):mode==='decisions'?r.amount:r.balance??r.total??r.amount)}</strong><span className="uw-badge">{String(r.status||'Awaiting review').replaceAll('_',' ')}</span></span></button></li>)}</ul>}</section>
    {row&&<aside className="uw-detail"><span className="uw-eyebrow">{label[row.kind||mode]||'Decision'}</span><h2>{row.target_id||row.id}</h2><dl className="uw-facts">{[[['write_off','credit_release'].includes(mode)?'Open balance':'Amount',money(mode==='credit_release'?Number(row.total)-Number(row.paid_amount||0):mode==='write_off'?row.balance??row.amount:row.amount??row.total)],['Status',String(row.status||'Pending').replaceAll('_',' ')],['Ashley’s review',row.review?.reason],['Evidence',row.review?.reference],['Damon’s decision',row.approval?.reason]].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>
    {mode==='decisions'&&!row.current&&<p className="uw-error">The source record changed. This approval cannot be applied; submit a new review using the current amount.</p>}
    {action?<form className="uw-followup" onSubmit={e=>{e.preventDefault();submit(action);}}><h3>{action==='approve'?'Damon’s decision':action==='record_write_off'?'Record the accounting posting':action==='release'?'Ashley’s release review':'Ashley’s accuracy review'}</h3>{mode==='write_off'&&<label>Amount to write off<input type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label>}{action!=='approve'&&<label>{action==='record_write_off'?'QuickBooks posting reference':'Bank, accounting, or review reference'}<input required maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label>}<label>Review note<textarea required rows={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="uw-detail-actions"><button className="uw-button primary" disabled={busy||(mode==='decisions'&&!row.current)}>{busy?'Saving…':action==='approve'?'Approve':action==='record_write_off'?'Record write-off':action==='release'?'Clear release':'Send to Damon for review'}</button>{action==='approve'&&<button type="button" className="uw-button" disabled={busy||!reason.trim()} onClick={()=>submit('reject')}>Reject</button>}<button type="button" className="uw-button quiet" disabled={busy} onClick={discard}>Discard changes</button></div><p>{action==='record_write_off'?'Record a posting already made in QuickBooks. This does not post to QuickBooks or mark the order paid.':action==='release'?'Payment review clears the finance step. Stock, shipping, and other approval checks still apply.':'No funds move when a review or decision is recorded.'}</p></form>:<p className="uw-notice">{row.status==='pending_approval'?'Waiting for Damon’s decision.':'Ashley completes the payment or accounting step.'}</p>}</aside>}
    </div></main></AdminShell>;
}
