import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {WorkspaceIcon} from '../../components/workspace/WorkspaceIcon.jsx';
import {useSEO} from '../../lib/seo.js';
import {db} from '../../lib/db.js';
import {availability} from '../../lib/wms/availability.js';
export function AdminInventory(){
 useSEO({title:'Inventory · Unite workspace',noindex:true});
 const products=db.useTable('products'),inventory=db.useTable('inventory'),warehouses=db.useTable('warehouses');
 const lots=db.useTable('lots');
 const [search,setSearch]=useState(''),[location,setLocation]=useState(''),[filter,setFilter]=useState('all');
 const rows=useMemo(()=>products.flatMap(p=>(p.variants?.length?p.variants:[p]).map(v=>({product:{...p,...v,id:v.id,product_id:p.id,name:p.variants?.length>1?`${p.name} · ${v.title}`:p.name},loaded:inventory.some(i=>i.sku===v.sku&&(!location||i.warehouse_id===location)),onHand:availability.onHand(v.sku,location||null),reserved:availability.reserved(v.sku,location||null),available:availability.availableToPromise(v.sku,location||null)}))),[products,inventory,lots,location]); // eslint-disable-line react-hooks/exhaustive-deps
 const shown=rows.filter(r=>(filter!=='out'||r.loaded&&r.available<=0)&&`${r.product.name} ${r.product.sku}`.toLowerCase().includes(search.toLowerCase()));
 return <AdminShell active="inventory"><main id="main" className="uw-workday"><header className="uw-day-heading"><div><h1>Inventory</h1><p>Track available, committed and on-hand stock by location.</p></div><div className="uw-inventory-actions"><Link className="uw-button" to="/admin/inventory/count">Stock count</Link><Link className="uw-button primary" to="/admin/inventory/receive">Receive inventory</Link></div></header>
 <>{inventory.some(i=>i.test_batch)&&<p className="uw-notice">Provisional stock · September 8 Shopify export at Unite Medical Warehouse. A physical count is pending. “Not loaded” means the source stock needs review.</p>}</><section className="uw-home-metrics" aria-label="Inventory totals">{[['Variants',rows.length],['On hand',rows.reduce((n,r)=>n+r.onHand,0)],['Available',rows.reduce((n,r)=>n+r.available,0)]].map(([label,value])=><div className="uw-inventory-metric" key={label}><span>{label}</span><strong>{value.toLocaleString()}</strong><small>{location?warehouses.find(w=>w.id===location)?.name:'All Unite-owned locations'}</small></div>)}</section>
 <section className="uw-work-list"><div className="uw-queue-heading"><div role="group" className="uw-type-filters" aria-label="Inventory views"><button aria-pressed={filter==='all'} onClick={()=>setFilter('all')}>All</button><button aria-pressed={filter==='out'} onClick={()=>setFilter('out')}>Out of stock</button></div><select aria-label="Inventory location" value={location} onChange={e=>setLocation(e.target.value)}><option value="">All locations</option>{warehouses.filter(w=>w.active!==false).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div className="uw-inventory-search"><label className="uw-search"><WorkspaceIcon name="search" size={16}/><input aria-label="Search inventory" placeholder="Search products or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{shown.length} variants</span></div>
 {!rows.length?<div className="uw-empty"><WorkspaceIcon name="box" size={36}/><h3>Your inventory starts here</h3><p>Add products first, then receive or count stock to record your opening inventory.</p><Link className="uw-button primary" to="/admin/products">Go to products</Link></div>:<div className="um-scroll-x"><table className="uw-inventory-table"><thead><tr><th>Product</th><th>SKU</th><th>Available</th><th>Held / committed</th><th>On hand</th></tr></thead><tbody>{shown.map(r=><tr key={r.product.id}><td><Link to={`/admin/products/edit/${encodeURIComponent(r.product.product_id)}`}>{r.product.name}</Link></td><td>{r.product.sku}</td><td><span className={`uw-badge ${r.loaded&&r.available<=0?'is-waiting':''}`}>{r.loaded?r.available.toLocaleString():'Not loaded'}</span></td><td>{r.loaded?r.reserved.toLocaleString():'—'}</td><td>{r.loaded?r.onHand.toLocaleString():'—'}</td></tr>)}</tbody></table>{!shown.length&&<div className="uw-empty">No products match your search or filters.</div>}</div>}</section></main></AdminShell>;
}
