import { useSEO } from '../../lib/seo.js';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { AdminShell } from '../../components/layout/AdminShell.jsx';
import { db } from '../../lib/db.js';
import { reviewShopifyCsv } from '../../lib/shopifyFileReview.js';
import { postWorkspace } from '../../lib/workspaceRequest.js';
import decisions from '../../data/damonLegacyOrderDecisions.generated.json';
import '../../styles/workspace.css';
const EXPORTS=[['products','Products','Export all products. Keep variants and their prices.','https://help.shopify.com/en/manual/products/import-export/export-products'],['customers','Customers','Export all customers, including consent and tax status.','https://help.shopify.com/en/manual/customers/import-export-customers'],['orders','Orders','Export all orders for history, then refresh open orders before cutover.','https://help.shopify.com/en/manual/fulfillment/managing-orders/exporting-orders'],['inventory','Inventory by location','Choose All locations, All states and All variants.','https://help.shopify.com/en/manual/products/inventory/setup/inventory-csv']];
const ACTIONS={transfer:'Approved for review',archive:'Archive in Shopify',cancel:'Cancel in Shopify',hold_customer:'Waiting for customer',hold_warehouse:'Waiting for warehouse',undecided:'Decision needed'};
export function AdminLaunch(){
 useSEO({title:'Launch preparation',noindex:true});
 const [params,setParams]=useSearchParams();const tab=['files','customers','orders'].includes(params.get('tab'))?params.get('tab'):'files';
 return <AdminShell active="launch"><main id="main" className="um-workspace"><header className="ws-header"><div><div className="ws-eyebrow">Launch preparation</div><h1>Refresh. Review. Verify.</h1><p>Prepare the next Shopify snapshot, then resolve customer and order exceptions.</p></div><Link className="ws-button" to="/admin/integrations">Check connections</Link></header>
  <nav className="ws-actions" aria-label="Launch steps" style={{marginBottom:24}}>{[['files','1. Shopify files'],['customers','2. Customer access'],['orders','3. Legacy orders']].map(([id,label])=><button key={id} className={`ws-button ${tab===id?'primary':''}`} aria-current={tab===id?'page':undefined} onClick={()=>setParams({tab:id})}>{label}</button>)}</nav>
  <div hidden={tab!=='files'}><ShopifyFiles/></div>{tab==='customers'?<CustomerAccess/>:tab==='orders'?<LegacyOrders/>:null}
  <section className="ws-card"><h2>Before going live</h2><p>File checks are one step. Launch still needs confirmed pricing, reconciled stock and successful staging tests.</p><div className="ws-actions"><Link to="/admin/customers">Customer pricing</Link><Link to="/admin/inventory/count">Inventory counts</Link><Link to="/admin/finance">Payment review</Link><Link to="/admin/inventory/barcodes">Barcode exceptions</Link></div></section>
 </main></AdminShell>;
}
function ShopifyFiles(){
 const [files,setFiles]=useState({});const [busy,setBusy]=useState('');const [error,setError]=useState('');
 async function check(kind,file){if(!file)return;setBusy(kind);setError('');setFiles(old=>{const next={...old};delete next[kind];return next;});try{if(file.size>40*1024*1024)throw new Error('Choose a CSV smaller than 40 MB, or split the export.');const result=reviewShopifyCsv(await file.text(),kind);setFiles(old=>({...old,[kind]:{...result,file:file.name}}));}catch(e){setError(e.message);}finally{setBusy('');}}
 function download(){const blob=new Blob([JSON.stringify({review:'local_file_preflight',not_imported:true,files:Object.values(files)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`unite-file-review-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="ws-card"><div className="ws-header"><div><h2>Tonight’s Shopify download</h2><p>Choose each original CSV to check its structure and flag missing data. Files stay in this tab; nothing is imported or sent.</p></div><span className="ws-pill">{Object.keys(files).length} of 4 files checked</span></div>
 {error&&<div className="ws-error" role="alert">{error}</div>}
 {EXPORTS.map(([kind,title,detail,url])=><div className="ws-details" key={kind}><div className="ws-row" style={{border:0,padding:'4px 0 12px'}}><div><strong>{title}</strong><span className="ws-muted">{detail} <a href={url} target="_blank" rel="noreferrer">Export guide</a></span></div></div><label>Choose {title.toLowerCase()} CSV<input disabled={Boolean(busy)} type="file" accept=".csv,text/csv" onChange={e=>check(kind,e.target.files?.[0])}/></label>{busy===kind&&<p role="status">Checking file…</p>}{files[kind]&&<div><p role="status"><strong>{files[kind].count.toLocaleString()} {files[kind].label}</strong> · {files[kind].file}</p>{files[kind].issues.length?<ul>{files[kind].issues.map((issue,i)=><li key={i} className="ws-muted" style={{marginBottom:8}}>{issue.count?`${issue.count} `:''}{issue.message}</li>)}</ul>:<p>Basic structure checks passed. Business approval is still required.</p>}</div>}</div>)}
 <div className="ws-note">Keep tonight’s files together in a dated folder. Customer-specific pricing, certificate documents and live remaining order quantities need separate evidence. Selecting a file does not prove that it is fresh or complete.</div><button className="ws-button" disabled={!Object.keys(files).length||Boolean(busy)} onClick={download}>Download review summary</button>
 <details className="ws-details"><summary>Previously imported Shopify history</summary><p>Review stored source records separately from tonight’s files.</p><Link to="/admin/shopify-history">Open imported history</Link></details>
 </section>;
}
function CustomerAccess(){
 const profiles=db.useTable('profiles');const [search,setSearch]=useState('');const [busy,setBusy]=useState('');const [error,setError]=useState('');const [preview,setPreview]=useState(null);
 const pending=profiles.filter(p=>p.activation_required&&p.status==='pending_activation');const shown=pending.filter(p=>`${p.name||''} ${p.email||''}`.toLowerCase().includes(search.toLowerCase()));
 async function issue(p){setBusy(p.id);setError('');setPreview(null);try{const result=await postWorkspace('/api/admin/customer-activations',{profile_id:p.id});setPreview({...result,name:p.name,email:p.email});}catch(e){setError(e.message);}finally{setBusy('');}}
 return <section className="ws-card"><h2>Help existing customers sign in</h2><p>Review pending accounts and create one activation link at a time. No email is sent by this screen.</p><label>Find a pending account<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPreview(null);}} placeholder="Name or email"/></label>{error&&<p role="alert" className="ws-error">{error}</p>}{!shown.length&&<p className="ws-empty">No matching pending accounts are loaded. Confirm the staging customer import before sending invitations.</p>}<ul className="ws-list">{shown.slice(0,50).map(p=><li className="ws-row" key={p.id}><div><strong>{p.name||'Customer'}</strong><span className="ws-muted">{p.email||'Email needed'}</span></div><button className="ws-button" disabled={Boolean(busy)||!p.email} onClick={()=>issue(p)}>{busy===p.id?'Creating…':'Create activation link'}</button></li>)}</ul>{shown.length>50&&<p>Narrow your search to find more accounts. Showing 50 of {shown.length}.</p>}{preview&&<section className="ws-note" aria-label="Activation preview"><h3>Link ready for {preview.name||preview.email}</h3><p>Review the message with Damon before sending. Ordering remains subject to account and pricing approval.</p><label>Activation link<input readOnly value={preview.activation_url} onFocus={e=>e.target.select()}/></label><p>Expires {new Date(preview.expires_at).toLocaleString()}.</p><button className="ws-button" onClick={()=>setPreview(null)}>Close preview</button></section>}<Link to="/admin/customers">Review pricing and account details →</Link></section>;
}
function LegacyOrders(){
 const [selected,setSelected]=useState('');const [preview,setPreview]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState(null);
 const decision=decisions.decisions.find(d=>d.shopify_order_id===selected);
 async function perform(action){setBusy(true);setError('');if(action==='preview'){setPreview(null);setResult(null);}try{const body=await postWorkspace('/api/admin/legacy-shopify-orders',{action,shopify_order_id:selected,...(action==='stage_transfer'?{preview_hash:preview.hash}:{})});if(action==='preview')setPreview(body.preview);else{setResult(body);setPreview(null);}}catch(e){setError(e.message);setPreview(null);}finally{setBusy(false);}}
 return <section className="ws-card"><h2>Keep legacy orders under control</h2><p>Shopify remains responsible for pre-cutover orders. Review the current Shopify record before staging a selected transfer.</p><label>Order to review<select value={selected} disabled={busy} onChange={e=>{setSelected(e.target.value);setPreview(null);setResult(null);setError('');}}><option value="">Choose an order</option>{decisions.decisions.map(d=><option key={d.shopify_order_id} value={d.shopify_order_id}>{d.order_number} · {ACTIONS[d.action]||d.action.replaceAll('_',' ')}</option>)}</select></label><div className="ws-actions" style={{marginTop:16}}><button className="ws-button primary" disabled={!selected||busy} onClick={()=>perform('preview')}>{busy?'Working…':'Get current Shopify details'}</button></div>{error&&<div className="ws-error" role="alert">{error}</div>}{preview&&<div style={{marginTop:24}}><h3>{preview.order_number} · remaining items</h3><p>Shopify last updated {new Date(preview.updated_at).toLocaleString()}.</p><ul className="ws-list">{preview.lines.map(l=><li className="ws-row" key={l.source_line_id}><div><strong>{l.name}</strong><span className="ws-muted">{l.sku}</span></div><span>{l.transferable_quantity} remaining</span></li>)}</ul><p>{preview.cancelled_at||preview.closed?'This order is closed or cancelled.':!preview.lines.length?'No remaining quantity.':'Review the quantities before continuing.'}</p>{decision?.action==='transfer'&&preview.lines.length>0&&!preview.closed&&!preview.cancelled_at&&<><div className="ws-note">Staging creates a held Unite record. It does not charge, ship, email, or release the Shopify commitment.</div><button className="ws-button" disabled={busy} onClick={()=>perform('stage_transfer')}>Stage reviewed transfer</button></>}</div>}{result&&<div className="ws-note" role="status">{result.replay?'This transfer was already staged.':'Transfer staged.'} It remains held pending Shopify acknowledgment.</div>}<details className="ws-details"><summary>Decisions still needed</summary><ul>{decisions.decisions.filter(d=>d.action!=='transfer'&&d.action!=='archive'&&d.action!=='cancel').map(d=><li key={d.shopify_order_id}>{d.order_number}: {ACTIONS[d.action]||d.action.replaceAll('_',' ')}</li>)}</ul></details></section>;
}
