import {useCallback,useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {WorkspaceIcon} from '../../components/workspace/WorkspaceIcon.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {useSEO} from '../../lib/seo.js';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
function RefundDetail({row,permissions,onSaved}){
 const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const action=permissions.review&&!row.accuracy_current?'review_refund':permissions.approve&&row.accuracy_current&&!row.approval_current?'approve_refund':null;
 async function submit(e){e.preventDefault();if(!action)return;setBusy(true);setError('');try{await postWorkspace('/api/returns/action',{rma_id:row.id,expected_revision:row.revision||0,action,reason});await onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <aside className="uw-detail"><span className="uw-eyebrow">Refund review</span><h2>{row.id}</h2><dl className="uw-facts">{[['Order',row.order_id],['Refund amount',money(row.refund_total)],['Restocking fee',money(row.restocking_fee)],['Ashley accuracy review',row.accuracy_current?'Recorded':'Pending'],['Damon final approval',row.approval_current?'Recorded':'Pending']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="uw-approval-steps"><div className={row.accuracy_current?'done':''}><span>1</span><div><strong>Ashley checks accuracy</strong><p>{row.refund_accuracy_review?.reason||'Verify the items, condition, amount, and fee.'}</p></div></div><div className={row.approval_current?'done':''}><span>2</span><div><strong>Damon approves</strong><p>{row.refund_final_approval?.reason||'Final decision after the accuracy review.'}</p></div></div><div><span>3</span><div><strong>Reconcile the refund</strong><p>Record actual payment through the approved payment process.</p></div></div></div>{action?<form className="uw-followup" onSubmit={submit}><label>{action==='review_refund'?'Accuracy review note':'Final approval reason'}<textarea required rows={4} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="uw-error">{error}</p>}<button className="uw-button primary" disabled={busy||!reason.trim()}>{busy?'Saving…':action==='review_refund'?'Record accuracy review':'Record final approval'}</button><p>This records a decision. It does not issue a refund.</p></form>:<p className="uw-notice">{row.approval_current?'Both reviews are recorded. Actual refund payment must be reconciled separately.':!row.accuracy_current?'Waiting for Ashley’s accuracy review.':'Waiting for Damon’s final approval.'}</p>}</aside>;
}
export function AdminRefundReviews(){
 const [params,setParams]=useSearchParams(),[data,setData]=useState(null),[error,setError]=useState(''),[selectedId,setSelectedId]=useState(params.get('rma')||''),[notice,setNotice]=useState('');
 useSEO({title:'Refund reviews · Team workspace',noindex:true});
 const load=useCallback(async signal=>{try{setData(await workspaceRequest('/api/admin/refund-reviews',{signal}));setError('');}catch(e){if(!signal?.aborted)setError(e.message);}},[]);
 useEffect(()=>{const c=new AbortController();Promise.resolve().then(()=>{if(!c.signal.aborted)load(c.signal);});return()=>c.abort();},[load]);
 const selected=data?.rmas.find(r=>r.id===selectedId);
 return <AdminShell active="refund-reviews"><main id="main" className="uw-workday"><header className="uw-day-heading"><div><span className="uw-eyebrow">Finance · Reviews</span><h1>Clear checks. Clear decisions.</h1><p>Ashley reviews accuracy. Damon gives final approval. Every amount follows the same sequence.</p></div><button className="uw-button" onClick={()=>load()}><WorkspaceIcon name="refresh" size={16}/>Refresh</button></header>{error&&<p className="uw-error" role="alert">{error}</p>}{notice&&<p className="uw-notice" role="status">{notice}</p>}{data&&!data.permissions.ashley_configured&&<p className="uw-notice">Ashley’s reviewer account has not been configured. Refund accuracy review remains unavailable until her exact staff account is connected.</p>}<div className={`uw-work-grid ${selected?'has-detail':''}`}><section className="uw-work-list"><div className="uw-queue-heading"><h2>Refunds awaiting completion</h2><span className="uw-badge">{data?.rmas.length??'—'}</span></div>{!data&&!error?<p className="uw-empty" role="status">Loading reviews…</p>:!data?.rmas.length?<p className="uw-empty">{error?'Reviews could not be loaded.':'No refunds awaiting review.'}</p>:<ul className="uw-queue">{data.rmas.map(r=><li key={r.id}><button className={`uw-work-row ${selectedId===r.id?'is-selected':''}`} aria-pressed={selectedId===r.id} onClick={()=>{setSelectedId(r.id);setParams({rma:r.id},{replace:true});}}><span className="uw-type-icon"><WorkspaceIcon name="money" size={18}/></span><span className="uw-row-copy"><strong>{r.id}</strong><span className="uw-row-next">Order {r.order_id}</span></span><span className="uw-row-state"><strong>{money(r.refund_total)}</strong><span className="uw-badge">{r.approval_current?'Approved':r.accuracy_current?'Damon’s review':'Ashley’s review'}</span></span><WorkspaceIcon name="arrow" size={16}/></button></li>)}</ul>}</section>{selected&&<RefundDetail key={`${selected.id}:${selected.revision||0}`} row={selected} permissions={data.permissions} onSaved={async()=>{setNotice('Decision saved. The refund payment has not been issued.');await load();}}/>}</div></main></AdminShell>;
}
