import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminShell } from '../../components/layout/AdminShell.jsx';
import { useSEO } from '../../lib/seo.js';
import '../../styles/workspace.css';

const WORKFLOWS=[
  ['Daily work','/admin/desk','Find what needs attention, assign an owner and next action, then refresh to confirm it saved.'],
  ['Customers','/admin/customers','Find three familiar customers. Check contact details, address, tax exemption and pricing hold. Do not activate real customer accounts during testing.'],
  ['Shopify history','/admin/shopify-history','Filter the September import by orders, open orders, transactions and inventory. Find a familiar order and compare it with Shopify. Historical orders are evidence, not new fulfillment work.'],
  ['Products and stock','/admin/products','Find stocked and sourced products. Check SKU, variant, price and barcode. Review provisional stock at Inventory; Shopify totals are not a verified physical count.'],
  ['Quotes','/admin/quotes','Create a test draft using a clearly named test customer. Change quantity and review pricing, freight and tax. Record any confusing step; provider-dependent actions may remain blocked.'],
  ['Approvals','/admin/desk','Review the over-$10,000 approval workflow. Check that changing commercial details requires a fresh decision. A completed provider/payment test still requires sandbox credentials.'],
  ['Receiving and picking','/admin/inventory/receive','Walk through a test purchase order, partial receipt, lot/expiry and wrong-barcode case. Only use records explicitly marked TEST. Real opening stock stays provisional.'],
  ['Returns and recall','/admin/inventory/lots','Walk through quarantine, traceability and recall decisions. Note the expected owner and next action for each exception.'],
];
const CHATGPT_PROMPT='Help me test Unite Medical staging. Work through one workflow at a time: customers, historical orders, products/inventory, quotes, approvals, receiving/picking, returns/recall. Ask me what I expected and what actually happened. Separate bugs, confusing UX, missing data, unavailable integrations and business decisions. Turn my notes into: workflow, steps, expected result, actual result, impact, suggested fix. Do not mark a workflow passed without evidence. Do not include passwords, activation links, authenticator keys or customer/payment details. I will paste the resulting notes into the staging feedback page.';

export function AdminTesting(){
  useSEO({title:'Damon’s staging test',noindex:true});
  const [data,setData]=useState({feedback:[],imports:[]});const [workflow,setWorkflow]=useState(WORKFLOWS[0][0]);const [result,setResult]=useState('confusing');const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  useEffect(()=>{let active=true;fetch('/api/admin/testing',{credentials:'include'}).then(async r=>{if(!r.ok)throw new Error('Could not load saved feedback.');return r.json();}).then(x=>{if(active)setData(x);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/testing',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflow,result,notes})});if(!r.ok)throw new Error('Feedback did not save. Please retry.');const x=await r.json();setData(d=>({...d,feedback:[x.feedback,...d.feedback]}));setNotes('');setMessage('Feedback saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <AdminShell active="testing"><main className="um-workspace"><header><h1>Damon’s staging test</h1><p>Use this checklist to review the work and leave feedback for Alex. This is staging; it is not a go-live approval.</p></header>
    <section className="ws-card"><h2>Start here</h2><p>Your changes save to the staging database. Live payment, shipping and messaging providers are not configured here. Test with records named TEST. Imported customer pricing and stock require reconciliation before release.</p>{data.imports.map(x=><p key={x.id}><strong>Shopify snapshot:</strong> {x.summary?.products} products · {x.summary?.customers} customers · {x.summary?.orders} historical orders · {x.summary?.open_orders} open orders · {x.summary?.transactions} transactions.</p>)}</section>
    <section className="ws-card"><h2>Workflows to try</h2><ol className="ws-list">{WORKFLOWS.map(([name,path,steps])=><li key={name} style={{padding:'16px 0'}}><Link to={path}><strong>{name}</strong></Link><p>{steps}</p><button className="ws-button" onClick={()=>{setWorkflow(name);document.getElementById('test-feedback').scrollIntoView({behavior:'smooth'});}}>Record feedback</button></li>)}</ol></section>
    <section className="ws-card" id="test-feedback"><h2>What happened?</h2><form className="ws-stack" onSubmit={save}><label>Workflow<select value={workflow} onChange={e=>setWorkflow(e.target.value)}>{WORKFLOWS.map(([name])=><option key={name}>{name}</option>)}</select></label><label>Result<select value={result} onChange={e=>setResult(e.target.value)}><option value="confusing">Confusing / too many steps</option><option value="bug">Bug</option><option value="blocked">Blocked / missing data or integration</option><option value="passed">Passed</option></select></label><label>Notes<textarea required rows={6} maxLength={8000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What I tried → what I expected → what happened. Include the record reference and what should be simpler."/></label><button className="ws-button primary" disabled={busy}>{busy?'Saving…':'Save feedback'}</button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</form></section>
    <section className="ws-card"><h2>Use ChatGPT to organize your notes</h2><p>Copy this prompt into your ChatGPT, then describe what you see. Keep login links and customer details out of the conversation.</p><textarea readOnly rows={7} aria-label="ChatGPT testing prompt" value={CHATGPT_PROMPT} style={{width:'100%'}}/></section>
    <section className="ws-card"><h2>Saved feedback</h2>{!data.feedback.length?<p>No feedback recorded yet.</p>:data.feedback.map(f=><article key={f.id} style={{borderBottom:'1px solid #ddd',padding:'16px 0'}}><strong>{f.workflow} — {f.result}</strong><p style={{whiteSpace:'pre-wrap'}}>{f.notes}</p><small>{f.author} · {new Date(f.created_at).toLocaleString()}</small></article>)}</section>
  </main></AdminShell>;
}
