import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {stopRemoteDb} from '../../lib/remoteDb.js';
export function AdminWorkspaceReset(){
 const [plan,setPlan]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmation,setConfirmation]=useState(''),[result,setResult]=useState(null);
 async function load(){try{setPlan(await workspaceRequest('/api/admin/workspace-reset'));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{Promise.resolve().then(load);},[]);
 async function run(action,run_id){setBusy(true);setError('');try{const value=await postWorkspace('/api/admin/workspace-reset',{action,run_id,version:plan.version,confirmation});stopRemoteDb({purge:true});setResult(value);setConfirmation('');await load();}catch(e){await load();setError(e.message);}finally{setBusy(false);}}
 return <AdminShell active="workspace-reset"><main id="main" className="uw-workday"><header className="uw-day-heading"><div><h1>Launch workspace</h1><p>Start with an empty customer list, product catalog and inventory.</p></div><Link className="uw-button" to="/work">Back to Home</Link></header>{error&&<p className="uw-error" role="alert">{error}</p>}{result&&<p className="uw-notice" role="status">{result.archived!==undefined?`${result.archived.toLocaleString()} records cleared from the active workspace. Staff access and settings are preserved.`:`${result.restored.toLocaleString()} records restored.`} <a href="/work">Reload workspace</a></p>}
 <section className="uw-admin-card"><h2>Clear staging data</h2><p>This clears existing customers, products, inventory and related orders, quotes, tasks, test inquiries and imported history from the active workspace. Staff logins, permissions, warehouse locations, site content and connection settings stay in place.</p><p>Records are archived in place and can be restored below. No backup file is created. This does not change Shopify or send messages.</p>{!plan?<p>Loading records…</p>:<><strong>{plan.total.toLocaleString()} records · {plan.staff_preserved} staff accounts preserved</strong><details><summary>Review affected records</summary><table className="uw-reset-table"><thead><tr><th>Record type</th><th>Count</th></tr></thead><tbody>{Object.entries(plan.counts).map(([name,count])=><tr key={name}><td>{name.replaceAll('_',' ')}</td><td>{count.toLocaleString()}</td></tr>)}</tbody></table></details>{plan.blocked>0&&<p role="alert">{plan.blocked} records are on legal hold. The reset is blocked.</p>}<label className="uw-reset-confirm">Type CLEAR STAGING WORKSPACE to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label><button className="uw-button primary" disabled={busy||!plan.total||plan.blocked>0||confirmation!=='CLEAR STAGING WORKSPACE'} onClick={()=>run('archive')}>{busy?'Working…':'Clear staging workspace'}</button></>}</section>
 {plan?.history?.length>0&&<section className="uw-admin-card" style={{marginTop:20}}><h2>Reset history</h2>{plan.history.map(r=><div key={r.id} className="uw-reset-history"><span>{new Date(r.created_at).toLocaleString()} · {r.total.toLocaleString()} records · {r.status}</span>{r.status==='archived'&&<button className="uw-button" disabled={busy} onClick={()=>run('restore',r.id)}>Restore this reset</button>}</div>)}</section>}</main></AdminShell>;
}
