import {useDetailFocus} from '../../lib/useDetailFocus.js';
import {useCallback,useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {AccountsPayable} from '../../components/finance/AccountsPayable.jsx';
import {WorkspaceIcon} from '../../components/workspace/WorkspaceIcon.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {useSEO} from '../../lib/seo.js';
import '../../styles/workspace.css';
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const balance=r=>Number(r.balance??Math.max(0,Number(r.amount??r.total??0)-Number(r.paid_amount||0)));
const dateValue=value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')?new Date(`${value}T23:59:59`):new Date(value);
const late=r=>balance(r)>0&&dateValue(r.due_date).getTime()<Date.now();
function InvoiceReview({invoice,onRecorded,onStart,onDirtyChange}){
 const detailHeading=useDetailFocus(invoice.id);
 const [reference,setReference]=useState(''),[amount,setAmount]=useState(String(balance(invoice))),[method,setMethod]=useState('ach'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dirty=!!reference||amount!==String(balance(invoice))||method!=='ach';
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false);},[dirty,onDirtyChange]);
 async function submit(e){e.preventDefault();onStart();setBusy(true);setError('');try{const result=await postWorkspace('/api/finance/record-payment',{invoice_id:invoice.id,provider:'off_platform',payment_reference:reference,amount:Number(amount),method});await onRecorded(result);setReference('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="uw-detail"><span className="uw-eyebrow">Invoice review</span><h2 ref={detailHeading} tabIndex={-1} style={{scrollMarginTop:80}}>{invoice.id}</h2><p>{invoice.customer_name}</p><dl className="uw-facts">{[['Order',invoice.order_id],['Invoice total',money(invoice.amount??invoice.total)],['Recorded payments',money(invoice.paid_amount)],['Write-offs recorded',money(invoice.written_off_amount)],['Remaining balance',money(balance(invoice))],['Terms',invoice.terms],['Due',invoice.due_date?dateValue(invoice.due_date).toLocaleDateString():'Not recorded']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'Not recorded'}</dd></div>)}</dl>
 {invoice.status!=='paid'&&balance(invoice)>0&&<form className="uw-followup" onSubmit={submit}><h3>Record confirmed payment</h3><p>Use the bank or accounting reference for money already received. This records evidence; it does not charge the customer or send a reminder.</p><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="ach">ACH / bank transfer</option><option value="wire">Wire</option><option value="check">Deposited check</option></select></label><label>Bank or accounting reference<input required value={reference} onChange={e=>setReference(e.target.value)} maxLength={200}/></label><label>Confirmed amount<input required type="number" min="0.01" max={balance(invoice)} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label>{error&&<p role="alert" className="uw-error">{error}</p>}<button className="uw-button primary" disabled={busy||!reference.trim()}>{busy?'Recording…':'Record payment evidence'}</button>{dirty&&<button type="button" className="uw-button quiet" onClick={()=>{setReference('');setAmount(String(balance(invoice)));setMethod('ach');setError('');}}>Discard payment draft</button>}</form>}
 <p className="uw-notice">Damon deposits checks. Ashley verifies payments and reconciles QuickBooks. Other release and approval requirements still apply.</p><Link className="uw-button" to={`/invoices/${encodeURIComponent(invoice.id)}/print`}>Open invoice document ↗</Link></section>;
}
export function AdminFinance(){
 const [params,setParams]=useSearchParams();
 const [editing,setEditing]=useState(false);
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[section,setSection]=useState(params.get('section')==='ap'?'ap':'ar'),[filter,setFilter]=useState('open'),[search,setSearch]=useState(''),[selectedId,setSelectedId]=useState(params.get('invoice')||'');
 useSEO({title:'Finance · Team workspace',noindex:true});
 const load=useCallback(async signal=>{try{const b=await workspaceRequest('/api/finance/record-payment',{signal});setRows(b.invoices);setError('');}catch(e){if(!signal?.aborted)setError(e.message);}finally{if(!signal?.aborted)setLoading(false);}},[]);
 useEffect(()=>{const c=new AbortController();Promise.resolve().then(()=>{if(!c.signal.aborted)load(c.signal);});return()=>c.abort();},[load]);
 const open=rows.filter(r=>balance(r)>0&&!['paid','void','cancelled','refunded','written_off','settled'].includes(r.status)),overdue=open.filter(late),selected=rows.find(r=>r.id===selectedId);
 const visible=rows.filter(r=>(filter==='all'||filter==='open'&&open.includes(r)||filter==='overdue'&&overdue.includes(r)||filter==='paid'&&['paid','settled','written_off'].includes(r.status))&&`${r.id} ${r.customer_name} ${r.order_id}`.toLowerCase().includes(search.toLowerCase()));
 return <AdminShell active="finance" unsavedChanges={editing}><main id="main" className="uw-workday"><header className="uw-day-heading"><div><span className="uw-eyebrow">Finance</span><h1>Payments & billing.</h1><p>Review the balance, match the evidence, and keep the next step clear.</p></div><Link className="uw-button" to="/admin/refund-reviews">Refund reviews<WorkspaceIcon name="arrow" size={16}/></Link></header><nav className="uw-view-tabs" aria-label="Finance views">{[['ar','Customer invoices'],['ap','Supplier bills']].map(([id,label])=><button key={id} onClick={()=>{if(editing){setNotice('Save or discard your draft before changing finance views.');return;}setSection(id);setNotice('');}} aria-pressed={section===id}>{label}</button>)}</nav>{error&&<p role="alert" className="uw-error">Invoice data is unavailable. {error}<button onClick={()=>load()}>Retry</button></p>}{notice&&<p role="status" className="uw-notice">{notice}</p>}
 {section==='ap'?<AccountsPayable onDirtyChange={setEditing}/>:<><div className="uw-finance-metrics">{[['Open balance',money(open.reduce((s,r)=>s+balance(r),0))],['Overdue balance',money(overdue.reduce((s,r)=>s+balance(r),0))],['Invoices to review',open.length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{loading||error?'—':value}</strong></div>)}</div><div className={`uw-work-grid ${selected?'has-detail':''}`}><section className="uw-work-list"><div className="uw-queue-heading"><h2>Customer invoices</h2><label className="uw-search"><WorkspaceIcon name="search" size={16}/><input type="search" placeholder="Find customer or invoice" aria-label="Find an invoice" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="uw-queue-filters"><div>{[['open','Open'],['overdue','Overdue'],['paid','Settled'],['all','All']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div><button className="uw-button quiet" disabled={editing} onClick={()=>load()}>Refresh</button></div>{loading?<p className="uw-empty" role="status">Loading invoices…</p>:!visible.length?<p className="uw-empty">{error?'Could not load invoices.':'No invoices match this view.'}</p>:<ul className="uw-queue">{visible.map(r=><li key={r.id}><button className={`uw-work-row ${selectedId===r.id?'is-selected':''}`} aria-pressed={selectedId===r.id} onClick={()=>{if(editing&&r.id!==selectedId){setNotice('Save or discard your payment draft before opening another invoice.');return;}setSelectedId(r.id);setParams({invoice:r.id},{replace:true});}}><span className="uw-type-icon"><WorkspaceIcon name="money" size={18}/></span><span className="uw-row-copy"><strong>{r.customer_name}</strong><span className="uw-row-next">{r.id} · {r.order_id||'Order not recorded'}</span></span><span className="uw-row-state"><strong>{money(balance(r))}</strong><span className={`uw-badge ${late(r)?'is-overdue':''}`}>{r.status==='written_off'?'Written off':r.status==='settled'?'Settled with write-off':r.status==='paid'?'Paid':late(r)?'Overdue':'Open'}</span></span><WorkspaceIcon name="arrow" size={16}/></button></li>)}</ul>}</section>{selected&&<InvoiceReview onDirtyChange={setEditing} key={`${selected.id}:${selected.paid_amount||0}`} invoice={selected} onStart={()=>setNotice('')} onRecorded={async result=>{setNotice(result.duplicate?'This payment reference was already recorded. No additional payment was added.':'Payment evidence saved. Review any remaining order holds before release.');await load();}}/>}</div></>}
 </main></AdminShell>;
}
