import {useEffect,useState} from 'react';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {useSEO} from '../../lib/seo.js';
import '../../styles/workspace.css';
export function AdminDocuments(){
 useSEO({title:'Document review',noindex:true});const [docs,setDocs]=useState([]),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function refresh(){const r=await workspaceRequest('/api/admin/documents');setDocs(r.documents);}
 useEffect(()=>{let active=true;workspaceRequest('/api/admin/documents').then(r=>{if(active)setDocs(r.documents);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function action(type){setBusy(true);setError('');setMessage('');try{await postWorkspace(type==='process'?'/api/admin/documents':'/api/admin/tax-certificates',{version_id:selected.id,action:type,reason});await refresh();setSelected(null);setReason('');setMessage(type==='process'?'Processing completed. Review the extracted evidence.':'Review saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <AdminShell active="documents"><main id="main" className="um-workspace"><header className="ws-header"><div><h1>Document review</h1><p>Scan the file, check its evidence, then record your review.</p></div></header>{error&&<div className="ws-error" role="alert">{error}</div>}{message&&<p role="status" className="ws-note">{message}</p>}<div className="ws-split"><section className="ws-card"><h2>Tax certificates</h2>{!docs.length&&<p>No documents loaded.</p>}<ul className="ws-list">{docs.map(d=><li className="ws-row" key={d.id}><div><strong>{d.org_id}</strong><p>{d.review_status} · {d.scan_status}</p><span className="ws-muted">{new Date(d.uploaded_at).toLocaleDateString()}</span></div><button className="ws-button" onClick={()=>{setSelected(d);setReason('');}}>Review</button></li>)}</ul><p>Showing up to 200 recently updated documents.</p></section>{selected&&<section className="ws-card"><h2>Review certificate</h2><p>{selected.org_id}</p><button className="ws-button" disabled={busy} onClick={()=>action('process')}>{busy?'Working…':'Scan and extract fields'}</button><p>Files remain quarantined until the configured scanner returns clean evidence. Extraction flags require human review.</p>{selected.scan_status==='clean'&&<a className="ws-button" href={`/api/admin/documents?version_id=${encodeURIComponent(selected.id)}`}>Download scanned original</a>}<dl>{Object.entries(selected.extracted_fields||{}).map(([k,v])=><div key={k} className="ws-row"><dt>{k.replaceAll('_',' ')}</dt><dd style={{overflowWrap:'anywhere'}}>{String(v??'Not found')}</dd></div>)}</dl>{selected.review_flags?.length>0&&<p className="ws-note">Review: {selected.review_flags.join(', ').replaceAll('_',' ')}</p>}<label>Review reason and evidence<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="ws-actions"><button className="ws-button primary" disabled={busy||!reason.trim()||selected.scan_status!=='clean'} onClick={()=>action('approve')}>Approve documentation</button><button className="ws-button" disabled={busy||!reason.trim()} onClick={()=>action('reject')}>Reject documentation</button></div><p>This review does not automatically change a preserved Shopify exemption or block checkout.</p></section>}</div><RetentionControls/></main></AdminShell>;
}
function RetentionControls(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[reason,setReason]=useState(''),[table,setTable]=useState('documents'),[record,setRecord]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setData(await workspaceRequest('/api/admin/retention'));}catch(e){setError(e.message);}}
 async function update(action,id){setBusy(true);setError('');try{await postWorkspace('/api/admin/retention',{action,id,table,record_id:record||null,reason});setReason('');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <details className="ws-card"><summary>Retention and legal holds</summary><p>Operational records have a three-year minimum. Legal holds and longer recorded requirements take precedence. Generic sync cannot delete operational history.</p><button className="ws-button" onClick={load}>Load holds</button>{error&&<p className="ws-error" role="alert">{error}</p>}{data&&<><label>Record class<select value={table} onChange={e=>setTable(e.target.value)}>{data.tables.map(t=><option key={t}>{t}</option>)}<option value="*">All classes</option></select></label><label>Record ID (blank holds the whole class)<input value={record} onChange={e=>setRecord(e.target.value)}/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="ws-button" disabled={busy||!reason.trim()} onClick={()=>update('hold')}>Place hold</button><ul>{data.holds.map(h=><li key={h.id}>{h.table} · {h.record_id||'All records'} · {h.status} · {h.reason}{h.status==='active'&&<button className="ws-button" disabled={busy||!reason.trim()} onClick={()=>update('release',h.id)}>Release with stated reason</button>}</li>)}</ul></>}</details>;
}
