import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {useSEO} from '../../lib/seo.js';
import '../../styles/workspace.css';
export function AdminDesk(){
 useSEO({title:'Needs attention',noindex:true});const [rows,setRows]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('escalated'),[selected,setSelected]=useState(null);
 async function refresh(){setBusy(true);setError('');try{const r=await workspaceRequest('/api/admin/operations');setRows(r.exceptions);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{let active=true;workspaceRequest('/api/admin/operations').then(r=>{if(active)setRows(r.exceptions);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await postWorkspace('/api/admin/operations',selected);setSelected(null);await refresh();}catch(err){setError(err.message);}finally{setBusy(false);}}
 const visible=rows.filter(r=>filter==='all'||r.escalated||r.owner_email?.toLowerCase()==='damon@unitemedical.net');
 return <AdminShell active="desk"><main id="main" className="um-workspace"><header className="ws-header"><div><h1>Needs attention</h1><p>Decisions, overdue work and customers waiting for a response.</p></div><button className="ws-button" disabled={busy} onClick={refresh}>Refresh</button></header>{error&&<div className="ws-error" role="alert">{error} Connect the staging services to load operational work.</div>}<div className="ws-actions"><button className="ws-button" onClick={()=>setFilter('escalated')} aria-pressed={filter==='escalated'}>Needs Damon ({rows.filter(r=>r.escalated||r.owner_email?.toLowerCase()==='damon@unitemedical.net').length})</button><button className="ws-button" onClick={()=>setFilter('all')} aria-pressed={filter==='all'}>All open work ({rows.length})</button></div>
 <section className="ws-card" style={{marginTop:24}}>{!visible.length?<p className="ws-empty">{error?'Operational data is unavailable.':'No matching exceptions loaded.'}</p>:<ul className="ws-list">{visible.map(r=><li key={r.id} className="ws-row"><div><h2>{r.title}</h2><p>{r.customer_name} · {r.customer_impact}</p><p><strong>{r.owner_email||'No owner assigned'}</strong> · Due {new Date(r.due_at).toLocaleString()}</p><p>{r.next_action}</p></div><div className="ws-actions"><Link className="ws-button primary" to={r.path}>Open workflow</Link><button className="ws-button" onClick={()=>setSelected({...r,owner_email:r.owner_email||'',notes:r.notes||''})}>Assign / update</button></div></li>)}</ul>}</section>
 {selected&&<section className="ws-card" aria-label="Update exception"><h2>{selected.title}</h2><form onSubmit={save}><label>Owner email<input type="email" required value={selected.owner_email} onChange={e=>setSelected({...selected,owner_email:e.target.value})}/></label><label>Due time (UTC)<input type="datetime-local" required value={selected.due_at.slice(0,16)} onChange={e=>setSelected({...selected,due_at:e.target.value+'Z'})}/></label><label>Next action<input required value={selected.next_action} onChange={e=>setSelected({...selected,next_action:e.target.value})}/></label><label>Progress / evidence<textarea value={selected.notes} onChange={e=>setSelected({...selected,notes:e.target.value})}/></label><p>The exception closes when the underlying workflow is resolved. Sending a message alone does not close it.</p><div className="ws-actions"><button className="ws-button primary" disabled={busy}>Save assignment</button><button type="button" className="ws-button" onClick={()=>setSelected(null)}>Cancel</button></div></form></section>}
 </main></AdminShell>;
}
