import {useEffect,useRef,useState} from 'react';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {useSEO} from '../../lib/seo.js';
import {WORKFLOW_REVIEW,REVIEW_RESULT_LABELS} from '../../lib/workflowReview.js';
import '../../styles/workspace.css';
import '../../styles/workflow-review.css';

export function AdminTesting(){
 useSEO({title:'Workflow review · Unite team',noindex:true});
 const [feedback,setFeedback]=useState([]),[selected,setSelected]=useState(WORKFLOW_REVIEW[0].id),[owner,setOwner]=useState('Everyone'),[result,setResult]=useState(''),[notes,setNotes]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const detail=useRef(null),active=WORKFLOW_REVIEW.find(w=>w.id===selected);
 const latest=new Map();for(const item of feedback){if(!latest.has(item.workflow))latest.set(item.workflow,item);}
 const filtered=WORKFLOW_REVIEW.filter(w=>owner==='Everyone'||w.owner===owner||w.owner==='Everyone');
 const passed=WORKFLOW_REVIEW.filter(w=>latest.get(w.name)?.result==='passed').length;
 const reviewed=WORKFLOW_REVIEW.filter(w=>latest.has(w.name)).length;
 const current=latest.get(active.name),dirty=Boolean(notes.trim()||result);
 useEffect(()=>{const controller=new AbortController();fetch('/api/admin/testing',{credentials:'include',signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Could not load saved feedback. Refresh to try again.');return r.json();}).then(x=>{if(!controller.signal.aborted)setFeedback(x.feedback||[]);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 function choose(id){if(dirty){setError('Save this observation or discard the draft before choosing another workflow.');return;}setSelected(id);setError('');setMessage('');if(window.matchMedia('(max-width: 1000px)').matches||detail.current?.getBoundingClientRect().top<88)requestAnimationFrame(()=>detail.current?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));}
 async function save(e){e.preventDefault();if(busy)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/testing',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflow:active.name,result,notes})});const x=await r.json();if(!r.ok||!x.feedback)throw new Error('Feedback did not save. Your draft is still here; please retry.');setFeedback(old=>[x.feedback,...old]);setNotes('');setResult('');setMessage('Observation saved. Choose the next workflow when you are ready.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 function download(){const payload={exported_at:new Date().toISOString(),environment:'staging',reviewed,passed,total:WORKFLOW_REVIEW.length,workflows:WORKFLOW_REVIEW.map(w=>({...w,latest_observation:latest.get(w.name)||null})),feedback};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`unite-workflow-review-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <AdminShell active="testing" unsavedChanges={dirty}><main id="main" className="um-workspace review-page">
  <header className="review-heading"><div><p className="uw-eyebrow">Damon & Alex · Staging review</p><h1>Walk through the work.</h1><p>One workflow at a time. Open it, try the steps, and record what actually happened.</p></div><button className="uw-button" disabled={loading} onClick={download}>Download review ↓</button></header>
  <div className="review-summary"><div><strong>{reviewed} / {WORKFLOW_REVIEW.length}</strong><span>workflows reviewed</span></div><div><strong>{passed}</strong><span>latest results passed</span></div><p>Start with the customer-to-shipment path. Use each person’s own login for role checks; Damon’s access alone does not verify theirs.</p></div>
  <details className="review-safety"><summary>Before you start</summary><p>This is the staging database, not an isolated sandbox. Use records explicitly designated for testing. Messaging, payment, and shipping providers may be live: do not send, charge, purchase labels, or move real inventory as part of the walkthrough. A TEST name does not disable integrations.</p><p>Provider tests and unavailable operations should be recorded as blocked until the required sandbox, records, or reconciliation is ready.</p></details>
  {error&&<div role="alert" className="uw-error">{error}</div>}
  {message&&<div role="status" className="review-saved">{message}</div>}
  <div className="review-layout"><aside className="review-index" aria-label="Workflow checklist"><label>Review by person<select value={owner} onChange={e=>setOwner(e.target.value)}>{['Everyone','Damon','Jacobe','Ashley','Darren'].map(name=><option key={name}>{name}</option>)}</select></label><nav aria-label="Choose a workflow">{filtered.map(w=>{const observation=latest.get(w.name);return <button key={w.id} aria-current={selected===w.id?'step':undefined} onClick={()=>choose(w.id)}><span className={`review-dot ${observation?.result||''}`}>{observation?.result==='passed'?'✓':WORKFLOW_REVIEW.indexOf(w)+1}</span><span><strong>{w.name}</strong><small>{w.owner} · {observation?REVIEW_RESULT_LABELS[observation.result]:'Not reviewed'}</small></span></button>;})}</nav></aside>
  <section ref={detail} className="review-detail" aria-labelledby="review-title"><div className="review-detail-head"><span>{active.owner} <span> / </span> {active.mode}</span><h2 id="review-title">{active.name}</h2><a className="uw-button primary" href={active.path} target="_blank" rel="noopener noreferrer">Open workflow ↗</a><p>Opens in another tab so your checklist stays here. Test using the role named above.</p></div>
   <ol className="review-steps">{active.steps.map((step,i)=><li key={step}><span>{i+1}</span><p>{step}</p></li>)}</ol><div className="review-expected"><strong>What a good result looks like</strong><p>{active.expected}</p></div>
   {current&&<div className="review-previous"><strong>Last observation · {REVIEW_RESULT_LABELS[current.result]}</strong><p>{current.notes}</p><small>{current.author} · {new Date(current.created_at).toLocaleString()}</small></div>}
   <form className="review-form" onSubmit={save}><h3>Record your observation</h3><label>Result<select required disabled={busy||loading} value={result} onChange={e=>setResult(e.target.value)}><option value="">Choose what happened…</option>{Object.entries(REVIEW_RESULT_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>What did you test?<textarea required disabled={busy||loading} rows={5} maxLength={8000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Steps tried · test record reference · expected vs actual result · anything that should be easier"/></label><p>Include enough detail to repeat the test. Leave out passwords, payment details, and private customer information.</p><div className="review-form-actions">{dirty&&<button type="button" className="uw-button" disabled={busy} onClick={()=>{setNotes('');setResult('');setError('');}}>Discard draft</button>}<button className="uw-button primary" disabled={busy||loading||!result||!notes.trim()}>{busy?'Saving…':'Save observation'}</button></div></form>
   <div className="review-next"><span>{WORKFLOW_REVIEW.indexOf(active)+1} of {WORKFLOW_REVIEW.length}</span><button className="uw-button" disabled={busy||WORKFLOW_REVIEW.indexOf(active)===WORKFLOW_REVIEW.length-1} onClick={()=>choose(WORKFLOW_REVIEW[WORKFLOW_REVIEW.indexOf(active)+1].id)}>Next workflow →</button></div>
  </section></div>
  <p className="review-footnote">Recorded observations support acceptance review. They do not activate ordering, reconcile opening balances, or approve a production cutover.</p>
 </main></AdminShell>;
}
