import { useState } from 'react';
import { AdminShell } from '../../components/layout/AdminShell.jsx';
import readiness from '../../data/barcodeReadiness.generated.json';
import { D } from '../../tokens.js';

export function AdminBarcodes(){
 const queue=readiness.queue;const registry={variant_count:readiness.summary.variants,identifiers:{length:readiness.summary.mapped},missing:{length:readiness.summary.missing},conflicts:readiness.conflicts};const [filter,setFilter]=useState('launch_operational');const rows=filter==='all'?queue:queue.filter((row)=>row.priority===filter);
 return <AdminShell active="barcodes"><main style={{padding:40,maxWidth:1320}}><p style={{fontFamily:D.mono,fontSize:11,letterSpacing:1.2,color:D.plum}}>WAREHOUSE · BARCODE READINESS</p><h1 style={{fontFamily:D.display,fontWeight:400,fontSize:48,margin:'8px 0'}}>Barcode work queue</h1><p style={{maxWidth:800,color:D.ink2}}>Conflicting codes fail closed. Missing codes do not receive stock until a manufacturer mapping or approved internal label is recorded.</p><div style={{display:'flex',gap:12,margin:'24px 0',flexWrap:'wrap'}}>{[['Variants',registry.variant_count],['Mapped',registry.identifiers.length],['Missing',registry.missing.length],['Conflicts',registry.conflicts.length],['Launch + stock priority',queue.filter((r)=>r.priority==='launch_operational').length]].map(([label,value])=><div key={label} style={{border:`1px solid ${D.line}`,padding:'14px 18px',borderRadius:6,minWidth:140}}><div style={{fontSize:11,color:D.ink2}}>{label}</div><strong style={{fontSize:26}}>{value}</strong></div>)}</div><div style={{display:'flex',gap:8,marginBottom:16}}>{['launch_operational','launch_no_stock','not_launching','all'].map((key)=><button key={key} onClick={()=>setFilter(key)} style={{padding:'9px 12px',border:`1px solid ${D.line}`,background:filter===key?D.plum:D.card,color:filter===key?D.paper:D.ink,borderRadius:4}}>{key.replaceAll('_',' ')}</button>)}</div><div style={{border:`1px solid ${D.line}`,borderRadius:8,overflow:'hidden'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr style={{background:D.paperAlt,textAlign:'left'}}><th style={{padding:12}}>PRIORITY</th><th style={{padding:12}}>SKU</th><th style={{padding:12}}>PRODUCT</th><th style={{padding:12}}>VARIANT</th><th style={{padding:12}}>ACTION</th></tr></thead><tbody>{rows.map((row)=><tr key={row.product_handle+row.sku+row.variant_title} style={{borderTop:`1px solid ${D.line}`}}><td style={{padding:12}}>{row.priority.replaceAll('_',' ')}</td><td style={{padding:12,fontFamily:D.mono}}>{row.sku||'NO SKU'}</td><td style={{padding:12}}>{row.product_name}</td><td style={{padding:12}}>{row.variant_title}</td><td style={{padding:12}}>Scan manufacturer code or issue internal label</td></tr>)}</tbody></table></div>{registry.conflicts.length>0&&<section style={{marginTop:30}}><h2>Cross-SKU conflicts</h2>{registry.conflicts.map((row)=><p key={row.value}><code>{row.value}</code> → {row.skus.join(', ')}</p>)}</section>}</main></AdminShell>;
}
