import {useState} from 'react';
import {Link} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {WorkspaceIcon} from '../../components/workspace/WorkspaceIcon.jsx';
import {useSEO} from '../../lib/seo.js';
import {db} from '../../lib/db.js';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
export function AdminProducts(){
 useSEO({title:'Products · Unite workspace',noindex:true});
 const products=db.useTable('products'),inventory=db.useTable('inventory');
 const [search,setSearch]=useState(''),[category,setCategory]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState('name');
 const categories=[...new Set(products.map(p=>p.category).filter(Boolean))].sort();
 const shown=products.filter(p=>(!category||p.category===category)&&(filter==='all'||(filter==='active'?p.available!==false:p.available===false))&&`${p.name} ${p.sku} ${p.vendor||''} ${(p.variants||[]).map(v=>`${v.sku} ${v.title}`).join(' ')}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:String(a.name).localeCompare(String(b.name)));
 const pilot=products.some(p=>p.test_batch);
 return <AdminShell active="products"><main id="main" className="uw-workday"><header className="uw-day-heading"><div><div className="uw-eyebrow">Catalog</div><h1>Products <span className="uw-heading-count">{products.length}</span></h1><p>Everything you sell, with its variants and inventory in one place.</p></div><div className="uw-inventory-actions"><Link className="uw-button" to="/admin/test-data"><WorkspaceIcon name="upload" size={15}/>Test data</Link><Link className="uw-button primary" to="/admin/products/new">+ Add product</Link></div></header>
 {pilot&&<p className="uw-notice">Test catalog from September 8 · Prices and stock are for staging checks. Physical inventory is still pending.</p>}
 <section className="uw-work-list"><div className="uw-queue-heading"><div className="uw-type-filters" role="group" aria-label="Product views">{[['all','All products'],['active','Available'],['hidden','Hidden']].map(([id,label])=><button key={id} onClick={()=>setFilter(id)} aria-pressed={filter===id}>{label}</button>)}</div><Link className="uw-button quiet" to="/admin/launch">Check CSV files<WorkspaceIcon name="arrow" size={14}/></Link></div>
 <div className="uw-catalog-toolbar"><label className="uw-search"><WorkspaceIcon name="search" size={16}/><input type="search" aria-label="Search products" placeholder="Search products, variants or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Product category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name, A–Z</option><option value="price">Price, low to high</option></select></div>
 {!products.length?<div className="uw-empty"><WorkspaceIcon name="box" size={36}/><h3>A clean slate for your catalog</h3><p>Start with the reviewed Shopify batch to test search, product details and variants.</p><Link className="uw-button primary" to="/admin/test-data">Review test catalog<WorkspaceIcon name="arrow" size={15}/></Link></div>:<><div className="um-scroll-x"><table className="uw-catalog-table"><thead><tr><th>Product</th><th>Status</th><th>Inventory</th><th>Category</th><th>Price</th></tr></thead><tbody>{shown.map(p=>{
 const variants=p.variants?.length?p.variants:[p],skus=new Set(variants.map(v=>v.sku)),stock=inventory.filter(i=>skus.has(i.sku)&&(i.inventory_owner_type||'unite')==='unite'&&!i.inventory_owner_org_id),available=stock.reduce((sum,r)=>sum+Number(r.on_hand||0)-Number(r.reserved||0),0),image=p.hero_image||p.images?.[0];
 return <tr key={p.id}><td><Link to={`/admin/products/edit/${encodeURIComponent(p.id)}`} className="uw-product-cell"><span className="uw-product-thumb">{image?<img src={image} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none';}}/>:<WorkspaceIcon name="box" size={18}/>}</span><span><strong>{p.name}</strong><small>{p.sku} · {variants.length} {variants.length===1?'variant':'variants'}</small></span></Link></td><td><span className={`uw-badge ${p.available!==false?'is-success':''}`}>{p.available!==false?'Available':'Hidden'}</span></td><td>{stock.length?`${available.toLocaleString()} available`:'Not loaded'}{stock.length>0&&stock.length<variants.length&&<small className="uw-cell-note">{variants.length-stock.length} variants need review</small>}</td><td>{p.category||'Uncategorized'}</td><td className="uw-nowrap">{money(p.price_min??p.price)}{p.price_max>p.price_min?' +':''}</td></tr>;
 })}</tbody></table></div>{!shown.length&&<div className="uw-empty"><h3>No matching products</h3><p>Try a different name, SKU or category.</p><button className="uw-button" onClick={()=>{setSearch('');setCategory('');setFilter('all');}}>Clear filters</button></div>}<div className="uw-table-foot">{shown.length} of {products.length} products · Select a product to view its details</div></>}
 </section></main></AdminShell>;
}
