import {useEffect,useRef,useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {Card,Modal,Address,Badge} from '../../components/commerce/CommerceUI.jsx';
import {useCommerce} from '../../lib/useCommerce.js';
import {commerceRequest,money} from '../../lib/commerceClient.js';
import '../../styles/commerce-workspace.css';
import '../../styles/commerce-order-create.css';
import {draftRequest} from '../../lib/adminOrderClient.js';
const addressFields=[['recipient','Name'],['company','Company'],['address1','Address'],['address2','Apartment, suite, etc.'],['city','City'],['province','State / province'],['zip','ZIP / postal code'],['country','Country code'],['phone','Phone']];
const emptyDraft=customer=>({id:crypto.randomUUID(),customer_id:customer||'',lines:[],shipping:0,tax:0,discount_percent:0,shipping_confirmed:false,tax_confirmed:false,shipping_address:{country:'US'},billing_address:{country:'US'},payment_method:'due_on_receipt',notes:'',tags:[],po_number:''});
export function CommerceOrderCreate(){
 const [params]=useSearchParams(),nav=useNavigate(),[draft,setDraft]=useState(()=>emptyDraft(params.get('customer'))),[revision,setRevision]=useState(0),[customer,setCustomer]=useState(null),[modal,setModal]=useState(''),[quote,setQuote]=useState(null),[quoteBusy,setQuoteBusy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(!params.get('draft'));
 const dirty=useRef(false),saveLock=useRef(false);const draftId=params.get('draft');
 useEffect(()=>{let active=true;if(!draftId)return;fetch('/api/admin/order-drafts?id='+encodeURIComponent(draftId),{credentials:'include'}).then(r=>r.json()).then(data=>{if(!active)return;if(!data.data)throw new Error(data.error||'Draft unavailable.');if(!data.data.draft){nav('/admin/orders/'+draftId,{replace:true});return;}setDraft({...data.data,lines:data.data.lines.map(l=>({...l,unit_price:l.requested_unit_price??l.unit_price}))});setRevision(data.data.revision);setLoaded(true);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[draftId,nav]);
 useEffect(()=>{let active=true;if(!draft.customer_id)return;commerceRequest({kind:'customers',id:draft.customer_id}).then(r=>{if(!active)return;setCustomer(r.data);if(!draftId&&!dirty.current){const address=r.data.addresses?.find(a=>a.is_default)||r.data.addresses?.[0]||{country:'US'};setDraft(d=>({...d,shipping_address:address,billing_address:address,payment_method:/^net/.test(r.data.terms)?r.data.terms:'due_on_receipt'}));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[draft.customer_id,draftId]);
 useEffect(()=>{if(!loaded)return;let active=true;const timer=setTimeout(()=>{setQuoteBusy(true);draftRequest('preview',draft,revision).then(data=>{if(active){setQuote(data);setError('');}}).catch(e=>{if(active){setQuote(null);setError(e.message);}}).finally(()=>{if(active)setQuoteBusy(false);});},250);return()=>{active=false;clearTimeout(timer);};},[draft,revision,loaded]);
 useEffect(()=>{function guard(e){if(dirty.current){e.preventDefault();e.returnValue='';}}window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[]);
 function change(patch){dirty.current=true;setQuoteBusy(true);setNotice('');setDraft(d=>({...d,...(('lines' in patch||'shipping_address' in patch||'discount_percent' in patch)?{tax_confirmed:customer?.tax_exempt===true}:{}),...patch}));}
 function selectCustomer(c){const address=c.addresses?.find(a=>a.is_default)||c.addresses?.find(a=>!a.archived)||{country:'US'};setCustomer(c);change({customer_id:c.id,shipping_address:address,billing_address:address,payment_method:/^net/.test(c.terms)?c.terms:'due_on_receipt',tax_confirmed:c.tax_exempt===true,tax:0});setModal('');}
 async function save(action){if(saveLock.current)return;saveLock.current=true;setBusy(true);setError('');try{const result=await draftRequest(action,draft,revision);dirty.current=false;setRevision(result.data.revision);setModal('');window.dispatchEvent(new CustomEvent('unite-records-changed'));if(action==='submit'){nav('/admin/orders/'+result.data.id);return;}setNotice('Draft saved');if(!draftId)nav('/admin/orders/new?draft='+result.data.id,{replace:true});}catch(e){setError(e.message);}finally{setBusy(false);saveLock.current=false;}}
 const totals=quote?.data,issues=quote?.issues||[],disabled=busy||quoteBusy||!quote;
 return <AdminShell active="orders"><main id="main" className="cw-page co-create"><div className="cw-heading"><div className="cw-title"><Link className="cw-back" to="/admin/orders" aria-label="Back to orders">←</Link><h1>{draftId?'Edit draft order':'Create order'}</h1><Badge>Draft</Badge></div><div className="cw-actions"><Link className="cw-button" to="/admin/orders">Cancel</Link><button disabled={disabled} onClick={()=>save('save')}>{busy?'Saving…':'Save draft'}</button></div></div>{error&&<p className="cw-error" role="alert">{error}</p>}{notice&&<p className="co-success" role="status">{notice}</p>}
 <div className="cw-columns"><div className="cw-primary-col"><Card title="Products"><div className="co-product-search"><button className="co-search-trigger" onClick={()=>setModal('products')}>⌕ <span>Search products by name or SKU</span></button><button onClick={()=>setModal('products')}>Browse</button></div>{draft.lines.length?<div className="co-line-list"><div className="co-line-heading"><span>Product</span><span>Quantity</span><span>Total</span><span/></div>{draft.lines.map((line,index)=>{const priced=totals?.lines.find(l=>l.id===line.id);return <div className="co-line" key={line.id}><div className="co-product"><img src={line.image||'/brand/unite-medical-icon.png'} alt=""/><div><strong>{line.name}</strong><small>{line.variant} · {line.sku}</small><button className="cw-text-button" onClick={()=>setModal({type:'price',line,index})}>{money(priced?.unit_price??line.unit_price)}</button><small className="co-price-source">{priced?.pricing_source||'Checking price…'}</small></div></div><input aria-label={'Quantity for '+line.name} type="number" min="1" max="100000" value={line.quantity} onChange={e=>change({lines:draft.lines.map((l,i)=>i===index?{...l,quantity:e.target.value}:l)})}/><strong>{money(priced?.ext_price??line.quantity*line.unit_price)}</strong><button aria-label={'Remove '+line.name} className="cw-icon-button" onClick={()=>change({lines:draft.lines.filter((_,i)=>i!==index)})}>×</button></div>;})}</div>:<div className="co-product-empty">Search or browse your catalog to add products.</div>}{customer&&draft.lines.length>0&&<p className="cw-muted">Customer pricing applies automatically at each quantity.</p>}</Card>
 <Card title="Payment"><dl className="cw-totals"><div><dt>Subtotal <small>{draft.lines.reduce((n,l)=>n+Number(l.quantity||0),0)} items</small></dt><dd>{money(totals?.subtotal||0)}</dd></div><div><dt><button className="cw-text-button" onClick={()=>setModal('discount')}>{Number(draft.discount_percent)?'Edit discount':'Add discount'}</button></dt><dd>{Number(draft.discount_percent)?draft.discount_percent+'%':'—'}</dd></div><div><dt><button className="cw-text-button" onClick={()=>setModal('shipping')}>{draft.shipping_confirmed?'Edit shipping':'Add shipping'}</button><small>{draft.shipping_name}</small></dt><dd>{draft.shipping_confirmed?money(draft.shipping):'Not set'}</dd></div><div><dt><button className="cw-text-button" onClick={()=>setModal('tax')}>{customer?.tax_exempt?'Tax exempt':'Review tax'}</button></dt><dd>{customer?.tax_exempt?money(0):draft.tax_confirmed?money(draft.tax):'Not reviewed'}</dd></div><div className="total"><dt>Total</dt><dd>{money(totals?.total||0)} <small>USD</small></dd></div></dl><div className="co-payment-terms"><label className="cw-label">Payment terms<select value={draft.payment_method} onChange={e=>change({payment_method:e.target.value})}><option value="due_on_receipt">Payment due on receipt</option><option value="ach">Bank transfer / ACH</option><option value="card">Credit card — payment review</option>{['net15','net30','net60'].map(t=><option value={t} key={t} disabled={customer?.terms!==t}>{t.replace('net','Net ')}{customer?.terms!==t?' · approval needed':''}</option>)}</select></label><p className="cw-muted">Creating an order adds it to QuickBooks sync, payment review and fulfillment. Payment collection and customer emails are separate actions.</p></div><div className="co-payment-actions"><button disabled={disabled} onClick={()=>save('save')}>Save draft</button><button className="primary" disabled={disabled||issues.length>0} onClick={()=>setModal('review')}>Create order</button></div>{issues.length>0&&<ul className="co-issues">{issues.map(i=><li key={i}>{i}</li>)}</ul>}</Card></div>
 <aside className="cw-secondary-col"><Card title="Customer" action={customer&&<button className="cw-text-button" onClick={()=>setModal('customer')}>Change</button>}>{customer?<><Link to={'/admin/customers/'+customer.id}>{customer.name}</Link><p>{customer.company}</p><h3>Contact information</h3><p>{customer.email||'No email address'}</p><p>{customer.phone}</p><div className="co-address-heading"><h3>Shipping address</h3><button className="cw-text-button" onClick={()=>setModal({type:'address',field:'shipping_address'})}>Edit</button></div><Address address={draft.shipping_address}/><button className="cw-text-button co-address-book" onClick={()=>setModal('addresses')}>Choose saved address ({customer.addresses?.filter(a=>!a.archived).length||0})</button><div className="co-address-heading"><h3>Billing address</h3><button className="cw-text-button" onClick={()=>setModal({type:'address',field:'billing_address'})}>Edit</button></div><Address address={draft.billing_address}/><h3>Tax details</h3><p>{customer.tax_exempt?'Tax exempt':'Collect tax'}</p></>:<button className="co-search-trigger" onClick={()=>setModal('customer')}>⌕ Search or choose a customer</button>}</Card>
 <Card title="Notes"><textarea aria-label="Order notes" placeholder="Add a note…" rows={4} value={draft.notes} onChange={e=>change({notes:e.target.value})}/></Card><Card title="Purchase order"><input aria-label="Purchase order number" placeholder="PO number" value={draft.po_number} onChange={e=>change({po_number:e.target.value})}/></Card><Card title="Tags"><input aria-label="Order tags" placeholder="Separate tags with commas" value={draft.tags.join(', ')} onChange={e=>change({tags:e.target.value.split(',')})}/></Card></aside></div>
 {modal==='customer'&&<CustomerPicker onClose={()=>setModal('')} onSelect={selectCustomer}/>}
 {modal==='products'&&<ProductPicker selected={draft.lines} onClose={()=>setModal('')} onAdd={products=>{change({lines:[...draft.lines,...products.map(p=>({id:crypto.randomUUID(),product_id:p.id,sku:p.sku,name:p.name,variant:p.variant,image:p.image,quantity:1,unit_price:p.retail,manual_price:false}))]});setModal('');}}/>}
 {modal==='addresses'&&<Modal title="Choose shipping address" onClose={()=>setModal('')}><div className="cw-form co-address-list">{customer?.addresses?.filter(a=>!a.archived).map(a=><button key={a.id} onClick={()=>{change({shipping_address:a});setModal('');}}><Address address={a}/>{a.is_default&&<Badge>Default</Badge>}</button>)}</div><footer><button onClick={()=>setModal({type:'address',field:'shipping_address'})}>Use a new address</button></footer></Modal>}
 {modal?.type==='address'&&<AddressEditor address={draft[modal.field]} title={modal.field==='shipping_address'?'Edit shipping address':'Edit billing address'} onClose={()=>setModal('')} onSave={a=>{change({[modal.field]:a});setModal('');}}/>}
 {modal==='shipping'&&<SimpleFields title="Shipping" initial={{shipping_name:draft.shipping_name||'Custom shipping',shipping:draft.shipping}} fields={[['shipping_name','Shipping service','text'],['shipping','Shipping charge (USD)','number']]} onClose={()=>setModal('')} onSave={v=>{change({...v,shipping_confirmed:true});setModal('');}} note="Enter the agreed shipping charge. Enter 0 only for free shipping or pickup."/>}
 {modal==='tax'&&<SimpleFields title="Review tax" initial={{tax:customer?.tax_exempt?0:draft.tax,tax_note:draft.tax_note||''}} fields={[['tax','Tax amount (USD)','number'],['tax_note','Tax calculation or exemption reference','text']]} onClose={()=>setModal('')} onSave={v=>{change({...v,tax_confirmed:true});setModal('');}} note={customer?.tax_exempt?'This customer is tax exempt. The order tax will remain $0.':'Confirm the tax for this order and shipping address before creating the order.'}/>}
 {modal==='discount'&&<SimpleFields title="Add order discount" initial={{discount_percent:draft.discount_percent}} fields={[['discount_percent','Discount (%)','number']]} onClose={()=>setModal('')} onSave={v=>{change(v);setModal('');}} note="Discounts are checked against your pricing authority and verified product costs."/>}
 {modal?.type==='price'&&<SimpleFields title="Edit unit price" initial={{unit_price:modal.line.unit_price}} fields={[['unit_price','Unit price (USD)','number']]} onClose={()=>setModal('')} onSave={v=>{change({lines:draft.lines.map((l,i)=>i===modal.index?{...l,unit_price:Number(v.unit_price),manual_price:true}:l)});setModal('');}} note="A manual price requires verified cost and Damon or Jacobe’s approval."/>}
 {modal==='review'&&<Modal title="Create order" onClose={()=>!busy&&setModal('')}><div className="cw-form"><h3>{customer?.company||customer?.name}</h3><p>{draft.lines.length} products · {money(totals?.total)}</p><Address address={draft.shipping_address}/><p>This creates one order for your team, an unpaid invoice in Finance, and a QuickBooks sync request. Fulfillment waits for the normal payment, credit and stock checks.</p>{error&&<p className="cw-error">{error}</p>}</div><footer><button disabled={busy} onClick={()=>setModal('')}>Back</button><button className="primary" disabled={busy} onClick={()=>save('submit')}>{busy?'Creating order…':'Create order'}</button></footer></Modal>}
 </main></AdminShell>;
}
function CustomerPicker({onSelect,onClose}){const [q,setQ]=useState(''),[selectError,setSelectError]=useState(''),{data,loading,error}=useCommerce({kind:'customers',q,limit:30});async function select(c){try{const r=await commerceRequest({kind:'customers',id:c.id});onSelect(r.data);}catch(e){setSelectError(e.message);}}return <Modal title="Select customer" onClose={onClose}><div className="cw-form"><input aria-label="Find customer" placeholder="Search name, company or email" value={q} onChange={e=>setQ(e.target.value)}/>{loading&&<p>Searching…</p>}{(error||selectError)&&<p role="alert">{error||selectError}</p>}<div className="cw-choice-list">{data?.rows?.filter(c=>c.status!=='archived').map(c=><button key={c.id} onClick={()=>select(c)}><strong>{c.name}</strong><small>{c.company} · {c.email}</small></button>)}</div>{data?.rows?.length===0&&<p>No customers match this search.</p>}</div></Modal>;}
function ProductPicker({selected,onAdd,onClose}){const [q,setQ]=useState(''),[chosen,setChosen]=useState([]),{data,loading,error}=useCommerce({kind:'products',q,filter:'active',limit:50});const existing=new Set(selected.map(l=>l.product_id));return <Modal title="Select products" wide onClose={onClose}><div className="cw-form"><input aria-label="Find products" placeholder="Search by product name or SKU" value={q} onChange={e=>setQ(e.target.value)}/>{loading&&<p>Searching…</p>}{error&&<p role="alert">{error}</p>}<div className="co-product-picker">{data?.rows?.map(p=><label key={p.id}><input type="checkbox" disabled={existing.has(p.id)} checked={chosen.some(c=>c.id===p.id)||existing.has(p.id)} onChange={e=>setChosen(rows=>e.target.checked?[...rows,p]:rows.filter(r=>r.id!==p.id))}/>{p.image&&<img src={p.image} alt=""/>}<span><strong>{p.name}</strong><small>{p.variant} · {p.sku}</small></span><span>{money(p.retail)}<small>{existing.has(p.id)?'Already added':'Retail'}</small></span></label>)}</div>{data?.rows?.length===0&&<p>No active products match this search.</p>}</div><footer><span>{chosen.length} selected</span><button onClick={onClose}>Cancel</button><button className="primary" disabled={!chosen.length} onClick={()=>onAdd(chosen)}>Add products</button></footer></Modal>;}
function AddressEditor({address,title,onSave,onClose}){return <SimpleFields title={title} initial={address} fields={addressFields.map(([k,v])=>[k,v,'text'])} onClose={onClose} onSave={v=>onSave({...v,id:address?.id||crypto.randomUUID()})}/>;}
function SimpleFields({title,initial,fields,onSave,onClose,note}){const [value,setValue]=useState(initial);return <Modal title={title} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(value);}}><div className="cw-form">{note&&<p className="cw-muted">{note}</p>}{fields.map(([key,label,type])=><label key={key}>{label}<input aria-label={label} type={type} min={type==='number'?0:undefined} step={type==='number'?'.01':undefined} value={value[key]??''} onChange={e=>setValue({...value,[key]:e.target.value})}/></label>)}</div><footer><button type="button" onClick={onClose}>Cancel</button><button className="primary">Done</button></footer></form></Modal>;}
