import {useState} from 'react';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
export function CustomerTools(){
 const [data,setData]=useState(null),[report,setReport]=useState(null),[source,setSource]=useState(''),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(''),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){setError('');try{const [d,f]=await Promise.all([workspaceRequest('/api/admin/organization-merge'),workspaceRequest('/api/telemetry/funnel')]);setData(d);setReport(f.report);}catch(e){setError(e.message);}}
 async function act(action){setBusy(true);setError('');try{const r=await postWorkspace('/api/admin/organization-merge',{action,source_id:source,target_id:target,reason,fingerprint:preview?.fingerprint,confirm_target:confirm});if(action==='preview')setPreview(r.preview);else{setPreview(null);setMessage('Merge saved. Reload the customer list to see the updated accounts.');await load();}}catch(e){setError(e.message);}finally{setBusy(false);}}
 const invalidate=()=>{setPreview(null);setConfirm('');};
 return <details className="ws-card" style={{margin:24}}><summary>Customer cleanup and quote funnel</summary><button className="ws-button" onClick={load}>Load review</button>{error&&<p className="ws-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{data&&<><h2>Duplicate company review</h2><p>Suggestions use normalized company names. Nothing merges automatically or joins people by email domain.</p><ul>{data.candidates.map((g,i)=><li key={i}>{g.map(o=>o.name+' ('+o.id+')').join(' / ')}</li>)}</ul><div className="ws-grid"><label>Merge from<select value={source} onChange={e=>{setSource(e.target.value);invalidate();}}><option value="">Choose company</option>{data.organizations.map(o=><option key={o.id} value={o.id}>{o.name} · {o.id}</option>)}</select></label><label>Keep company<select value={target} onChange={e=>{setTarget(e.target.value);invalidate();}}><option value="">Choose company</option>{data.organizations.map(o=><option key={o.id} value={o.id}>{o.name} · {o.id}</option>)}</select></label><label>Reason<input value={reason} onChange={e=>{setReason(e.target.value);invalidate();}}/></label></div><button className="ws-button" disabled={busy||!source||!target||source===target||!reason.trim()} onClick={()=>act('preview')}>Preview changes</button>{preview&&<div className="ws-note"><p>{preview.source} → {preview.target}</p><ul>{Object.entries(preview.counts).map(([k,v])=><li key={k}>{k}: {v} records</li>)}</ul><p>Source accounts move to the kept company and must sign in again. Conflicting commercial policies, duplicate memberships and distributor ownership block this operation. The original records are retained in the merge audit.</p><label>Type the kept company ID: {target}<input value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="ws-button" disabled={busy||confirm!==target} onClick={()=>act('merge')}>Apply reviewed merge</button></div>}</>}{report&&<><h2>Quote funnel · last 30 days</h2><p>{report.sessions} observed sessions · {report.converted} reported conversions · {report.inferred_abandoned} inactive without conversion for 30 minutes.</p><p>These are browser-reported events; incomplete tracking and blocked requests can affect counts.</p><ul>{Object.entries(report.intents).map(([k,v])=><li key={k}>{k}: {v.sessions} sessions, {v.converted} conversions, {v.abandoned} inactive</li>)}</ul>{[['Sources',report.sources],['Categories',report.categories],['Last observed stage',report.last_stages]].map(([title,group])=><details key={title}><summary>{title}</summary><ul>{Object.entries(group||{}).map(([k,v])=><li key={k}>{k}: {v}</li>)}</ul></details>)}<details><summary>Stages</summary><ul>{Object.entries(report.stages).map(([k,v])=><li key={k}>{k.replaceAll('_',' ')}: {v}</li>)}</ul></details></>}</details>;
}
