import {useEffect,useState} from 'react';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {auth} from '../../lib/auth.js';
export function OrderTimeline({orderId}){
 const session=auth.use();const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{let active=true;workspaceRequest(`/api/admin/order-detail?order_id=${encodeURIComponent(orderId)}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[orderId]);
 async function decide(action){setBusy(true);setError('');try{const r=await postWorkspace('/api/admin/order-approvals',{order_id:orderId,action,reason});setData(d=>({...d,order:{...d.order,approval:r.approval}}));setReason('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function resume(){setBusy(true);setError('');try{const r=await postWorkspace('/api/admin/order-resume',{order_id:orderId});setMessage(r.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section style={{marginTop:24}}><h3>Order timeline</h3>{error&&<p className="ws-error" role="alert">{error}</p>}{message&&<p role="status" className="ws-note">{message}</p>}{data&&<>{Number(data.order.total)>10000&&<div className="ws-note"><h3>Damon approval: {data.order.approval?.status||'Required'}</h3><p>{data.order.approval?.reason||'Review this order before payment setup or fulfillment.'}</p>{session?.email?.toLowerCase()==='damon@unitemedical.net'&&<><label>Decision reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="ws-actions"><button className="ws-button primary" disabled={busy||!reason.trim()} onClick={()=>decide('approve')}>Approve reviewed order</button><button className="ws-button" disabled={busy||!reason.trim()} onClick={()=>decide('reject')}>Reject</button></div></>}</div>}{data.order.approval?.status==='approved'&&!data.order.payment_url&&!['paid','terms_approved'].includes(data.order.payment_status)&&<button className="ws-button primary" disabled={busy} onClick={resume}>Continue to payment setup</button>}<ul className="ws-list">{data.events.map(e=><li key={`${e.type}:${e.id}`} className="ws-row"><div><strong>{e.type.replaceAll('_',' ')} · {e.status.replaceAll('_',' ')}</strong><p>{e.description||e.id}</p><span className="ws-muted">{e.at?new Date(e.at).toLocaleString():'Time unavailable'}{e.actor?` · ${e.actor}`:''}</span></div></li>)}</ul>{!data.events.length&&<p>No linked activity recorded yet.</p>}</>}</section>;
}
