import {useState} from 'react';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {db} from '../../lib/db.js';
import '../../styles/workspace.css';
export function QuoteDeliveryReview({quoteId}){
 const [addresses,setAddresses]=useState(null),[form,setForm]=useState({carrier:'fedex',service:'fedex_ground'}),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await workspaceRequest(`/api/admin/quote-delivery?quote_id=${encodeURIComponent(quoteId)}`);setAddresses(r.addresses);}catch(e){setError(e.message);}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await postWorkspace('/api/admin/quote-delivery',{...form,quote_id:quoteId});db.applyRemoteSnapshot({quotes:[r.quote]});setMessage('Delivery reviewed for 24 hours. Issue the revised quote to send the customer its confirmed total.');setAddresses(null);}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <details className="um-workspace ws-card" style={{margin:'20px 0',padding:20}}><summary>Review delivered price</summary><p>Confirm the actual carton, destination, shipping and tax. This creates a new draft and invalidates earlier acceptance links.</p><button className="ws-button" onClick={load}>Load customer addresses</button>{error&&<p role="alert" className="ws-error">{error}</p>}{message&&<p role="status">{message}</p>}{addresses&&<form onSubmit={save}><label>Ship to<select required value={form.address_id||''} onChange={e=>setForm({...form,address_id:e.target.value})}><option value="">Choose address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.line1}, {a.city}, {a.state} {a.zip}</option>)}</select></label>{!addresses.length&&<p>Add the customer’s shipping address before reviewing delivery.</p>}<label>Carrier<select value={form.carrier} onChange={e=>setForm({...form,carrier:e.target.value})}>{['fedex','ups','stamps_com'].map(c=><option key={c}>{c}</option>)}</select></label><div className="ws-grid">{[['service','Carrier service code','text'],['weight','Packed weight (lb)','number'],['length','Length (in)','number'],['width','Width (in)','number'],['height','Height (in)','number'],['freight','Shipping and handling ($)','number'],['tax','Tax ($)','number'],['shipping_evidence','Carrier quote and handling evidence','text'],['tax_evidence','Tax or exemption evidence','text']].map(([key,label,type])=><label key={key}>{label}<input required type={type} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><button className="ws-button primary" disabled={busy||!form.address_id}>Save reviewed delivery</button></form>}</details>;
}
