import {useEffect,useState} from 'react';
import {postWorkspace} from '../../lib/workspaceRequest.js';
const TITLES={correct_invoice:'Correct unpaid freight invoice',return_to_planning:'Return shipment to planning',cancel_shipment:'Cancel this allocation'};
export function ShipmentRecovery({row,permissions,disabled,onDirty,onSaved}){
 const [action,setAction]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[voidReference,setVoidReference]=useState(''),[carrierCost,setCarrierCost]=useState(''),[tax,setTax]=useState(''),[custody,setCustody]=useState(false),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{onDirty(!!action);return()=>onDirty(false);},[action,onDirty]);
 const freight=Math.round((Number(carrierCost)*(1+Number(row.correction_markup_pct??20)/100)+Number(row.correction_handling??0))*100)/100,total=Math.round((freight+Number(tax))*100)/100;
 const closed=['shipped','delivered','cancelled'].includes(row.status)||['shipped','delivered','cancelled','canceled','refunded','closed'].includes(row.order.status);
 const options=closed?[]:[...(permissions.finance&&row.status==='planned'&&row.phase==='later'&&row.invoice_id&&Number(row.balance)===Number(row.amount)?['correct_invoice']:[]),...(permissions.warehouse&&['inventory_reserved','ready_to_ship'].includes(row.status)?['return_to_planning']:[]),...(permissions.cancel?['cancel_shipment']:[])];
 if(!options.length)return null;
 function reset(next=''){setAction(next);setReason('');setReference('');setVoidReference('');setCarrierCost('');setTax('');setCustody(false);setConfirm(false);setError('');}
 async function save(e){e.preventDefault();if(!confirm||busy)return;setBusy(true);setError('');try{await postWorkspace('/api/orders/shipments',{action,order_id:row.order.id,shipment_id:row.id,expected_revision:row.order.revision,reason,reference,label_void_reference:voidReference,carrier_cost:carrierCost,tax,expected_total:total,goods_in_warehouse:custody});await onSaved(action);setAction('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="uw-followup" aria-label="Shipment corrections"><h3>Need to correct something?</h3>{!action?<div className="uw-detail-actions">{options.map(option=><button type="button" className="uw-button quiet" key={option} disabled={disabled} onClick={()=>reset(option)}>{TITLES[option]}</button>)}</div>:<form onSubmit={save}><h4>{TITLES[action]}</h4>
 <p>{action==='correct_invoice'?'This recalculates later freight from the verified carrier cost and configured markup. It keeps the prior invoice revision and requires fresh customer approval. Paid or externally posted invoices need accounting reconciliation.':action==='return_to_planning'?'Release only this allocation’s reserved stock. On-hand quantities and payments stay unchanged. Ashley must review and reserve it again before picking.':'Cancel only this allocation. Goods already with the carrier cannot be cancelled here. Ashley receives an accounting/refund review and Jacobe receives a customer follow-up. No refund or credit is issued automatically.'}</p>
 {action==='correct_invoice'?<><label>Verified carrier cost<input type="number" required min="0" step="0.01" value={carrierCost} onChange={e=>setCarrierCost(e.target.value)}/></label><label>Corrected tax<input type="number" required min="0" step="0.01" value={tax} onChange={e=>setTax(e.target.value)}/></label>{carrierCost!==''&&tax!==''&&Number.isFinite(total)&&<p role="status"><strong>Corrected invoice total: ${total.toFixed(2)}</strong><br/>Freight ${freight.toFixed(2)} · tax ${Number(tax).toFixed(2)}. Based on {row.correction_markup_pct??20}% markup and ${Number(row.correction_handling??0).toFixed(2)} handling.</p>}</>:<label className="uw-checkbox"><input type="checkbox" required checked={custody} onChange={e=>setCustody(e.target.checked)}/> All goods in this allocation remain in the warehouse; no carrier has custody.</label>}
 {action!=='correct_invoice'&&row.status==='ready_to_ship'&&<label>Carrier label void confirmation<input required maxLength={200} value={voidReference} onChange={e=>setVoidReference(e.target.value)}/><span>Void the actual label in the carrier system before saving. This form records that confirmation.</span></label>}
 <label>Correction evidence reference<input required maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Reason for correction<textarea required rows={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 <label className="uw-checkbox"><input type="checkbox" required checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> I reviewed this allocation and the effect described above.</label>
 {error&&<p className="uw-error" role="alert">{error}</p>}<div className="uw-detail-actions"><button className="uw-button primary" disabled={busy||!confirm}>{busy?'Saving…':TITLES[action]}</button><button type="button" className="uw-button quiet" disabled={busy} onClick={()=>reset()}>Discard correction</button></div></form>}</section>;
}
