import {useState} from 'react';
export function ShipmentPlanReview({order,items,onSaved}){
 const [nowQty,setNowQty]=useState({}),[reason,setReason]=useState(''),[cost,setCost]=useState(''),[date,setDate]=useState(''),[selected,setSelected]=useState(''),[reference,setReference]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function action(kind){setBusy(true);setMessage('');try{
  const body={order_id:order.id,expected_revision:order.shipping_plan_revision||0,action:kind,reason,shipment_id:selected,carrier_cost:cost===''?null:Number(cost),customer_approval_reference:reference,payment_reference:reference,amount:cost===''?null:Number(cost)};
  if(kind==='save_plan'){const first=[],later=[];for(const item of items){const qty=Number(nowQty[item.sku]??item.qty);if(qty>0)first.push({sku:item.sku,qty});if(qty<item.qty)later.push({sku:item.sku,qty:item.qty-qty});}body.shipments=[{id:'initial',items:first},{id:'backorder',items:later,carrier_cost:body.carrier_cost,expected_date:date||null}];}
  const r=await fetch('/api/admin/shipment-plan',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw new Error(b.error.replaceAll('_',' '));setMessage('Saved. Accounting follow-up and customer update queued.');onSaved();
 }catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <details className="ws-details"><summary>Shipping allocation and later freight</summary><a className="ws-button" href="/staff/shipments">Open shipment workspace →</a><p>Unite-caused splits: carrier cost plus 20%; $15 handling once per order. Unknown later freight remains pending until Jacobe records the customer’s approval. Use the shipment workspace to review tax, approve the invoice, record payment, and release each shipment.</p>{!order.shipment_plan?.length?<><h3>Plan two shipments</h3>{items.map(i=><label key={i.id}>{i.sku} · {i.qty} ordered — ships now<input type="number" min="0" max={i.qty} value={nowQty[i.sku]??i.qty} onChange={e=>setNowQty({...nowQty,[i.sku]:e.target.value})}/></label>)}<label>Known later shipment date (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></>:<>{order.shipment_plan.map(s=><p key={s.id}><strong>{s.id}:</strong> {s.items.map(i=>`${i.sku} × ${i.qty}`).join(', ')} · {s.expected_date||'Awaiting supplier confirmation'} · {s.charge.final_amount==null?'Freight pending':`$${s.charge.final_amount.toFixed(2)}`} · {s.charge.approval_status} · Payment: {s.charge.payment_status}</p>)}<label>Affected shipment<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select shipment</option>{order.shipment_plan.filter(s=>s.phase==='later').map(s=><option key={s.id}>{s.id}</option>)}</select></label><label>Customer approval or payment reference<input value={reference} onChange={e=>setReference(e.target.value)}/></label></>}<label>Later carrier cost / payment amount (leave blank while unknown)<input type="number" min="0" step="0.01" value={cost} onChange={e=>setCost(e.target.value)}/></label><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="ws-actions">{(order.shipment_plan?.length?[['set_later_freight','Set carrier cost'],['record_customer_approval','Record customer approval (Jacobe)'],['waive_freight','Waive later freight']]:[['save_plan','Save shipment plan']]).map(([kind,label])=><button key={kind} className="ws-button" disabled={busy||!reason.trim()} onClick={()=>action(kind)}>{label}</button>)}</div>{message&&<p role="status">{message}</p>}</details>;
}
