import {ShipmentRecovery} from './ShipmentRecovery.jsx';
import {useCallback,useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {AdminShell} from '../../components/layout/AdminShell.jsx';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
import {useSEO} from '../../lib/seo.js';
const money=v=>v==null?'Awaiting review':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
export function StaffShipments(){
  useSEO({title:'Split shipments · Unite',noindex:true});
  const [data,setData]=useState(null),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[reason,setReason]=useState(''),[reference,setReference]=useState(''),[tax,setTax]=useState(''),[carrier,setCarrier]=useState(''),[tracking,setTracking]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [recoveryDirty,setRecoveryDirty]=useState(false);
  const formDirty=!!(reason||reference||tax||carrier||tracking),dirty=formDirty||recoveryDirty;
  const load=useCallback(async()=>{try{setData(await workspaceRequest('/api/orders/shipments'));setError('');}catch(e){setError(e.message);}},[]);
  useEffect(()=>{const c=new AbortController();workspaceRequest('/api/orders/shipments',{signal:c.signal}).then(r=>{if(!c.signal.aborted)setData(r);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
  const rows=(data?.orders||[]).flatMap(order=>order.shipments.map(s=>({...s,order,key:`${order.id}:${s.id}`}))).filter(s=>`${s.order.id} ${s.id} ${s.items.map(i=>i.sku).join(' ')} ${s.tracking_number||''}`.toLowerCase().includes(search.toLowerCase()));
  const row=rows.find(s=>s.key===selected)||rows[0],p=data?.permissions||{};
  let action=null,title='';
  if(row?.status==='planned'){
    if(row.phase==='later'&&!row.waived&&!row.invoice_id){action=p.finance?'prepare_invoice':null;title='Ashley reviews freight and tax';}
    else if(row.phase==='later'&&!row.waived&&!row.customer_approved){action=p.customer?'approve_invoice':null;title='Jacobe records customer approval';}
    else if(row.phase==='later'&&!row.waived&&row.payment_status!=='paid')title='Ashley records payment against the freight invoice';
    else {action=p.finance?'release':null;title='Ashley clears this shipment for picking';}
  }else if(row?.status==='inventory_reserved'){action=p.warehouse?'record_label':null;title='Darren records the carrier label';}
  else if(row?.status==='ready_to_ship'){action=p.warehouse?'handoff':null;title='Darren confirms carrier custody';}
  else title=row?.status==='cancelled'?'Cancelled · accounting review required':'Shipment complete';
  if(['cancelled','canceled','refunded','shipped','delivered','closed'].includes(row?.order.status)||row?.status==='cancelled')action=null;
  function discard(){setReason('');setReference('');setTax('');setCarrier('');setTracking('');}
  async function submit(e){e.preventDefault();if(!row||!action||recoveryDirty)return;setBusy(true);setError('');setNotice('');try{await postWorkspace('/api/orders/shipments',{order_id:row.order.id,shipment_id:row.id,expected_revision:row.order.revision,action,reason,reference,tax,carrier,tracking});discard();setNotice(action==='handoff'?'Carrier handoff saved. Stock and shipment status updated; Jacobe has a tracking follow-up.':action==='record_label'?'Tracking saved. Shipment remains ready until custody is confirmed.':'Saved. The next step is ready for the responsible teammate.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <AdminShell active="shipments" unsavedChanges={dirty}><main id="main" className="uw-work-page"><header className="uw-page-heading"><div><span className="uw-eyebrow">Order coordination</span><h1>One shipment at a time.</h1><p>Follow each part from the freight review to the final handoff.</p></div><button className="uw-button" disabled={dirty||busy} onClick={load}>Refresh</button></header>{error&&<p className="uw-error" role="alert">{error}</p>}{notice&&<p className="uw-notice" role="status">{notice}</p>}
  <div className={`uw-work-grid ${row?'has-detail':''}`}><section className="uw-work-list"><div className="uw-queue-heading"><h2>Split shipments</h2><label className="uw-search"><input type="search" aria-label="Find a shipment" placeholder="Order, product, or tracking" disabled={dirty} value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{!data&&!error?<p className="uw-empty">Loading shipments…</p>:!rows.length?<p className="uw-empty">{error?'Could not load shipments.':'No split shipments match. Create allocations from the order’s shipping plan.'}</p>:<ul className="uw-queue">{rows.map(s=><li key={s.key}><button className={`uw-work-row ${s.key===row.key?'is-selected':''}`} aria-pressed={s.key===row.key} onClick={()=>{if(dirty){setNotice('Save or discard before opening another shipment.');return;}setSelected(s.key);}}><span className="uw-row-copy"><strong>{s.order.id}</strong><span>{s.id} · {s.items.reduce((n,i)=>n+i.qty,0)} units</span></span><span className="uw-badge">{s.status.replaceAll('_',' ')}</span></button></li>)}</ul>}</section>
  {row&&<aside className="uw-detail"><span className="uw-eyebrow">{row.order.id}</span><h2>{row.id}</h2><dl className="uw-facts">{[['Products',row.items.map(i=>`${i.sku} × ${i.qty}`).join(', ')],['Expected date',row.expected_date||'Awaiting supplier confirmation'],['Status',row.status.replaceAll('_',' ')],['Tracking',row.tracking_number],['Carrier',row.carrier],...('amount'in row&&row.phase==='later'?[['Freight',row.waived?'Waived':money(row.freight)],['Tax',money(row.tax)],['Invoice total',money(row.amount)],['Customer approval',row.customer_approved?'Recorded':'Pending'],['Freight payment',row.payment_status]]:[])].filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{!recoveryDirty&&<h3>{title}</h3>}
  {row.invoice_id&&p.finance&&<Link className="uw-button" to={`/admin/finance?invoice=${encodeURIComponent(row.invoice_id)}`}>Open freight invoice</Link>}
  {action&&!recoveryDirty?<form className="uw-followup" onSubmit={submit}>{action==='prepare_invoice'&&<><p>Enter the verified tax on this additional freight charge. Use an explicit zero with its exemption or calculation reference when applicable.</p><label>Verified tax<input type="number" min="0" step="0.01" required value={tax} onChange={e=>setTax(e.target.value)}/></label></>}{action==='approve_invoice'&&<p>Confirm the customer agreed to the full invoice total, including tax.</p>}{action==='record_label'&&<><p>Use a label already issued by the carrier or the approved shipping system.</p><label>Carrier<input required value={carrier} onChange={e=>setCarrier(e.target.value)}/></label><label>Tracking number<input required value={tracking} onChange={e=>setTracking(e.target.value)}/></label></>}{action==='handoff'&&<p>Confirm the goods actually transferred to the carrier. A label alone is insufficient.</p>}<label>{action==='handoff'?'Pickup scan, signed BOL, or custody reference':action==='record_label'?'Carrier label / booking reference':action==='prepare_invoice'?'Tax calculation or exemption reference':action==='approve_invoice'?'Customer approval reference':'Payment review reference'}<input required maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Note<textarea required rows={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="uw-detail-actions"><button className="uw-button primary" disabled={busy||recoveryDirty}>{busy?'Saving…':action==='prepare_invoice'?'Create freight invoice':action==='approve_invoice'?'Record customer approval':action==='release'?'Reserve this shipment’s stock':action==='record_label'?'Save tracking':'Confirm custody handoff'}</button><button className="uw-button quiet" type="button" disabled={busy} onClick={discard}>Discard changes</button></div></form>:!recoveryDirty&&!['shipped','cancelled'].includes(row.status)&&<p className="uw-notice">The next step belongs to the teammate named above.</p>}<ShipmentRecovery key={`${row.key}:${row.order.revision}`} row={row} permissions={p} disabled={formDirty||busy} onDirty={setRecoveryDirty} onSaved={async action=>{setNotice(action==='correct_invoice'?'Invoice corrected. Jacobe must obtain fresh customer approval.':action==='cancel_shipment'?'Allocation cancelled. Ashley and Jacobe have follow-up tasks; no refund was issued.':'Shipment returned to planning. Reservations released; on-hand stock unchanged.');await load();}}/></aside>}
  </div></main></AdminShell>;
}
