import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {WELL_REQUEST_STATES} from '../../data/welllinkPublic.js';
import {workspaceRequest,postWorkspace} from '../../lib/workspaceRequest.js';
const endpoint='/api/welllink/requests';
function RequestReview({row,onSaved}) {
  const [status,setStatus]=useState(row.status),[note,setNote]=useState(row.staff_note||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function save(e){e.preventDefault();setBusy(true);setError('');try{const result=await postWorkspace(endpoint,{action:'review',id:row.id,version:row.version,status,note});onSaved(result.request);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <details className="wl-intake-row"><summary><span><strong>{row.facility}</strong><small>{row.organization} · {row.kind} · {row.email}</small></span><span>{WELL_REQUEST_STATES[row.status]}</span></summary><div className="wl-intake-body"><dl>{[['Contact',`${row.name} · ${row.title}`],['Email',row.email],['Phone',row.phone],['Ship to',`${row.address}, ${row.city}, ${row.state} ${row.zip}`],['Institution ID',row.institution_id],['Unite account',row.account_number],['Participation (self-reported)',row.participation_status],['Products',row.skus.join(', ')],['Case quantities',row.quantity],['Sample shipping',row.carrier],['Carrier account',row.carrier_account?`${row.carrier_account} · authorization ${row.carrier_authorization?'provided':'missing'}`:null],['Marketing opt-in',row.marketing_opt_in?'Yes':'No'],['Referral',Object.entries(row.referral||{}).filter(([,v])=>v).map(([k,v])=>`${k}: ${v}`).join(' · ')],['Received',new Date(row.created_at).toLocaleString()]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><form onSubmit={save}><fieldset disabled={busy}><label>Member-visible status<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(WELL_REQUEST_STATES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Internal review note<textarea required maxLength={2000} rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record roster source, facility match, CPF reference, missing steps, and follow-up."/></label><p>Status updates do not enable pricing. Confirm roster eligibility, requester authority, accepted CPF and effective date before providing a contract quote.</p>{error&&<p role="alert" className="wl-error">{error}</p>}<button className="wl-button primary" disabled={busy}>{busy?'Saving…':'Save review'}</button></fieldset></form></div></details>;
}
export function WellLinkRequests() {
  const [rows,setRows]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();workspaceRequest(`${endpoint}?view=staff`,{signal:controller.signal}).then(r=>setRows(r.requests)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[retry]);
  return <section className="wl-panel"><div className="wl-panel-heading"><div><h2>Member requests</h2><p>Facility access, contract quotes and sample boxes. Initial owner: Damon.</p></div><Link className="wl-button" to="/welllink">View public page ↗</Link></div>{error?<div className="wl-error" role="alert">{error}<button className="wl-button" onClick={()=>{setError('');setRetry(n=>n+1);}}>Try again</button></div>:!rows?<p role="status">Loading requests…</p>:!rows.length?<div className="wl-empty"><h3>No member requests yet</h3><p>Requests from the public WellLink page will appear here and in the CRM.</p></div>:<>{rows.map(row=><RequestReview key={`${row.id}:${row.version}`} row={row} onSaved={saved=>setRows(current=>current.map(r=>r.id===saved.id?saved:r))}/>)}<p className="wl-intake-limit">Showing up to 200 recent requests. All requests remain in the CRM and private records.</p></>}</section>;
}
